import Mathlib
/-! Generated by `lean/make_web.py` from `FrcLedger/Causality.lean` with `FrcLedger/Theme/Extension`, `FrcLedger/Keys/Extension` inlined — one self-contained file for the Lean web editor. Edit the modules, not this file. -/

/-! inlined: FrcLedger/Theme/Extension.lean (verbatim, minus its import lines) -/

/-!
# FrcLedger.Theme.Extension — the quadratic extension (the extension theme, ledger migration task LM17)

`Ext F ν`: the elements `a + b w` of `F[w]/(w² − ν)` over a commutative ring, with its commutative ring structure,
the embedding of the base, conjugation `a + bw ↦ a − bw`, the norm `N = a² − νb²` (multiplicative, `z z̄ = N(z)`),
the star ring, and the field when `ν` is a nonsquare. Moved from 8-dirac's module, which keeps every old name as an
alias. Classical, on Mathlib's hierarchy.
-/

namespace FRC.Extension

@[ext]
structure Ext (F : Type*) (ν : F) where
  re : F
  im : F

namespace Ext
variable {F : Type*} [CommRing F] {ν : F}

instance : Zero (Ext F ν) := ⟨⟨0, 0⟩⟩
instance : One (Ext F ν) := ⟨⟨1, 0⟩⟩
instance : Add (Ext F ν) := ⟨fun z z' => ⟨z.re + z'.re, z.im + z'.im⟩⟩
instance : Neg (Ext F ν) := ⟨fun z => ⟨-z.re, -z.im⟩⟩
instance : Sub (Ext F ν) := ⟨fun z z' => ⟨z.re - z'.re, z.im - z'.im⟩⟩
instance : Mul (Ext F ν) := ⟨fun z z' => ⟨z.re * z'.re + ν * (z.im * z'.im), z.re * z'.im + z.im * z'.re⟩⟩
instance : SMul ℕ (Ext F ν) := ⟨fun n z => ⟨n • z.re, n • z.im⟩⟩
instance : SMul ℤ (Ext F ν) := ⟨fun n z => ⟨n • z.re, n • z.im⟩⟩

@[simp] theorem zero_re : (0 : Ext F ν).re = 0 := rfl
@[simp] theorem zero_im : (0 : Ext F ν).im = 0 := rfl
@[simp] theorem one_re : (1 : Ext F ν).re = 1 := rfl
@[simp] theorem one_im : (1 : Ext F ν).im = 0 := rfl
@[simp] theorem add_re (z z' : Ext F ν) : (z + z').re = z.re + z'.re := rfl
@[simp] theorem add_im (z z' : Ext F ν) : (z + z').im = z.im + z'.im := rfl
@[simp] theorem neg_re (z : Ext F ν) : (-z).re = -z.re := rfl
@[simp] theorem neg_im (z : Ext F ν) : (-z).im = -z.im := rfl
@[simp] theorem sub_re (z z' : Ext F ν) : (z - z').re = z.re - z'.re := rfl
@[simp] theorem sub_im (z z' : Ext F ν) : (z - z').im = z.im - z'.im := rfl
@[simp] theorem mul_re (z z' : Ext F ν) : (z * z').re = z.re * z'.re + ν * (z.im * z'.im) := rfl
@[simp] theorem mul_im (z z' : Ext F ν) : (z * z').im = z.re * z'.im + z.im * z'.re := rfl
@[simp] theorem nsmul_re (n : ℕ) (z : Ext F ν) : (n • z).re = n • z.re := rfl
@[simp] theorem nsmul_im (n : ℕ) (z : Ext F ν) : (n • z).im = n • z.im := rfl
@[simp] theorem zsmul_re (n : ℤ) (z : Ext F ν) : (n • z).re = n • z.re := rfl
@[simp] theorem zsmul_im (n : ℤ) (z : Ext F ν) : (n • z).im = n • z.im := rfl

instance : CommRing (Ext F ν) where
  add_assoc _ _ _ := by ext <;> simp [add_assoc]
  zero_add _ := by ext <;> simp
  add_zero _ := by ext <;> simp
  add_comm _ _ := by ext <;> simp [add_comm]
  nsmul := (· • ·)
  nsmul_zero _ := by ext <;> simp
  nsmul_succ _ _ := by ext <;> simp [add_smul]
  zsmul := (· • ·)
  zsmul_zero' _ := by ext <;> simp
  zsmul_succ' _ _ := by ext <;> simp [add_smul]
  zsmul_neg' _ _ := by ext <;> simp [add_smul] <;> ring
  neg_add_cancel _ := by ext <;> simp
  sub_eq_add_neg _ _ := by ext <;> simp [sub_eq_add_neg]
  mul_assoc _ _ _ := by ext <;> simp <;> ring
  one_mul _ := by ext <;> simp
  mul_one _ := by ext <;> simp
  left_distrib _ _ _ := by ext <;> simp <;> ring
  right_distrib _ _ _ := by ext <;> simp <;> ring
  zero_mul _ := by ext <;> simp
  mul_zero _ := by ext <;> simp
  mul_comm _ _ := by ext <;> simp <;> ring

def ofBase (a : F) : Ext F ν := ⟨a, 0⟩
def w : Ext F ν := ⟨0, 1⟩
def conj (z : Ext F ν) : Ext F ν := ⟨z.re, -z.im⟩
def norm (z : Ext F ν) : F := z.re * z.re - ν * (z.im * z.im)

@[simp] theorem ofBase_re (a : F) : (ofBase a : Ext F ν).re = a := rfl
@[simp] theorem ofBase_im (a : F) : (ofBase a : Ext F ν).im = 0 := rfl
@[simp] theorem w_re : (w : Ext F ν).re = 0 := rfl
@[simp] theorem w_im : (w : Ext F ν).im = 1 := rfl
@[simp] theorem conj_re (z : Ext F ν) : (conj z).re = z.re := rfl
@[simp] theorem conj_im (z : Ext F ν) : (conj z).im = -z.im := rfl

theorem w_sq : (w : Ext F ν) ^ 2 = ofBase ν := by ext <;> simp [sq]
theorem conj_mul (z z' : Ext F ν) : conj (z * z') = conj z * conj z' := by ext <;> simp <;> ring
theorem conj_add (z z' : Ext F ν) : conj (z + z') = conj z + conj z' := by ext <;> simp [add_comm]
theorem conj_conj (z : Ext F ν) : conj (conj z) = z := by ext <;> simp
theorem conj_one : conj (1 : Ext F ν) = 1 := by ext <;> simp
theorem mul_conj (z : Ext F ν) : z * conj z = ofBase (norm z) := by ext <;> simp [norm] <;> ring
/-- 8:A2 — the norm is multiplicative: `N(zz') = N(z)N(z')`. -/
theorem norm_mul (z z' : Ext F ν) : norm (z * z') = norm z * norm z' := by
  simp only [norm, mul_re, mul_im]; ring
theorem ofBase_mul (a b : F) : (ofBase (a * b) : Ext F ν) = ofBase a * ofBase b := by ext <;> simp
theorem ofBase_add (a b : F) : (ofBase (a + b) : Ext F ν) = ofBase a + ofBase b := by ext <;> simp
theorem ofBase_one : (ofBase 1 : Ext F ν) = 1 := rfl
theorem ofBase_zero : (ofBase 0 : Ext F ν) = 0 := rfl
theorem ofBase_injective : Function.Injective (ofBase : F → Ext F ν) := fun a b h => by
  simpa using congrArg re h
theorem conj_ofBase (a : F) : conj (ofBase a : Ext F ν) = ofBase a := by ext <;> simp
theorem conj_w : conj (w : Ext F ν) = -w := by ext <;> simp
theorem conj_eq_self_iff (z : Ext F ν) (h2 : (2 : F) ≠ 0) [NoZeroDivisors F] :
    conj z = z ↔ z.im = 0 := by
  constructor
  · intro h
    have := congrArg im h
    simp at this
    have h' : (2 : F) * z.im = 0 := by linear_combination -this
    rcases mul_eq_zero.1 h' with h0 | h0
    · exact absurd h0 h2
    · exact h0
  · intro h; ext <;> simp [h]
theorem conj_eq_neg_iff (z : Ext F ν) (h2 : (2 : F) ≠ 0) [NoZeroDivisors F] :
    conj z = -z ↔ z.re = 0 := by
  constructor
  · intro h
    have := congrArg re h
    simp at this
    have h' : (2 : F) * z.re = 0 := by linear_combination this
    rcases mul_eq_zero.1 h' with h0 | h0
    · exact absurd h0 h2
    · exact h0
  · intro h; ext <;> simp [h]

instance : StarRing (Ext F ν) where
  star := conj
  star_involutive := conj_conj
  star_mul z z' := by rw [conj_mul, mul_comm]
  star_add z z' := conj_add z z'

theorem star_def (z : Ext F ν) : star z = conj z := rfl

/-- `w` generates: `z = re + im · w`. -/
theorem eq_re_add_im_w (z : Ext F ν) : z = ofBase z.re + ofBase z.im * w := by ext <;> simp

end Ext

/-! ## The field: `ν` a nonsquare makes `K` a field -/
namespace Ext
variable {F : Type*} [Field F] {ν : F}

theorem norm_eq_zero_iff (hν : ¬ IsSquare ν) (z : Ext F ν) : norm z = 0 ↔ z = 0 := by
  constructor
  · intro h
    by_cases hb : z.im = 0
    · have : z.re * z.re = 0 := by simpa [norm, hb] using h
      ext <;> simp [hb, mul_self_eq_zero.1 this]
    · exfalso; apply hν
      refine ⟨z.re / z.im, ?_⟩
      have : z.re * z.re = ν * (z.im * z.im) := by
        simpa [norm, sub_eq_zero] using h
      rw [div_mul_div_comm, eq_div_iff (mul_ne_zero hb hb), this]
  · rintro rfl; simp [norm]

noncomputable instance instInv : Inv (Ext F ν) := ⟨fun z => ofBase (norm z)⁻¹ * conj z⟩

theorem inv_def (z : Ext F ν) : z⁻¹ = ofBase (norm z)⁻¹ * conj z := rfl

theorem mul_inv_cancel' (hν : ¬ IsSquare ν) (z : Ext F ν) (hz : z ≠ 0) : z * z⁻¹ = 1 := by
  rw [inv_def, mul_left_comm, mul_conj, ← ofBase_mul, inv_mul_cancel₀ ((norm_eq_zero_iff hν z).not.2 hz)]
  rfl

/-- 8:A2 — the field structure under `¬ IsSquare ν`, `z⁻¹ = z̄/N(z)` (a `def`, not an instance: the hypothesis is
not a class). -/
@[instance_reducible] noncomputable def field (hν : ¬ IsSquare ν) : Field (Ext F ν) where
  __ := (inferInstance : CommRing (Ext F ν))
  inv := (·⁻¹)
  exists_pair_ne := ⟨0, 1, fun h => by simpa using congrArg re h⟩
  mul_inv_cancel z hz := mul_inv_cancel' hν z hz
  inv_zero := by ext <;> simp [inv_def, norm]
  nnqsmul := _
  nnqsmul_def _ _ := rfl
  qsmul := _
  qsmul_def _ _ := rfl

end Ext

/-! ## The Lorentzian plane: the square classes and the boosts of `x² − ν t²` (3-causality's theorems, moved by the
ledger migration, task LM20; the old names `FRC.Causality.*` stay as aliases) -/

section lorentz

variable {F : Type*} [Field F]

/-- 3:B2 (Thm. nonexistence, first clause): `c² = ν` makes `ν` a square, so a nonsquare `ν` has no root. -/
theorem no_causal_root (ν c : F) (h : ¬IsSquare ν) : c ^ 2 ≠ ν := fun e => h ⟨c, by rw [← e, sq]⟩

/-- 3:B2 (the consequence): when `−1` is a square (`card F ≢ 3 mod 4`) so is `−c²`, and every coefficient of
`−c² t² + x² + y² + z²` lies in the class of squares — a Euclidean form for every `c ≠ 0`. -/
theorem neg_sq_is_square [Fintype F] (hF : Fintype.card F % 4 ≠ 3) (c : F) : IsSquare (-(c ^ 2)) := by
  obtain ⟨i, hi⟩ := FiniteField.isSquare_neg_one_iff.mpr hF
  exact ⟨i * c, by rw [show -(c ^ 2) = (-1) * c ^ 2 by ring, hi]; ring⟩

/-- 3:B3 (Lemma absorption): coefficients `a_i = w_i² a_0` are absorbed by `x_i ↦ w_i x_i`. -/
theorem absorb (a0 a1 a2 a3 w1 w2 w3 x0 x1 x2 x3 : F) (h1 : w1 ^ 2 * a0 = a1) (h2 : w2 ^ 2 * a0 = a2)
    (h3 : w3 ^ 2 * a0 = a3) :
    a0 * x0 ^ 2 + a1 * x1 ^ 2 + a2 * x2 ^ 2 + a3 * x3 ^ 2 =
    a0 * (x0 ^ 2 + (w1 * x1) ^ 2 + (w2 * x2) ^ 2 + (w3 * x3) ^ 2) := by
  rw [← h1, ← h2, ← h3]; ring

/-- 3:B5: `x² − ν t²` is anisotropic for a nonsquare `ν`. -/
theorem aniso_tx (ν t x : F) (hν : ¬IsSquare ν) (e : x ^ 2 = ν * t ^ 2) : t = 0 ∧ x = 0 := by
  by_cases ht : t = 0
  · subst ht; simp at e; exact ⟨rfl, e⟩
  · exact absurd ⟨x / t, by field_simp; linear_combination (-1 : F) * e⟩ hν

/-- 3:C2 (the finite Lorentz boost): `Λ(γ, b) = !![γ, b; νb, γ]` with `γ² − νb² = 1` preserves `x² − ν t²`. -/
theorem boost_preserves (ν γ b t x : F) (h : γ ^ 2 - ν * b ^ 2 = 1) :
    (γ * x + ν * b * t) ^ 2 - ν * (γ * t + b * x) ^ 2 = x ^ 2 - ν * t ^ 2 := by
  linear_combination (x ^ 2 - ν * t ^ 2) * h

/-- 3:C2: the boosts compose as the norm-one elements of `F(√ν)` multiply. -/
theorem boost_comp (ν γ1 b1 γ2 b2 : F) :
    !![γ1, b1; ν * b1, γ1] * !![γ2, b2; ν * b2, γ2] =
    !![γ1 * γ2 + ν * (b1 * b2), γ1 * b2 + b1 * γ2; ν * (γ1 * b2 + b1 * γ2), γ1 * γ2 + ν * (b1 * b2)] := by
  ext i j; fin_cases i <;> fin_cases j <;> simp [Matrix.mul_apply, Fin.sum_univ_two] <;> ring

/-- 3:C2: `Λ(γ, b)` is orthogonal for the Gram matrix `diag(−ν, 1)` of `Q_ν`: `Λᵀ G Λ = G`. -/
theorem boost_orthogonal (ν γ b : F) (h : γ ^ 2 - ν * b ^ 2 = 1) :
    (!![γ, b; ν * b, γ]).transpose * !![-ν, 0; 0, 1] * !![γ, b; ν * b, γ] = !![-ν, 0; 0, 1] := by
  ext i j; fin_cases i <;> fin_cases j <;> simp [Matrix.mul_apply, Fin.sum_univ_two] <;>
    first | ring1 | linear_combination (-ν) * h | linear_combination h

/-- 3:C3: `γ ≠ 0` on every boost of the Lorentzian plane (`γ = 0` would make `ν = (i/b)²`). -/
theorem gamma_ne_zero [Fintype F] (hF : Fintype.card F % 4 ≠ 3) (ν γ b : F) (hν : ¬IsSquare ν)
    (h : γ ^ 2 - ν * b ^ 2 = 1) : γ ≠ 0 := by
  rintro rfl
  obtain ⟨i, hi⟩ := FiniteField.isSquare_neg_one_iff.mpr hF
  have hb : b ≠ 0 := by rintro rfl; simp at h
  have hνb : ν * b ^ 2 = -1 := by linear_combination -h
  exact hν ⟨i / b, by field_simp; linear_combination hνb + hi⟩

/-- 3:C3: the velocity `v = −νb/γ` satisfies `γ² (ν − v²) = ν` — `γ = 1/√(1 − β²)` with `β² = v²/ν`. -/
theorem gamma_velocity (ν γ b v : F) (h : γ ^ 2 - ν * b ^ 2 = 1) (hv : v * γ = -(ν * b)) :
    γ ^ 2 * (ν - v ^ 2) = ν := by
  linear_combination ν * h - (v * γ - ν * b) * hv

/-- 3:C3 (Einstein's addition law, exact): `v₁₂ (ν + v₁v₂) = ν (v₁ + v₂)`. -/
theorem velocity_addition (ν γ1 b1 γ2 b2 v1 v2 v12 : F) (hγ : γ1 * γ2 ≠ 0)
    (hv1 : v1 * γ1 = -(ν * b1)) (hv2 : v2 * γ2 = -(ν * b2))
    (hv12 : v12 * (γ1 * γ2 + ν * (b1 * b2)) = -(ν * (γ1 * b2 + b1 * γ2))) :
    v12 * (ν + v1 * v2) = ν * (v1 + v2) := by
  have : γ1 * γ2 * (v12 * (ν + v1 * v2) - ν * (v1 + v2)) = 0 := by
    linear_combination ν * hv12 + (-v12 * ν * b2 - ν * γ2 + v12 * (v2 * γ2 + ν * b2)) * hv1 +
      (-v12 * ν * b1 - ν * γ1) * hv2
  rcases mul_eq_zero.mp this with h | h
  · exact absurd h hγ
  · exact sub_eq_zero.mp h

end lorentz

end FRC.Extension

/-! inlined: FrcLedger/Keys/Extension.lean (verbatim, minus its import lines) -/

/-!
# FrcLedger.Keys.Extension — the keyed theorems of the extension theme (ledger migration, task LM19)

One declaration per key, `FRC.LedgerML.p<key>`, generated by `make_keys.py` from the ledgers' Lean bindings: the theorem
that every row carrying the key asserts, proved from the themes alone. The paper's module keeps its declaration
`FRC.<Module>.p<key>` as an alias. Every declaration has the axioms of Mathlib's hierarchy at most (`check_axioms.py`).
-/

namespace FRC.LedgerML

-- Keys of the extension theme (generated by make_keys.py from the ledgers' Lean bindings; edit the ledgers, not this file)
/-- p03006 — 3:B2. Nonexistence of a causal square root: no $c\in\Fp$ has $c^{2}=\nu$ for $\nu\in N$; for $c\in\Fpx$ every coefficient of $-c^{2}t^{2}+x^{2}+y^{2}+z^{2}$ is a square ($-1=\im^{2}$), the form Euclidean with $\p^{3}+\p^{2}-\p$ zeros; $c=0$ gives a degenerate form. -/
theorem p03006 : (∀ {F : Type u_1} [Field F] (ν c : F), ¬IsSquare ν → c ^ (2 : ℕ) ≠ ν) ∧ ∀ {F : Type u_2} [Field F] [Fintype F], Fintype.card F % (4 : ℕ) ≠ (3 : ℕ) → ∀ (c : F), IsSquare (-c ^ (2 : ℕ)) :=
  And.intro @FRC.Extension.no_causal_root (@FRC.Extension.neg_sq_is_square)
/-- p03007 — 3:B3. Square-class absorption: if $a_{i}/a_{0}\in S$ for all $\im$ then $Q\simeq a_{0}\sum Y_{i}^{2}$ by $Y_{i}=w_{i}X_{i}$, $w_{i}^{2}=a_{i}/a_{0}$; no root of $a_{0}$ is needed, and none exists for $a_{0}\in N$ ($-a_{0}$ is a nonsquare with it). -/
theorem p03007 : ∀ {F : Type u_1} [Field F] (a0 a1 a2 a3 w1 w2 w3 x0 x1 x2 x3 : F), w1 ^ (2 : ℕ) * a0 = a1 → w2 ^ (2 : ℕ) * a0 = a2 → w3 ^ (2 : ℕ) * a0 = a3 → a0 * x0 ^ (2 : ℕ) + a1 * x1 ^ (2 : ℕ) + a2 * x2 ^ (2 : ℕ) + a3 * x3 ^ (2 : ℕ) = a0 * (x0 ^ (2 : ℕ) + (w1 * x1) ^ (2 : ℕ) + (w2 * x2) ^ (2 : ℕ) + (w3 * x3) ^ (2 : ℕ)) :=
  @FRC.Extension.absorb
/-- p03009 — 3:B5. The Witt decomposition: for $\nu\in N$ the plane $x^{2}-\nu t^{2}$ (the norm of $\Fpq$) is anisotropic and $y^{2}+z^{2}=(y+iz)(y-iz)$ hyperbolic, so $Q_{\nu}=H\perp\langle1,-\nu\rangle$, index one; for $\nu=w^{2}$ the $(t,x)$-plane is hyperbolic too, $H\perp H$. Over $\Fpq$, $\nu=c^{2}$ and $Q_{\nu}\simeq\sum X_{i}^{2}$: hyperbolic ($16\,225$ zeros at $q=25$); the extension dissolves the split. -/
theorem p03009 : ∀ {F : Type u_1} [Field F] (ν t x : F), ¬IsSquare ν → x ^ (2 : ℕ) = ν * t ^ (2 : ℕ) → t = (0 : F) ∧ x = (0 : F) :=
  @FRC.Extension.aniso_tx
/-- p03013 — 3:C2. $\Lambda(\gamma,b)$ preserves $-\nu t^{2}+x^{2}$ exactly and $\Lambda(z_{1})\Lambda(z_{2})=\Lambda(z_{1}z_{2})$: the boosts are the norm-one cycle $N^{1}\simeq C_{\p+1}$, the non-split torus, and exhaust $SO(Q_{\nu},\Fp)$ in dimension $1{+}1$ ($6$, $14$, $18$ at $5$, $13$, $17$); with $\nu\in S$ the same construction is the split torus $C_{\p-1}$ --- the two tori are the two signatures (00:C3). -/
theorem p03013 : (∀ {F : Type u_1} [Field F] (ν γ b t x : F), γ ^ (2 : ℕ) - ν * b ^ (2 : ℕ) = (1 : F) → (γ * x + ν * b * t) ^ (2 : ℕ) - ν * (γ * t + b * x) ^ (2 : ℕ) = x ^ (2 : ℕ) - ν * t ^ (2 : ℕ)) ∧ (∀ {F : Type u_2} [Field F] (ν γ1 b1 γ2 b2 : F), !![γ1, b1; ν * b1, γ1] * !![γ2, b2; ν * b2, γ2] = !![γ1 * γ2 + ν * (b1 * b2), γ1 * b2 + b1 * γ2; ν * (γ1 * b2 + b1 * γ2), γ1 * γ2 + ν * (b1 * b2)]) ∧ ∀ {F : Type u_3} [Field F] (ν γ b : F), γ ^ (2 : ℕ) - ν * b ^ (2 : ℕ) = (1 : F) → !![γ, b; ν * b, γ].transpose * !![-ν, (0 : F); (0 : F), (1 : F)] * !![γ, b; ν * b, γ] = !![-ν, (0 : F); (0 : F), (1 : F)] :=
  And.intro @FRC.Extension.boost_preserves (And.intro @FRC.Extension.boost_comp (@FRC.Extension.boost_orthogonal))
/-- p03014 — 3:C3. Velocity: $\gamma\neq0$ on every boost; $v=-\nu b/\gamma\in\Fp$; $\gamma^{2}(\nu-v^{2})=\nu$, the finite $\gamma=1/\sqrt{1-\beta^{2}}$ with $\beta^{2}=v^{2}/\nu$ ($\beta$ itself is no shell quantity, 8:B8); Einstein's law $v_{12}=(v_{1}+v_{2})/(1+v_{1}v_{2}/\nu)$ exact, the denominator never zero; $v$ is two-to-one on $N^{1}$. -/
theorem p03014 : (∀ {F : Type u_1} [Field F] [Fintype F], Fintype.card F % (4 : ℕ) ≠ (3 : ℕ) → ∀ (ν γ b : F), ¬IsSquare ν → γ ^ (2 : ℕ) - ν * b ^ (2 : ℕ) = (1 : F) → γ ≠ (0 : F)) ∧ (∀ {F : Type u_2} [Field F] (ν γ b v : F), γ ^ (2 : ℕ) - ν * b ^ (2 : ℕ) = (1 : F) → v * γ = -(ν * b) → γ ^ (2 : ℕ) * (ν - v ^ (2 : ℕ)) = ν) ∧ ∀ {F : Type u_3} [Field F] (ν γ1 b1 γ2 b2 v1 v2 v12 : F), γ1 * γ2 ≠ (0 : F) → v1 * γ1 = -(ν * b1) → v2 * γ2 = -(ν * b2) → v12 * (γ1 * γ2 + ν * (b1 * b2)) = -(ν * (γ1 * b2 + b1 * γ2)) → v12 * (ν + v1 * v2) = ν * (v1 + v2) :=
  And.intro @FRC.Extension.gamma_ne_zero (And.intro @FRC.Extension.gamma_velocity (@FRC.Extension.velocity_addition))
-- end keys

end FRC.LedgerML

/-! FrcLedger/Causality.lean -/

/-!
# 3-causality — the Euclidean–Lorentzian dichotomy, Mathlib witnesses

Rows of the predicate ledger of *Euclidean–Lorentzian Dichotomy and Algebraic Causality in Finite Ring Continuum*
(Entropy 2025, 27, 1098; tree `3-causality-20260510`), over an arbitrary finite
field `F` with `card F ≢ 3 (mod 4)` (so `−1` is a square, the shells `p = 4κ + 1` among them).  Classical
(tier 2) on Mathlib's hierarchy; the same rows are proved with no axioms in the core. Since the ledger migration
(task LM20) the theorems live in the extension theme, `FrcLedger/Theme/Extension.lean`, as `FRC.Extension.*`; the
old names below are aliases, and the predicate declarations are the aliases of their keys.
-/

namespace FRC.Causality

variable {F : Type*} [Field F]

/-! ## Old names (ledger migration, task LM20): the theorems moved to the extension theme (`FRC.Extension`,
`FrcLedger/Theme/Extension.lean`), each under its old name -/

/-- 3:B2 (Thm. nonexistence, first clause): `c² = ν` makes `ν` a square, so a nonsquare `ν` has no root. -/
theorem no_causal_root (ν c : F) (h : ¬IsSquare ν) : c ^ 2 ≠ ν :=
  FRC.Extension.no_causal_root ν c h

/-- 3:B2 (the consequence): when `−1` is a square (`card F ≢ 3 mod 4`) so is `−c²`, and every coefficient of
`−c² t² + x² + y² + z²` lies in the class of squares — a Euclidean form for every `c ≠ 0`. -/
theorem neg_sq_is_square [Fintype F] (hF : Fintype.card F % 4 ≠ 3) (c : F) : IsSquare (-(c ^ 2)) :=
  FRC.Extension.neg_sq_is_square hF c

/-- 3:B3 (Lemma absorption): coefficients `a_i = w_i² a_0` are absorbed by `x_i ↦ w_i x_i`. -/
theorem absorb (a0 a1 a2 a3 w1 w2 w3 x0 x1 x2 x3 : F) (h1 : w1 ^ 2 * a0 = a1) (h2 : w2 ^ 2 * a0 = a2)
    (h3 : w3 ^ 2 * a0 = a3) :
    a0 * x0 ^ 2 + a1 * x1 ^ 2 + a2 * x2 ^ 2 + a3 * x3 ^ 2 =
    a0 * (x0 ^ 2 + (w1 * x1) ^ 2 + (w2 * x2) ^ 2 + (w3 * x3) ^ 2) :=
  FRC.Extension.absorb a0 a1 a2 a3 w1 w2 w3 x0 x1 x2 x3 h1 h2 h3

/-- 3:B5: `x² − ν t²` is anisotropic for a nonsquare `ν`. -/
theorem aniso_tx (ν t x : F) (hν : ¬IsSquare ν) (e : x ^ 2 = ν * t ^ 2) : t = 0 ∧ x = 0 :=
  FRC.Extension.aniso_tx ν t x hν e

/-- 3:C2 (the finite Lorentz boost): `Λ(γ, b) = !![γ, b; νb, γ]` with `γ² − νb² = 1` preserves `x² − ν t²`. -/
theorem boost_preserves (ν γ b t x : F) (h : γ ^ 2 - ν * b ^ 2 = 1) :
    (γ * x + ν * b * t) ^ 2 - ν * (γ * t + b * x) ^ 2 = x ^ 2 - ν * t ^ 2 :=
  FRC.Extension.boost_preserves ν γ b t x h

/-- 3:C2: the boosts compose as the norm-one elements of `F(√ν)` multiply. -/
theorem boost_comp (ν γ1 b1 γ2 b2 : F) :
    !![γ1, b1; ν * b1, γ1] * !![γ2, b2; ν * b2, γ2] =
    !![γ1 * γ2 + ν * (b1 * b2), γ1 * b2 + b1 * γ2; ν * (γ1 * b2 + b1 * γ2), γ1 * γ2 + ν * (b1 * b2)] :=
  FRC.Extension.boost_comp ν γ1 b1 γ2 b2

/-- 3:C2: `Λ(γ, b)` is orthogonal for the Gram matrix `diag(−ν, 1)` of `Q_ν`: `Λᵀ G Λ = G`. -/
theorem boost_orthogonal (ν γ b : F) (h : γ ^ 2 - ν * b ^ 2 = 1) :
    (!![γ, b; ν * b, γ]).transpose * !![-ν, 0; 0, 1] * !![γ, b; ν * b, γ] = !![-ν, 0; 0, 1] :=
  FRC.Extension.boost_orthogonal ν γ b h

/-- 3:C3: `γ ≠ 0` on every boost of the Lorentzian plane (`γ = 0` would make `ν = (i/b)²`). -/
theorem gamma_ne_zero [Fintype F] (hF : Fintype.card F % 4 ≠ 3) (ν γ b : F) (hν : ¬IsSquare ν)
    (h : γ ^ 2 - ν * b ^ 2 = 1) : γ ≠ 0 :=
  FRC.Extension.gamma_ne_zero hF ν γ b hν h

/-- 3:C3: the velocity `v = −νb/γ` satisfies `γ² (ν − v²) = ν` — `γ = 1/√(1 − β²)` with `β² = v²/ν`. -/
theorem gamma_velocity (ν γ b v : F) (h : γ ^ 2 - ν * b ^ 2 = 1) (hv : v * γ = -(ν * b)) :
    γ ^ 2 * (ν - v ^ 2) = ν :=
  FRC.Extension.gamma_velocity ν γ b v h hv

/-- 3:C3 (Einstein's addition law, exact): `v₁₂ (ν + v₁v₂) = ν (v₁ + v₂)`. -/
theorem velocity_addition (ν γ1 b1 γ2 b2 v1 v2 v12 : F) (hγ : γ1 * γ2 ≠ 0)
    (hv1 : v1 * γ1 = -(ν * b1)) (hv2 : v2 * γ2 = -(ν * b2))
    (hv12 : v12 * (γ1 * γ2 + ν * (b1 * b2)) = -(ν * (γ1 * b2 + b1 * γ2))) :
    v12 * (ν + v1 * v2) = ν * (v1 + v2) :=
  FRC.Extension.velocity_addition ν γ1 b1 γ2 b2 v1 v2 v12 hγ hv1 hv2 hv12

-- Ledger predicates of 3-causality (generated by make_predicates.py from docs/3-causality/3-causality-ledger.json; edit the ledger, not this section)
/-- 3:B2 (p03006) — Nonexistence of a causal square root: no $c\in\Fp$ has $c^{2}=\nu$ for $\nu\in N$; for $c\in\Fpx$ every coefficient of $-c^{2}t^{2}+x^{2}+y^{2}+z^{2}$ is a square ($-1=i^{2}$), the form Euclidean with $\p^{3}+\p^{2}-\p$ zeros; $c=0$ gives a degenerate form. -/
theorem p03006 : (∀ {F : Type u_1} [Field F] (ν c : F), ¬IsSquare ν → c ^ (2 : ℕ) ≠ ν) ∧ ∀ {F : Type u_2} [Field F] [Fintype F], Fintype.card F % (4 : ℕ) ≠ (3 : ℕ) → ∀ (c : F), IsSquare (-c ^ (2 : ℕ)) :=
  @FRC.LedgerML.p03006
/-- 3:B3 (p03007) — Square-class absorption: if $a_{i}/a_{0}\in S$ for all $i$ then $Q\simeq a_{0}\sum Y_{i}^{2}$ by $Y_{i}=w_{i}X_{i}$, $w_{i}^{2}=a_{i}/a_{0}$; no root of $a_{0}$ is needed, and none exists for $a_{0}\in N$ ($-a_{0}$ is a nonsquare with it). -/
theorem p03007 : ∀ {F : Type u_1} [Field F] (a0 a1 a2 a3 w1 w2 w3 x0 x1 x2 x3 : F), w1 ^ (2 : ℕ) * a0 = a1 → w2 ^ (2 : ℕ) * a0 = a2 → w3 ^ (2 : ℕ) * a0 = a3 → a0 * x0 ^ (2 : ℕ) + a1 * x1 ^ (2 : ℕ) + a2 * x2 ^ (2 : ℕ) + a3 * x3 ^ (2 : ℕ) = a0 * (x0 ^ (2 : ℕ) + (w1 * x1) ^ (2 : ℕ) + (w2 * x2) ^ (2 : ℕ) + (w3 * x3) ^ (2 : ℕ)) :=
  @FRC.LedgerML.p03007
/-- 3:B5 (p03009) — The Witt decomposition: for $\nu\in N$ the plane $x^{2}-\nu t^{2}$ (the norm of $\Fpq$) is anisotropic and $y^{2}+z^{2}=(y+iz)(y-iz)$ hyperbolic, so $Q_{\nu}=H\perp\langle1,-\nu\rangle$, index one; for $\nu=w^{2}$ the $(t,x)$-plane is hyperbolic too, $H\perp H$. Over $\Fpq$, $\nu=c^{2}$ and $Q_{\nu}\simeq\sum X_{i}^{2}$: hyperbolic ($16\,225$ zeros at $q=25$); the extension dissolves the split. -/
theorem p03009 : ∀ {F : Type u_1} [Field F] (ν t x : F), ¬IsSquare ν → x ^ (2 : ℕ) = ν * t ^ (2 : ℕ) → t = (0 : F) ∧ x = (0 : F) :=
  @FRC.LedgerML.p03009
/-- 3:C2 (p03013) — $\Lambda(\gamma,b)$ preserves $-\nu t^{2}+x^{2}$ exactly and $\Lambda(z_{1})\Lambda(z_{2})=\Lambda(z_{1}z_{2})$: the boosts are the norm-one cycle $N^{1}\simeq C_{\p+1}$, the non-split torus, and exhaust $SO(Q_{\nu},\Fp)$ in dimension $1{+}1$ ($6$, $14$, $18$ at $5$, $13$, $17$); with $\nu\in S$ the same construction is the split torus $C_{\p-1}$ --- the two tori are the two signatures (00:C3). -/
theorem p03013 : (∀ {F : Type u_1} [Field F] (ν γ b t x : F), γ ^ (2 : ℕ) - ν * b ^ (2 : ℕ) = (1 : F) → (γ * x + ν * b * t) ^ (2 : ℕ) - ν * (γ * t + b * x) ^ (2 : ℕ) = x ^ (2 : ℕ) - ν * t ^ (2 : ℕ)) ∧ (∀ {F : Type u_2} [Field F] (ν γ1 b1 γ2 b2 : F), !![γ1, b1; ν * b1, γ1] * !![γ2, b2; ν * b2, γ2] = !![γ1 * γ2 + ν * (b1 * b2), γ1 * b2 + b1 * γ2; ν * (γ1 * b2 + b1 * γ2), γ1 * γ2 + ν * (b1 * b2)]) ∧ ∀ {F : Type u_3} [Field F] (ν γ b : F), γ ^ (2 : ℕ) - ν * b ^ (2 : ℕ) = (1 : F) → !![γ, b; ν * b, γ].transpose * !![-ν, (0 : F); (0 : F), (1 : F)] * !![γ, b; ν * b, γ] = !![-ν, (0 : F); (0 : F), (1 : F)] :=
  @FRC.LedgerML.p03013
/-- 3:C3 (p03014) — Velocity: $\gamma\neq0$ on every boost; $v=-\nu b/\gamma\in\Fp$; $\gamma^{2}(\nu-v^{2})=\nu$, the finite $\gamma=1/\sqrt{1-\beta^{2}}$ with $\beta^{2}=v^{2}/\nu$ ($\beta$ itself is no shell quantity, 8:B8); Einstein's law $v_{12}=(v_{1}+v_{2})/(1+v_{1}v_{2}/\nu)$ exact, the denominator never zero; $v$ is two-to-one on $N^{1}$. -/
theorem p03014 : (∀ {F : Type u_1} [Field F] [Fintype F], Fintype.card F % (4 : ℕ) ≠ (3 : ℕ) → ∀ (ν γ b : F), ¬IsSquare ν → γ ^ (2 : ℕ) - ν * b ^ (2 : ℕ) = (1 : F) → γ ≠ (0 : F)) ∧ (∀ {F : Type u_2} [Field F] (ν γ b v : F), γ ^ (2 : ℕ) - ν * b ^ (2 : ℕ) = (1 : F) → v * γ = -(ν * b) → γ ^ (2 : ℕ) * (ν - v ^ (2 : ℕ)) = ν) ∧ ∀ {F : Type u_3} [Field F] (ν γ1 b1 γ2 b2 v1 v2 v12 : F), γ1 * γ2 ≠ (0 : F) → v1 * γ1 = -(ν * b1) → v2 * γ2 = -(ν * b2) → v12 * (γ1 * γ2 + ν * (b1 * b2)) = -(ν * (γ1 * b2 + b1 * γ2)) → v12 * (ν + v1 * v2) = ν * (v1 + v2) :=
  @FRC.LedgerML.p03014
-- end ledger predicates

end FRC.Causality

-- Ledger predicates: axioms (each predicate's, computed here)
#print axioms FRC.Causality.p03006
#print axioms FRC.Causality.p03007
#print axioms FRC.Causality.p03009
#print axioms FRC.Causality.p03013
#print axioms FRC.Causality.p03014
