import Mathlib
/-! Generated by `lean/make_web.py` from `FrcLedger/Causality.lean` with `FrcLedger/Fourier` inlined — one self-contained file for the Lean web editor. Edit the modules, not this file. -/

/-! inlined: FrcLedger/Fourier.lean (verbatim, minus its import lines) -/

/-!
# 6-fourier — the shell Fourier operator: rows B5/B7 for every shell (2026-09-15)

The shell Fourier matrix `W k j = g^(jk)` on `V = 𝔽_p^{Z_{p−1}}`, `g` a primitive root,
the reversal `J`, and the normalised operator `F = i W` with `i = −g^κ` (`i² = −1`).
Claims (6-fourier rows B5, B7; master C2 transform layer):
  `W² = −J`, `F² = J`, `F⁴ = I`, `W J = J W`.
The paper's witness checks these on six shells; here they are proved for every prime `p`
with `p = 4κ + 1` and every primitive root `g`.
-/

namespace FRC.Fourier

open Matrix Finset

variable {K : Type*} [Field K] {n : ℕ} [NeZero n]

/-- The geometric sum of an `n`-th root of unity `ζ ≠ 1` over `Fin n` vanishes. -/
lemma sum_pow_eq_zero_of_ne_one {ζ : K} (hζn : ζ ^ n = 1) (hζ : ζ ≠ 1) :
    ∑ j : Fin n, ζ ^ (j : ℕ) = 0 := by
  have h := geom_sum_mul ζ n
  rw [hζn, sub_self] at h
  rw [Fin.sum_univ_eq_sum_range (fun j => ζ ^ j) n]
  exact (mul_eq_zero.1 h).resolve_right (sub_ne_zero.2 hζ)

/-- The shell Fourier matrix, `W k j = g^(j·k)`. -/
def W (g : K) : Matrix (Fin n) (Fin n) K := fun k j => g ^ ((j : ℕ) * (k : ℕ))

/-- The reversal `J k l = [l = −k]`. -/
def J : Matrix (Fin n) (Fin n) K := fun k l => if l = -k then 1 else 0

lemma W_apply (g : K) (k j : Fin n) : (W g : Matrix (Fin n) (Fin n) K) k j = g ^ ((j : ℕ) * (k : ℕ)) := rfl
lemma J_apply (k l : Fin n) : (J : Matrix (Fin n) (Fin n) K) k l = if l = -k then 1 else 0 := rfl

/-- `g^((-j).val) = (g^(j.val))⁻¹` for an `n`-th root of unity `g`. -/
lemma pow_neg_val {g : K} (hg : g ^ n = 1) (j : Fin n) :
    g ^ ((-j : Fin n) : ℕ) = (g ^ (j : ℕ))⁻¹ := by
  have hne : g ≠ 0 := by rintro rfl; simp [NeZero.ne n] at hg
  apply eq_inv_of_mul_eq_one_left
  rw [← pow_add]
  have hdvd : n ∣ ((-j : Fin n) : ℕ) + (j : ℕ) := by
    have h : (-j : Fin n) + j = 0 := neg_add_cancel j
    have := congrArg Fin.val h
    rw [Fin.val_add, Fin.val_zero] at this
    exact Nat.dvd_of_mod_eq_zero this
  obtain ⟨c, hc⟩ := hdvd
  rw [hc, pow_mul, hg, one_pow]

/-- `J² = 1`. -/
theorem J_sq : (J : Matrix (Fin n) (Fin n) K) ^ 2 = 1 := by
  ext k l
  rw [sq, Matrix.mul_apply, Matrix.one_apply]
  simp only [J_apply, mul_ite, mul_one, mul_zero]
  rw [Finset.sum_eq_single (-k)]
  · simp [neg_neg, eq_comm]
  · intro x _ hx; simp [hx]
  · intro h; exact absurd (Finset.mem_univ _) h

/-- `W² = n • J` for any primitive `n`-th root of unity `g` (the general identity). -/
theorem W_sq (g : K) (hg : IsPrimitiveRoot g n) :
    (W g : Matrix (Fin n) (Fin n) K) ^ 2 = (n : K) • J := by
  ext k l
  rw [sq, Matrix.mul_apply, Matrix.smul_apply, J_apply]
  simp only [W_apply]
  have hrw : ∀ j : Fin n, g ^ ((j : ℕ) * (k : ℕ)) * g ^ ((l : ℕ) * (j : ℕ))
      = (g ^ ((k : ℕ) + (l : ℕ))) ^ (j : ℕ) := by
    intro j; rw [← pow_add, ← pow_mul]; congr 1; ring
  simp_rw [hrw]
  have hdvd_iff : n ∣ (k : ℕ) + (l : ℕ) ↔ l = -k := by
    constructor
    · intro hd
      rw [eq_neg_iff_add_eq_zero, add_comm]
      apply Fin.ext
      rw [Fin.val_add, Fin.val_zero]
      exact Nat.mod_eq_zero_of_dvd hd
    · intro hl
      have h : k + l = 0 := by rw [hl, add_neg_cancel]
      have := congrArg Fin.val h
      rw [Fin.val_add, Fin.val_zero] at this
      exact Nat.dvd_of_mod_eq_zero this
  by_cases hkl : l = -k
  · obtain ⟨c, hc⟩ := hdvd_iff.2 hkl
    rw [hc, pow_mul, hg.pow_eq_one, one_pow]
    simp [hkl]
  · have hne : g ^ ((k : ℕ) + (l : ℕ)) ≠ 1 := by
      intro h1
      exact hkl (hdvd_iff.1 (hg.dvd_of_pow_eq_one _ h1))
    have hpow : (g ^ ((k : ℕ) + (l : ℕ))) ^ n = 1 := by
      rw [← pow_mul, mul_comm, pow_mul, hg.pow_eq_one, one_pow]
    rw [sum_pow_eq_zero_of_ne_one hpow hne]
    simp [hkl]

/-- `W J = J W` for any `n`-th root of unity `g`. -/
theorem W_mul_J_comm (g : K) (hg : g ^ n = 1) :
    (W g : Matrix (Fin n) (Fin n) K) * J = J * W g := by
  ext k l
  rw [Matrix.mul_apply, Matrix.mul_apply]
  simp only [W_apply, J_apply, mul_ite, ite_mul, mul_one, mul_zero, one_mul, zero_mul]
  rw [Finset.sum_eq_single (-l), Finset.sum_eq_single (-k)]
  · simp only [neg_neg, ite_true]
    -- g^((-l)·k) = g^(l·(-k))
    have hl : (g ^ (l : ℕ)) ^ n = 1 := by rw [← pow_mul, mul_comm, pow_mul, hg, one_pow]
    rw [pow_mul, pow_mul, pow_neg_val hg l, inv_pow, pow_neg_val hl k]
  · intro x _ hx; simp [hx]
  · intro h; exact absurd (Finset.mem_univ _) h
  · intro x _ hx
    have : l ≠ -x := fun h => hx (by rw [h, neg_neg])
    simp [this]
  · intro h; exact absurd (Finset.mem_univ _) h

/-! ## The shell: a field with `p = 4κ + 1` elements, `g` a primitive root, `i = −g^κ` -/

section shell

variable {F : Type*} [Field F] [Fintype F]

/-- `(card F − 1 : ℕ) = −1` in a finite field `F`. -/
lemma natCast_card_pred_eq_neg_one : ((Fintype.card F - 1 : ℕ) : F) = -1 := by
  have h2 : 1 ≤ Fintype.card F := Fintype.card_pos
  rw [Nat.cast_sub h2, FiniteField.cast_card_eq_zero, Nat.cast_one, zero_sub]

/-- The quarter-turn `i = −g^κ` squares to `−1` (`g^{2κ}` is a primitive square root of unity). -/
lemma quarter_turn_sq (κ : ℕ) (hκ : Fintype.card F = 4 * κ + 1) (g : F)
    (hg : IsPrimitiveRoot g (Fintype.card F - 1)) :
    (-(g ^ κ)) ^ 2 = -1 := by
  have hκ' : Fintype.card F - 1 = 4 * κ := by omega
  have hκpos : κ ≠ 0 := by
    intro h; subst h; have := Fintype.one_lt_card (α := F); omega
  have hsq : (-(g ^ κ)) ^ 2 = g ^ (2 * κ) := by ring
  rw [hsq]
  have h2 : IsPrimitiveRoot (g ^ (2 * κ)) 2 := by
    have hd : 2 * κ ∣ Fintype.card F - 1 := by rw [hκ']; exact ⟨2, by ring⟩
    have := hg.pow_of_dvd (show 2 * κ ≠ 0 by omega) hd
    have hq : (Fintype.card F - 1) / (2 * κ) = 2 := by
      rw [hκ', show 4 * κ = 2 * κ * 2 by ring]; exact Nat.mul_div_cancel_left _ (by omega)
    rwa [hq] at this
  exact h2.eq_neg_one_of_two_right

/-- 6:B5, 6:B7 — every shell: on a field with `p = 4κ + 1` elements, `n = p − 1`,
`g` a primitive root and `F = i • W`: `W² = −J`, `F² = J`, `F⁴ = 1`, `W J = J W`. -/
theorem shell_relations (κ : ℕ) (hκ : Fintype.card F = 4 * κ + 1) (g : F)
    (hg : IsPrimitiveRoot g (Fintype.card F - 1)) :
    haveI : NeZero (Fintype.card F - 1) := ⟨by have := Fintype.one_lt_card (α := F); omega⟩
    (W g : Matrix (Fin (Fintype.card F - 1)) (Fin (Fintype.card F - 1)) F) ^ 2 = -J ∧
    ((-(g ^ κ)) • W g : Matrix (Fin (Fintype.card F - 1)) (Fin (Fintype.card F - 1)) F) ^ 2 = J ∧
    ((-(g ^ κ)) • W g : Matrix (Fin (Fintype.card F - 1)) (Fin (Fintype.card F - 1)) F) ^ 4 = 1 ∧
    (W g : Matrix (Fin (Fintype.card F - 1)) (Fin (Fintype.card F - 1)) F) * J = J * W g := by
  haveI : NeZero (Fintype.card F - 1) := ⟨by have := Fintype.one_lt_card (α := F); omega⟩
  have hW : (W g : Matrix (Fin (Fintype.card F - 1)) (Fin (Fintype.card F - 1)) F) ^ 2 = -J := by
    rw [W_sq g hg, natCast_card_pred_eq_neg_one, neg_one_smul]
  have hi := quarter_turn_sq κ hκ g hg
  have hF : ((-(g ^ κ)) • W g : Matrix (Fin (Fintype.card F - 1)) (Fin (Fintype.card F - 1)) F) ^ 2
      = J := by
    rw [smul_pow, hW, hi, neg_one_smul, neg_neg]
  refine ⟨hW, hF, ?_, W_mul_J_comm g hg.pow_eq_one⟩
  rw [show (4 : ℕ) = 2 * 2 by norm_num, pow_mul, hF, J_sq]

/-- 6:B5, 6:B7 on the prime shell `𝔽_p = ZMod p`, an instance: the relations hold there for every prime
`p = 4κ + 1` and primitive root `g`. -/
theorem shell_relations_zmod (p κ : ℕ) [hp : Fact (Nat.Prime p)] (hκ : p = 4 * κ + 1)
    (g : ZMod p) (hg : IsPrimitiveRoot g (p - 1)) :
    haveI : NeZero (Fintype.card (ZMod p) - 1) :=
      ⟨by have := Fintype.one_lt_card (α := ZMod p); omega⟩
    ((-(g ^ κ)) • W g : Matrix (Fin (Fintype.card (ZMod p) - 1))
      (Fin (Fintype.card (ZMod p) - 1)) (ZMod p)) ^ 2 = J := by
  have hc : Fintype.card (ZMod p) = p := ZMod.card p
  exact (shell_relations κ (by rw [hc, hκ]) g (by rw [hc]; exact hg)).2.1

end shell

end FRC.Fourier

/-! FrcLedger/Causality.lean -/

/-!
# 3-causality — the Euclidean–Lorentzian dichotomy, Mathlib witnesses

Rows of the predicate ledger of *Euclidean–Lorentzian Dichotomy and Algebraic Causality in Finite Ring Continuum*
(Entropy 2025, 27, 1098; tree `3-causality-20260510`), over an arbitrary finite
field `F` with `card F ≢ 3 (mod 4)` (so `−1` is a square, the shells `p = 4κ + 1` among them).  Classical
(tier 2) on Mathlib's hierarchy; the same rows are proved with no axioms in `FrcCore/Causality.lean`.
-/

namespace FRC.Causality

variable {F : Type*} [Field F]

/-- 3:B2 (Thm. nonexistence, first clause): `c² = ν` makes `ν` a square, so a nonsquare `ν` has no root. -/
theorem no_causal_root (ν c : F) (h : ¬IsSquare ν) : c ^ 2 ≠ ν := fun e => h ⟨c, by rw [← e, sq]⟩

/-- 3:B2 (the consequence): when `−1` is a square (`card F ≢ 3 mod 4`) so is `−c²`, and every coefficient of
`−c² t² + x² + y² + z²` lies in the class of squares — a Euclidean form for every `c ≠ 0`. -/
theorem neg_sq_is_square [Fintype F] (hF : Fintype.card F % 4 ≠ 3) (c : F) : IsSquare (-(c ^ 2)) := by
  obtain ⟨i, hi⟩ := FiniteField.isSquare_neg_one_iff.mpr hF
  exact ⟨i * c, by rw [show -(c ^ 2) = (-1) * c ^ 2 by ring, hi]; ring⟩

/-- 3:B3 (Lemma absorption): coefficients `a_i = w_i² a_0` are absorbed by `x_i ↦ w_i x_i`. -/
theorem absorb (a0 a1 a2 a3 w1 w2 w3 x0 x1 x2 x3 : F) (h1 : w1 ^ 2 * a0 = a1) (h2 : w2 ^ 2 * a0 = a2)
    (h3 : w3 ^ 2 * a0 = a3) :
    a0 * x0 ^ 2 + a1 * x1 ^ 2 + a2 * x2 ^ 2 + a3 * x3 ^ 2 =
    a0 * (x0 ^ 2 + (w1 * x1) ^ 2 + (w2 * x2) ^ 2 + (w3 * x3) ^ 2) := by
  rw [← h1, ← h2, ← h3]; ring

/-- 3:B5: `x² − ν t²` is anisotropic for a nonsquare `ν`. -/
theorem aniso_tx (ν t x : F) (hν : ¬IsSquare ν) (e : x ^ 2 = ν * t ^ 2) : t = 0 ∧ x = 0 := by
  by_cases ht : t = 0
  · subst ht; simp at e; exact ⟨rfl, e⟩
  · exact absurd ⟨x / t, by field_simp; linear_combination (-1 : F) * e⟩ hν

/-- 3:C2 (the finite Lorentz boost): `Λ(γ, b) = !![γ, b; νb, γ]` with `γ² − νb² = 1` preserves `x² − ν t²`. -/
theorem boost_preserves (ν γ b t x : F) (h : γ ^ 2 - ν * b ^ 2 = 1) :
    (γ * x + ν * b * t) ^ 2 - ν * (γ * t + b * x) ^ 2 = x ^ 2 - ν * t ^ 2 := by
  linear_combination (x ^ 2 - ν * t ^ 2) * h

/-- 3:C2: the boosts compose as the norm-one elements of `F(√ν)` multiply. -/
theorem boost_comp (ν γ1 b1 γ2 b2 : F) :
    !![γ1, b1; ν * b1, γ1] * !![γ2, b2; ν * b2, γ2] =
    !![γ1 * γ2 + ν * (b1 * b2), γ1 * b2 + b1 * γ2; ν * (γ1 * b2 + b1 * γ2), γ1 * γ2 + ν * (b1 * b2)] := by
  ext i j; fin_cases i <;> fin_cases j <;> simp [Matrix.mul_apply, Fin.sum_univ_two] <;> ring

/-- 3:C2: `Λ(γ, b)` is orthogonal for the Gram matrix `diag(−ν, 1)` of `Q_ν`: `Λᵀ G Λ = G`. -/
theorem boost_orthogonal (ν γ b : F) (h : γ ^ 2 - ν * b ^ 2 = 1) :
    (!![γ, b; ν * b, γ]).transpose * !![-ν, 0; 0, 1] * !![γ, b; ν * b, γ] = !![-ν, 0; 0, 1] := by
  ext i j; fin_cases i <;> fin_cases j <;> simp [Matrix.mul_apply, Fin.sum_univ_two] <;>
    first | ring1 | linear_combination (-ν) * h | linear_combination h

/-- 3:C3: `γ ≠ 0` on every boost of the Lorentzian plane (`γ = 0` would make `ν = (i/b)²`). -/
theorem gamma_ne_zero [Fintype F] (hF : Fintype.card F % 4 ≠ 3) (ν γ b : F) (hν : ¬IsSquare ν)
    (h : γ ^ 2 - ν * b ^ 2 = 1) : γ ≠ 0 := by
  rintro rfl
  obtain ⟨i, hi⟩ := FiniteField.isSquare_neg_one_iff.mpr hF
  have hb : b ≠ 0 := by rintro rfl; simp at h
  have hνb : ν * b ^ 2 = -1 := by linear_combination -h
  exact hν ⟨i / b, by field_simp; linear_combination hνb + hi⟩

/-- 3:C3: the velocity `v = −νb/γ` satisfies `γ² (ν − v²) = ν` — `γ = 1/√(1 − β²)` with `β² = v²/ν`. -/
theorem gamma_velocity (ν γ b v : F) (h : γ ^ 2 - ν * b ^ 2 = 1) (hv : v * γ = -(ν * b)) :
    γ ^ 2 * (ν - v ^ 2) = ν := by
  linear_combination ν * h - (v * γ - ν * b) * hv

/-- 3:C3 (Einstein's addition law, exact): `v₁₂ (ν + v₁v₂) = ν (v₁ + v₂)`. -/
theorem velocity_addition (ν γ1 b1 γ2 b2 v1 v2 v12 : F) (hγ : γ1 * γ2 ≠ 0)
    (hv1 : v1 * γ1 = -(ν * b1)) (hv2 : v2 * γ2 = -(ν * b2))
    (hv12 : v12 * (γ1 * γ2 + ν * (b1 * b2)) = -(ν * (γ1 * b2 + b1 * γ2))) :
    v12 * (ν + v1 * v2) = ν * (v1 + v2) := by
  have : γ1 * γ2 * (v12 * (ν + v1 * v2) - ν * (v1 + v2)) = 0 := by
    linear_combination ν * hv12 + (-v12 * ν * b2 - ν * γ2 + v12 * (v2 * γ2 + ν * b2)) * hv1 +
      (-v12 * ν * b1 - ν * γ1) * hv2
  rcases mul_eq_zero.mp this with h | h
  · exact absurd h hγ
  · exact sub_eq_zero.mp h

end FRC.Causality
