import Mathlib
/-! Generated by `lean/make_web.py` from `FrcLedger/Godel.lean` with `FrcLedger/Reductio` inlined — one self-contained file for the Lean web editor. Edit the modules, not this file. -/

/-! inlined: FrcLedger/Reductio.lean (verbatim, minus its import lines) -/

/-!
# 5-red — paradoxes of infinity as reductio: the ledger predicates in Lean (2026-09-17)

Rows of the predicate ledger of *Paradoxes of Infinity as Reductio ad Absurdum* (tree `5-reductio-20260706`).
The finite exit's properties for any finite structure in any language (the complete theory is complete, and
truth is decided by evaluation); the infinitude of every structure with an injective successor missing zero
(no finite frame interprets `Q`); Cantor's theorem; the counting of the migration propositions and the vanishing
certified fraction; definable and periodic choice; the equivariant section criterion on an orbit; the
obstruction on `𝔽₅`; the finite disappearance of the choice paradoxes; Dedekind's embedding.  Classical (tier 2)
on Mathlib's hierarchy; the finite content is proved with no axioms in `FrcCore/Reductio.lean`.
-/

open FirstOrder FirstOrder.Language

namespace FRC.Reductio

section frames

variable {L : Language} {M : Type*} [L.Structure M]

/-- 5:B5, 5:B3 (Proposition frame-complete, completeness): the theory of any structure — a finite frame `W_N` among
them — is complete: every sentence or its negation is in it. -/
theorem theory_complete [Nonempty M] : (L.completeTheory M).IsComplete := completeTheory.isComplete L M

/-- 5:B5 (decidability): in a finite structure with decidable relations, the truth of every bounded formula is
decided by evaluation — the quantifiers range over the finitely many elements. -/
def decRealize {α : Type*} [Fintype M] [DecidableEq M]
    (hR : ∀ (n : ℕ) (R : L.Relations n) (x : Fin n → M), Decidable (Structure.RelMap R x)) :
    ∀ {n : ℕ} (φ : L.BoundedFormula α n) (v : α → M) (xs : Fin n → M), Decidable (φ.Realize v xs)
  | _, .falsum, _, _ => isFalse id
  | _, .equal t₁ t₂, v, xs =>
    decidable_of_iff (t₁.realize (Sum.elim v xs) = t₂.realize (Sum.elim v xs)) Iff.rfl
  | _, .rel R ts, v, xs =>
    haveI := hR _ R fun i => (ts i).realize (Sum.elim v xs)
    decidable_of_iff (Structure.RelMap R fun i => (ts i).realize (Sum.elim v xs)) Iff.rfl
  | _, .imp f₁ f₂, v, xs =>
    haveI := decRealize hR f₁ v xs
    haveI := decRealize hR f₂ v xs
    decidable_of_iff (f₁.Realize v xs → f₂.Realize v xs) Iff.rfl
  | _, .all f, v, xs =>
    haveI : ∀ x : M, Decidable (f.Realize v (Fin.snoc xs x)) := fun x => decRealize hR f v (Fin.snoc xs x)
    decidable_of_iff (∀ x : M, f.Realize v (Fin.snoc xs x)) Iff.rfl

/-- 5:B5 (Proposition frame-complete, decidability): membership in the theory of a finite structure is decided
by evaluating the sentence. -/
@[instance_reducible] def decTheory [Fintype M] [DecidableEq M]
    (hR : ∀ (n : ℕ) (R : L.Relations n) (x : Fin n → M), Decidable (Structure.RelMap R x)) :
    DecidablePred (· ∈ L.completeTheory M) := fun φ =>
  haveI := decRealize hR (α := Empty) φ default default
  decidable_of_iff (BoundedFormula.Realize φ default default) Iff.rfl

/-- 5:B3 (Theorem witnessed, exit 2 — `Th(W_N)` does not interpret `Q`): a structure with an injective
successor that never reaches zero is infinite; every model of `Q` is such a structure, and a finite frame's
definable quotients are finite. -/
theorem infinite_of_succ {A : Type*} (S : A → A) (z : A) (hinj : Function.Injective S) (hz : ∀ x, S x ≠ z) :
    Infinite A := by
  by_contra hfin
  have : Finite A := not_infinite_iff_finite.mp hfin
  obtain ⟨x, hx⟩ := Finite.injective_iff_surjective.mp hinj z
  exact hz x hx

end frames

section diagonal

/-- 5:D3 (Remark cantor-diagonal): Cantor's theorem is an external diagonal — no map from a set onto its power
set, in every finite frame as `n < 2^n`. -/
theorem cantor (α : Type*) (f : α → Set α) : ¬ Function.Surjective f := Function.cantor_surjective f

/-- 5:D3: on the frame, `n < 2^n`. -/
theorem cantor_finite (n : ℕ) : n < 2 ^ n := Nat.lt_two_pow_self

end diagonal

section migration

/-- 5:C2 (Proposition mirror, the count): fewer than `s^(K+1)` strings of length at most `K` exist over an
alphabet of `s ≥ 2` letters. -/
theorem records_lt (s K : ℕ) (hs : 2 ≤ s) : ∑ i ∈ Finset.range (K + 1), s ^ i < s ^ (K + 1) :=
  Nat.geomSum_lt hs fun _ hk => Finset.mem_range.mp hk

/-- 5:C2 (Proposition mirror): a part with fewer distinguishable records than the frame has elements admits no
injective representation of the frame's domain. -/
theorem no_mirror {A R : Type*} [Fintype A] [Fintype R] (h : Fintype.card R < Fintype.card A) (f : A → R) :
    ¬ Function.Injective f := fun hf => absurd (Fintype.card_le_of_injective f hf) (not_le.mpr h)

open Filter Topology in
/-- 5:C3 (Proposition fraction): the certified fraction `s^(K+1) / ⌊c^L/2⌋` of a bounded agent tends to zero as
the cohort length `L` grows, for any capacity and any `c > 1`. -/
theorem certified_fraction_tendsto (A c : ℝ) (hc : 1 < c) :
    Tendsto (fun L : ℕ => A / c ^ L) atTop (𝓝 0) :=
  tendsto_const_nhds.div_atTop (tendsto_pow_atTop_atTop_of_one_lt hc)

end migration

section choice

variable {U : Type*} [LinearOrder U]

/-- 5:E1 (Proposition finite-choice): on a finite universe with a canonical order, `ch(A) = min A` is a member of
every nonempty `A` — choice is a definable theorem, not a postulate. -/
theorem finite_choice (A : Finset U) (hA : A.Nonempty) : A.min' hA ∈ A := Finset.min'_mem A hA

/-- 5:E2 (Lemma periodic-equality): for an equality-periodic family `A (i + N) = A i` the choice `min A i` is
periodic with the same period. -/
theorem periodic_choice (A : ℤ → Finset U) (N : ℤ) (hN : ∀ i, A (i + N) = A i) (i : ℤ) :
    (A (i + N)).min = (A i).min := by rw [hN]

variable {G I A : Type*} [Group G] [MulAction G I] [MulAction G A]

/-- 5:E3 (Theorem equivariant-choice, one orbit): for a `G`-family `π : A → I` over a transitive `G`-set `I`, an
equivariant section exists iff the stabiliser of a base point `i₀` fixes some point of its fibre. -/
theorem equivariant_section_iff [MulAction.IsPretransitive G I] (π : A → I)
    (hπ : ∀ (g : G) (a : A), π (g • a) = g • π a) (i₀ : I) :
    (∃ s : I → A, (∀ i, π (s i) = i) ∧ ∀ (g : G) (i : I), s (g • i) = g • s i) ↔
      ∃ a, π a = i₀ ∧ ∀ g ∈ MulAction.stabilizer G i₀, g • a = a := by
  constructor
  · rintro ⟨s, hs, heq⟩
    refine ⟨s i₀, hs i₀, fun g hg => ?_⟩
    rw [← heq, MulAction.mem_stabilizer_iff.mp hg]
  · rintro ⟨a, ha, hfix⟩
    classical
    choose g hg using fun i => MulAction.exists_smul_eq G i₀ i
    -- `s i := g i • a`, where `g i • i₀ = i`; independence of the choice is the stabiliser condition
    have key : ∀ (h : G) (i : I), h • i₀ = i → h • a = g i • a := by
      intro h i hi
      have hst : (g i)⁻¹ * h ∈ MulAction.stabilizer G i₀ := by
        rw [MulAction.mem_stabilizer_iff, mul_smul, hi]
        have e := inv_smul_smul (g i) i₀
        rw [hg i] at e
        exact e
      have := hfix _ hst
      rw [mul_smul] at this
      calc h • a = g i • (g i)⁻¹ • h • a := (smul_inv_smul _ _).symm
        _ = g i • a := by rw [this]
    refine ⟨fun i => g i • a, fun i => ?_, fun h i => ?_⟩
    · rw [hπ, ha, hg]
    · show g (h • i) • a = h • (g i • a)
      rw [← mul_smul]
      exact (key (h * g i) (h • i) (by rw [mul_smul, hg])).symm

/-- 5:E4 (Example basis-obstruction): on the line over `𝔽₅` the involution `v ↦ −v` fixes no basis — `−v ≠ v`
for every `v ≠ 0` — while over `𝔽₂` it fixes `1`: the obstruction is arithmetic. -/
theorem obstruction_five : (∀ v : ZMod 5, v ≠ 0 → -v ≠ v) ∧ (-(1 : ZMod 2) = 1) := by decide

/-- 5:E8 (Banach–Tarski disappears): a finite nonempty set cannot be doubled — there is no injection
`X ⊕ X ↪ X`, so no decomposition reassembles two copies of `X` from pieces of `X`. -/
theorem no_doubling {X : Type*} [Fintype X] [Nonempty X] : IsEmpty (X ⊕ X ↪ X) := by
  constructor
  intro f
  have h := Fintype.card_le_of_embedding f
  rw [Fintype.card_sum] at h
  have : 0 < Fintype.card X := Fintype.card_pos
  omega

/-- 5:E8 (ultrafilters): on a finite set every ultrafilter is principal. -/
theorem ultrafilter_principal {X : Type*} [Finite X] (f : Ultrafilter X) : ∃ a, f = pure a :=
  Ultrafilter.eq_pure_of_finite f

end choice

section determinacy

/-- 5:D8 (Proposition finiteness, the finite direction): over a finite domain a second-order quantifier over all
subsets is a finite conjunction — decided by exhaustive evaluation. -/
def decideAllSubsets {M : Type*} [Fintype M] [DecidableEq M] (P : Finset M → Prop) [DecidablePred P] :
    Decidable (∀ S : Finset M, P S) := Fintype.decidableForallFintype

/-- 5:D8 (the infinite direction, its first step): an infinite domain carries a copy of `ℕ` — Dedekind's
embedding, from which the reduction of true second-order arithmetic proceeds. -/
theorem nat_embeds {M : Type*} [Infinite M] : Nonempty (ℕ ↪ M) := ⟨Infinite.natEmbedding M⟩

end determinacy

-- Ledger predicates of 5-reductio (generated by make_predicates.py from docs/5-reductio/5-reductio-ledger.json; edit the ledger, not this section)
/-- 5:B3 (p05007) — Witnessed independence: every three-element subset is satisfiable --- $Q$ itself ($\neg$Cmp, consistent by finitary means, the superexponential cost exact); $\mathrm{Th}(W_N)$ ($\neg$IR: consistent, complete, decidable, singly axiomatised, interpreting no $Q$ since every model of $Q$ is infinite); the inconsistent extension ($\neg$Cns); true arithmetic ($\neg$Eff). Four legs, all load-bearing. -/
theorem p05007 : (∀ {A : Type u_1} (S : A → A) (z : A), Function.Injective S → (∀ (x : A), S x ≠ z) → Infinite A) ∧ ∀ {L : FirstOrder.Language} {M : Type u_4} [L.Structure M] [Nonempty M], (L.completeTheory M).IsComplete :=
  And.intro @FRC.Reductio.infinite_of_succ (@FRC.Reductio.theory_complete)
/-- 5:B5 (p05009) — Per-frame completeness: $\mathrm{Th}(W_N)$ is consistent, complete and decidable, axiomatised by the categorical sentence $\sigma_N$; truth in any finite structure is decided by evaluation, and the theory of any structure is complete. Cited definitions (not proofs): FRC.Reductio.decRealize, FRC.Reductio.decTheory. -/
theorem p05009 : ∀ {L : FirstOrder.Language} {M : Type u_3} [L.Structure M] [Nonempty M], (L.completeTheory M).IsComplete :=
  @FRC.Reductio.theory_complete
/-- 5:C2 (p05013) — No internal mirror: fewer than $s^{K+1}$ records exist, so an agent with $s^{K+1}<N$ holds no injective representation of the domain of $W_N$ --- a proper part cannot mirror the whole (pigeonhole). -/
theorem p05013 : (∀ (s K : ℕ), (2 : ℕ) ≤ s → ∑ i ∈ Finset.range (K + (1 : ℕ)), s ^ i < s ^ (K + (1 : ℕ))) ∧ ∀ {A : Type u_1} {R : Type u_2} [Fintype A] [Fintype R], Fintype.card R < Fintype.card A → ∀ (f : A → R), ¬Function.Injective f :=
  And.intro @FRC.Reductio.records_lt (@FRC.Reductio.no_mirror)
/-- 5:C3 (p05014) — Vanishing certified fraction: at least $c^{L}$ normal-form sentences of length $\le L$, half of each cohort frame truths by completeness, fewer than $s^{K+1}$ certified, so the certified fraction is at most $s^{K+1}/\lfloor c^{L}/2\rfloor\to0$. -/
theorem p05014 : ∀ (A c : ℝ), (1 : ℝ) < c → Filter.Tendsto (fun L => A / c ^ L) Filter.atTop (nhds (0 : ℝ)) :=
  @FRC.Reductio.certified_fraction_tendsto
/-- 5:D3 (p05019) — Diagonal normal form: $\{$Eff, Cns, Cmp, IR$\}$ inconsistent (B2), Tarski a variant with the truth predicate for Cmp; the diagonal is a theorem when external --- Cantor's theorem, $n<2^{n}$ on every frame, uncountability, halting --- and a paradox engine only over an internalised registry with completeness demanded. -/
theorem p05019 : (∀ (α : Type u_1) (f : α → Set α), ¬Function.Surjective f) ∧ ∀ (n : ℕ), n < (2 : ℕ) ^ n :=
  And.intro @FRC.Reductio.cantor (@FRC.Reductio.cantor_finite)
/-- 5:D8 (p05024) — Finiteness of determinate totalities: in ZF with every infinite set Dedekind-infinite, a structure satisfies Det iff it is finite --- finite: the full higher-order theory decided by exhaustive evaluation; infinite: a copy of $\N$ inside gives an effective reduction of true second-order arithmetic, which is not arithmetical. The real field's first-order tameness is silence about its subsets. Cited definitions (not proofs): FRC.Reductio.decideAllSubsets. -/
theorem p05024 : ∀ {M : Type u_1} [Infinite M], Nonempty (ℕ ↪ M) :=
  @FRC.Reductio.nat_embeds
/-- 5:E1 (p05027) — Global choice on a finite universe: with a canonical order, $\operatorname{ch}(A)=\min A$ is a uniform pointwise choice rule; over a fixed finite base AC is a definable theorem; finite products are nonempty without it. -/
theorem p05027 : ∀ {U : Type u_1} [LinearOrder U] (A : Finset U) (hA : A.Nonempty), A.min' hA ∈ A :=
  @FRC.Reductio.finite_choice
/-- 5:E2 (p05028) — Periodic choice: an equality-periodic family $A_{i+N}=A_i$ has the choice $f(i)=\operatorname{ch}(A_i)$ of the same period; group-periodic families as equivariant surjections $\pi:A\to I$ with equivariant sections. -/
theorem p05028 : ∀ {U : Type u_1} [LinearOrder U] (A : ℤ → Finset U) (N : ℤ), (∀ (i : ℤ), A (i + N) = A i) → ∀ (i : ℤ), (A (i + N)).min = (A i).min :=
  @FRC.Reductio.periodic_choice
set_option linter.defProp false in
/-- 5:E3 (p05029) — Equivariant periodic choice: a $G$-equivariant section exists iff each stabiliser action $G_i\curvearrowright A_i$ has a fixed point (one orbit at a time); the Fraenkel--Mostowski mechanism in positive form. -/
def p05029 := @FRC.Reductio.equivariant_section_iff
/-- 5:E4 (p05030) — The definable basis: every subspace of a finite vector space has the greedy $\min$-basis, one definable function on all subspaces; the equivariant obstruction --- $\Z/2$ acting by $v\mapsto-v$ on the line over $\F_5$ fixes no basis ($-v\neq v$), over $\F_2$ it does: arithmetic, not formal. -/
theorem p05030 : (∀ (v : ZMod (5 : ℕ)), v ≠ (0 : ZMod (5 : ℕ)) → -v ≠ v) ∧ (-1 : ZMod (2 : ℕ)) = (1 : ZMod (2 : ℕ)) :=
  @FRC.Reductio.obstruction_five
/-- 5:E8 (p05034) — The choice paradoxes vanish: on a finite set counting measure is complete and invariant, no decomposition doubles the set ($X\sqcup X$ does not inject into $X$), and every ultrafilter is principal; periodic variants inherit this on one period. -/
theorem p05034 : (∀ {X : Type u_1} [Fintype X] [Nonempty X], IsEmpty (X ⊕ X ↪ X)) ∧ ∀ {X : Type u_2} [Finite X] (f : Ultrafilter X), ∃ a, f = pure a :=
  And.intro @FRC.Reductio.no_doubling (@FRC.Reductio.ultrafilter_principal)
-- end ledger predicates

end FRC.Reductio

/-! FrcLedger/Godel.lean -/

/-!
# 25-göd — incompleteness without infinity: the ledger predicates on Mathlib

Predicates of the ledger of *Incompleteness Without Infinity* (tree `25-godel-20260614`) stated on Mathlib's
hierarchy.

* 25:C1 — a carrier with an injective successor that omits an element is not finite, so every model of `Q` is
  infinite.
* 25:C2 — the theory of a structure is complete, and a finite structure decides each sentence.
* 25:C5 — among `m + 1` sentences of a first-order language two receive the same number in a structure of `m`
  elements.
* 25:D1, 25:D3 — an agent with fewer storage states than the structure has elements has no injective encoding.
  Some reading stands for at least `⌈m / a^K⌉ ≥ 2` elements. Every element outside a maximal faithfully read
  range is an alias of one inside it.
* 25:E1 — the binary trees with `n + 1` inner nodes number at least `2^n`, and the equations between two of them
  at least `2^ℓ` from `ℓ = 6` leaves on.
* 25:E2 — the records of length at most `B` number fewer than `a^(B+1)`.
* 25:F4 — an injective coding of strings into tuples needs `a^n ≤ m^k`.
* 25:H2 — over a finite domain a second-order quantifier ranges over `2^(m^k)` relations.

The axioms of each declaration are in `lean/axioms.log`.
-/

open FirstOrder FirstOrder.Language

namespace FRC.Godel

/-! ### 25:C1, 25:C2, 25:C5 — Gödel's hypotheses over a finite structure -/

section vacuity

/-- 25:C1 (Proposition noQ, the finite form) — on a finite carrier an injective map is onto: no successor is
injective and omits an element. -/
theorem finite_succ_onto {A : Type*} [Finite A] (S : A → A) (hinj : Function.Injective S) (z : A) : ∃ x, S x = z :=
  Finite.surjective_of_injective hinj z

/-- 25:C1 (Proposition noQ) — every model of `Q` is infinite: a carrier with an injective successor `S` and an
element outside its range is not finite, so no finite structure interprets `Q`. -/
theorem infinite_of_succ {A : Type*} (S : A → A) (z : A) (hinj : Function.Injective S) (hz : ∀ x, S x ≠ z) :
    Infinite A :=
  not_finite_iff_infinite.mp (fun _ => (finite_succ_onto S hinj z).elim (fun x hx => hz x hx))

variable {L : Language} {M : Type*} [L.Structure M]

/-- 25:C2 (Proposition complete) — the theory of a structure is complete: satisfiable, and deciding every
sentence one way or the other. -/
theorem theory_complete [Nonempty M] : (L.completeTheory M).IsComplete := completeTheory.isComplete L M

/-- 25:C2 (Proposition complete, decidability) — in a finite structure with decidable relations, membership in
the theory is decided by evaluating the sentence, each quantifier ranging over the finitely many elements. -/
@[instance_reducible] def decTheory [Fintype M] [DecidableEq M]
    (hR : ∀ (n : ℕ) (R : L.Relations n) (x : Fin n → M), Decidable (Structure.RelMap R x)) :
    DecidablePred (· ∈ L.completeTheory M) := FRC.Reductio.decTheory hR

/-- The sentences `⊥, ¬⊥, ¬¬⊥, …`. -/
def nots (L : Language) : ℕ → L.Sentence
  | 0 => (⊥ : L.Sentence)
  | n + 1 => (nots L n).not

theorem nots_injective (L : Language) : Function.Injective (nots L) := by
  intro a
  induction a with
  | zero =>
    intro b h
    cases b with
    | zero => rfl
    | succ b => exact absurd h (by simp [nots, BoundedFormula.not])
  | succ a ih =>
    intro b h
    cases b with
    | zero => exact absurd h (by simp [nots, BoundedFormula.not])
    | succ b =>
      have h' : (nots L a).imp ⊥ = (nots L b).imp ⊥ := h
      rw [BoundedFormula.imp.injEq] at h'
      exact congrArg Nat.succ (ih h'.1)

omit [L.Structure M] in
/-- Remark Tarski scoped, the classical form (cited by no row; the row's finite form is `nots_collide`) — no
numbering of all the sentences of a first-order language into a finite structure is injective. -/
theorem no_goedel_numbering [Finite M] (f : L.Sentence → M) : ¬ Function.Injective f := fun hf =>
  haveI : Infinite L.Sentence := Infinite.of_injective (nots L) (nots_injective L)
  not_injective_infinite_finite f hf

end vacuity

/-- 25:C5 (Remark Tarski scoped, the row's finite form) — among the `m + 1` sentences `⊥, ¬⊥, …, ¬^m ⊥` two
distinct ones receive the same number, whatever the numbering into a structure of `m` elements. -/
theorem nots_collide {L : Language} {M : Type*} [Fintype M] (f : L.Sentence → M) :
    ∃ i j, i < j ∧ j ≤ Fintype.card M ∧ nots L i ≠ nots L j ∧ f (nots L i) = f (nots L j) := by
  have h : Fintype.card M < Fintype.card (Fin (Fintype.card M + 1)) := by simp
  obtain ⟨a, b, hab, hf⟩ := Fintype.exists_ne_map_eq_of_card_lt (fun k : Fin (Fintype.card M + 1) => f (nots L k)) h
  rcases lt_or_gt_of_ne (Fin.val_ne_of_ne hab) with hlt | hgt
  · exact ⟨a, b, hlt, Nat.lt_succ_iff.mp b.isLt, fun e => (Nat.ne_of_lt hlt) (nots_injective L e), hf⟩
  · exact ⟨b, a, hgt, Nat.lt_succ_iff.mp a.isLt, fun e => (Nat.ne_of_lt hgt) (nots_injective L e), hf.symm⟩

/-! ### 25:D1, 25:D3 — the part cannot hold the whole -/

section part

/-- 25:D1 (Theorem part (1)) — an agent whose storage takes `a^K` states (strings of length `K` over an alphabet
of `a` letters) in a structure of more than `a^K` elements has no injective encoding of the elements. -/
theorem no_injective_encoding {A Alph : Type*} [Fintype A] [Fintype Alph] (K : ℕ)
    (h : Fintype.card Alph ^ K < Fintype.card A) (ρ : A → (Fin K → Alph)) : ¬ Function.Injective ρ := fun hinj => by
  have := Fintype.card_le_of_injective ρ hinj
  rw [Fintype.card_pi_const] at this
  exact absurd this (Nat.not_le.mpr h)

/-- 25:D3 (Lemma wrap (1), aliasing) — every total reading identifies distinct elements when the states are
fewer than the elements. -/
theorem reading_identifies {A R : Type*} [Fintype A] [Fintype R] (h : Fintype.card R < Fintype.card A) (ρ : A → R) :
    ∃ x y, x ≠ y ∧ ρ x = ρ y :=
  Fintype.exists_ne_map_eq_of_card_lt ρ h

/-- 25:D3 (Lemma wrap (1), the multiplicity) — some reading stands for at least `⌈m / a^K⌉` elements: its
fibre, multiplied by the number of states, covers the structure. -/
theorem alias_fibre {A R : Type*} [Fintype A] [Fintype R] [DecidableEq R] [Nonempty R] (ρ : A → R) :
    ∃ y, Fintype.card A ≤ Fintype.card R * Fintype.card {x // ρ x = y} := by
  by_contra h
  simp only [not_exists, not_le] at h
  have hsum : Fintype.card A = ∑ y : R, (Finset.univ.filter (fun x => ρ x = y)).card := by
    rw [← Finset.card_univ]; exact Finset.card_eq_sum_card_fiberwise (fun x _ => Finset.mem_univ (ρ x))
  obtain ⟨y0⟩ := ‹Nonempty R›
  have hlt : ∑ y : R, Fintype.card R * (Finset.univ.filter (fun x => ρ x = y)).card < ∑ _y : R, Fintype.card A :=
    Finset.sum_lt_sum_of_nonempty ⟨y0, Finset.mem_univ _⟩ (fun y _ => by
      have := h y; rwa [Fintype.card_subtype] at this)
  rw [← Finset.mul_sum, ← hsum, Finset.sum_const, Finset.card_univ, smul_eq_mul] at hlt
  exact lt_irrefl _ hlt

/-- 25:D3 (Lemma wrap (1), at least two) — with fewer states than elements some reading stands for at least two
elements. -/
theorem alias_two {A R : Type*} [Fintype A] [Fintype R] [DecidableEq R] [Nonempty R]
    (h : Fintype.card R < Fintype.card A) (ρ : A → R) : ∃ y, 2 ≤ Fintype.card {x // ρ x = y} := by
  obtain ⟨y, hy⟩ := alias_fibre ρ
  refine ⟨y, ?_⟩
  by_contra hlt
  have h1 : Fintype.card {x // ρ x = y} ≤ 1 := by omega
  have h2 : Fintype.card R * Fintype.card {x // ρ x = y} ≤ Fintype.card R * 1 := Nat.mul_le_mul_left _ h1
  omega

/-- 25:D3 (Lemma wrap (1), the aliases) — every element outside a maximal faithfully represented range (a set
on which the reading is injective and which no larger set with that property contains) is read as an element
inside it. -/
theorem alias_outside {A R : Type*} (ρ : A → R) (S : Set A) (hS : Set.InjOn ρ S)
    (hmax : ∀ T : Set A, S ⊆ T → Set.InjOn ρ T → T = S) (x : A) (hx : x ∉ S) : ∃ s ∈ S, ρ s = ρ x := by
  by_contra h
  have h' : ∀ s ∈ S, ρ s ≠ ρ x := fun s hs he => h ⟨s, hs, he⟩
  have hT : Set.InjOn ρ (insert x S) := by
    intro a ha b hb hab
    rcases Set.mem_insert_iff.mp ha with rfl | ha' <;> rcases Set.mem_insert_iff.mp hb with rfl | hb'
    · rfl
    · exact absurd hab.symm (h' b hb')
    · exact absurd hab (h' a ha')
    · exact hS ha' hb' hab
  have hEq := hmax (insert x S) (Set.subset_insert x S) hT
  have hx' : x ∈ insert x S := Set.mem_insert x S
  rw [hEq] at hx'
  exact hx hx'

end part

/-! ### 25:E1, 25:E2 — the reach bound -/

section reach

theorem two_mul_catalan_le (n : ℕ) : 2 * catalan (n + 1) ≤ catalan (n + 2) := by
  rw [catalan_succ (n + 1), Fin.sum_univ_succ, Fin.sum_univ_castSucc]
  simp only [Fin.val_zero, Fin.val_succ, Fin.val_last, Fin.val_castSucc, catalan_zero, Nat.sub_zero, one_mul,
    Nat.sub_self, mul_one]
  omega

/-- 25:E1 (Lemma abundance, the Catalan bound) — `C_{ℓ−1} ≥ 2^{ℓ−2}` for `ℓ ≥ 2`: `2^n ≤ catalan (n + 1)`. -/
theorem two_pow_le_catalan : ∀ n : ℕ, 2 ^ n ≤ catalan (n + 1)
  | 0 => by simp
  | n + 1 => by
    calc 2 ^ (n + 1) = 2 * 2 ^ n := by ring
      _ ≤ 2 * catalan (n + 1) := Nat.mul_le_mul_left 2 (two_pow_le_catalan n)
      _ ≤ catalan (n + 2) := two_mul_catalan_le n

/-- 25:E1 (Lemma abundance, the cohort) — from `ℓ = n + 6` leaves on, the pairs of distinct terms with `ℓ` leaves
number at least `2^ℓ`: `2^(n+6) ≤ C(C_{n+5}, 2)`. -/
theorem cohort_lower (n : ℕ) : 2 ^ (n + 6) ≤ (catalan (n + 5)).choose 2 := by
  have h1 : 2 ^ (n + 4) ≤ catalan (n + 5) := two_pow_le_catalan (n + 4)
  refine le_trans ?_ (Nat.choose_le_choose 2 h1)
  have h16 : 16 ≤ 2 ^ (n + 4) := by
    calc 16 = 2 ^ 4 := by norm_num
      _ ≤ 2 ^ (n + 4) := Nat.pow_le_pow_right (by norm_num) (by omega)
  obtain ⟨y, hy⟩ : ∃ y, 2 ^ (n + 4) = y + 1 := ⟨2 ^ (n + 4) - 1, by omega⟩
  have e : 2 ^ (n + 6) = 4 * (y + 1) := by rw [← hy]; ring
  rw [e, hy, Nat.choose_two_right, Nat.add_sub_cancel, Nat.le_div_iff_mul_le (by norm_num)]
  nlinarith

/-- 25:E1 (Lemma abundance, the count) — the binary trees with `n + 1` inner nodes number at least `2^n`.  They
are the shapes of the closed terms with `ℓ = n + 2` leaves; that identification is the lemma's and is not proved
here. -/
theorem abundance (n : ℕ) : 2 ^ n ≤ (BinaryTree.treesOfNumNodesEq (n + 1)).card := by
  rw [BinaryTree.treesOfNumNodesEq_card_eq_catalan]; exact two_pow_le_catalan n

/-- 25:E2 (Proposition reach, the count) — the records of length at most `B` over `a ≥ 2` letters number fewer
than `a^(B+1)`. -/
theorem records_lt (a B : ℕ) (ha : 2 ≤ a) : ∑ i ∈ Finset.range (B + 1), a ^ i < a ^ (B + 1) :=
  Nat.geomSum_lt ha (fun _ hk => Finset.mem_range.mp hk)

end reach

/-! ### 25:F4 — density -/

/-- 25:F4 (Lemma density, the count) — an injective coding of the strings of length `n` over an alphabet of `a`
letters into `k`-tuples over a structure of `m` elements needs `a^n ≤ m^k`. -/
theorem dense_coding {A M : Type*} [Fintype A] [Fintype M] (n k : ℕ) (c : (Fin n → A) → (Fin k → M))
    (hc : Function.Injective c) : Fintype.card A ^ n ≤ Fintype.card M ^ k := by
  have := Fintype.card_le_of_injective c hc
  rwa [Fintype.card_pi_const, Fintype.card_pi_const] at this

/-! ### 25:H2 — second-order quantifiers over a finite domain -/

section finiteness

/-- 25:H2 (Theorem finiteness, the finite direction, the procedure) — a second-order statement over the `k`-ary
relations of a finite structure is decided by exhaustive evaluation. -/
def decideAllRelations {M : Type*} [Fintype M] [DecidableEq M] (k : ℕ) (P : Finset (Fin k → M) → Prop)
    [DecidablePred P] : Decidable (∀ R, P R) := inferInstance

/-- 25:H2 (Theorem finiteness, the finite direction) — over a structure of `m` elements a second-order
quantifier over `k`-ary relations ranges over the `2^(m^k)` subsets of `M^k`, a finite set. -/
theorem card_relations (M : Type*) [Fintype M] [DecidableEq M] (k : ℕ) :
    Fintype.card (Finset (Fin k → M)) = 2 ^ (Fintype.card M ^ k) := by
  rw [Fintype.card_finset, Fintype.card_pi_const]

end finiteness




-- Ledger predicates of 25-godel (generated by make_predicates.py from docs/25-godel/25-godel-ledger.json; edit the ledger, not this section)
/-- 25:C1 (p25010) — No finite structure interprets $\mathsf{Q}$: a model of $\mathsf{Q}$ has an injective successor with $0$ outside its range, and on a finite set an injective map is onto. -/
theorem p25010 : (∀ {A : Type u_1} [Finite A] (S : A → A), Function.Injective S → ∀ (z : A), ∃ x, S x = z) ∧ ∀ {A : Type u_2} (S : A → A) (z : A), Function.Injective S → (∀ (x : A), S x ≠ z) → Infinite A :=
  And.intro @FRC.Godel.finite_succ_onto (@FRC.Godel.infinite_of_succ)
/-- 25:C2 (p25011) — Completeness and decidability: for finite $\M$ the theory $\Th(\M)$ is complete, consistent and decidable by exhaustive evaluation. A sentence of quantifier depth $q$ takes at most $c\,m^{q}$ atomic evaluations, $c$ depending on its length. One first-order sentence $\sigma_{\M}$ characterises $\M$ up to isomorphism. Cited definitions (not proofs): FRC.Godel.decTheory. -/
theorem p25011 : ∀ {L : FirstOrder.Language} {M : Type u_3} [L.Structure M] [Nonempty M], (L.completeTheory M).IsComplete :=
  @FRC.Godel.theory_complete
/-- 25:C5 (p25014) — Tarski scoped: the $m+1$ sentences $\varphi,\neg\varphi,\dots,\neg^{m}\varphi$ outnumber the $m$ elements of $\M$, so every numbering of the sentences by elements of $\M$ gives two of them the same number. Truth in $\M$ is defined externally by a finite table with the evaluation procedure of C2. What fails is the internalisation of truth. -/
theorem p25014 : ∀ {L : FirstOrder.Language} {M : Type u_3} [Fintype M] (f : L.Sentence → M), ∃ i j, i < j ∧ j ≤ Fintype.card M ∧ FRC.Godel.nots L i ≠ FRC.Godel.nots L j ∧ f (FRC.Godel.nots L i) = f (FRC.Godel.nots L j) :=
  @FRC.Godel.nots_collide
/-- 25:D1 (p25015) — Relational diagonal: an agent of storage capacity $K$ with $a^{K}<m$ has no injective encoding of the elements of $\M$ into its storage states. Every internal representation identifies distinct elements. A fortiori the agent holds no faithful model of $\M$ that also represents the model's own encoding map. -/
theorem p25015 : ∀ {A : Type u_1} {Alph : Type u_2} [Fintype A] [Fintype Alph] (K : ℕ), Fintype.card Alph ^ K < Fintype.card A → ∀ (ρ : A → Fin K → Alph), ¬Function.Injective ρ :=
  @FRC.Godel.no_injective_encoding
/-- 25:D3 (p25017) — Wrap, aliasing: every total assignment of storage readings to the elements of $\M$ identifies distinct elements when $a^{K}<m$. Some reading stands for at least $\lceil m/a^{K}\rceil\ge2$ elements. Every element outside a maximal faithfully represented range is read as an alias of one inside it. -/
theorem p25017 : (∀ {A : Type u_1} {R : Type u_2} [Fintype A] [Fintype R], Fintype.card R < Fintype.card A → ∀ (ρ : A → R), ∃ x y, x ≠ y ∧ ρ x = ρ y) ∧ (∀ {A : Type u_3} {R : Type u_4} [Fintype A] [Fintype R] [DecidableEq R] [Nonempty R] (ρ : A → R), ∃ y, Fintype.card A ≤ Fintype.card R * Fintype.card { x // ρ x = y }) ∧ (∀ {A : Type u_5} {R : Type u_6} [Fintype A] [Fintype R] [DecidableEq R] [Nonempty R], Fintype.card R < Fintype.card A → ∀ (ρ : A → R), ∃ y, (2 : ℕ) ≤ Fintype.card { x // ρ x = y }) ∧ ∀ {A : Type u_7} {R : Type u_8} (ρ : A → R) (S : Set A), Set.InjOn ρ S → (∀ (T : Set A), S ⊆ T → Set.InjOn ρ T → T = S) → ∀ x ∉ S, ∃ s ∈ S, ρ s = ρ x :=
  And.intro @FRC.Godel.reading_identifies (And.intro @FRC.Godel.alias_fibre (And.intro @FRC.Godel.alias_two (@FRC.Godel.alias_outside)))
/-- 25:E1 (p25019) — Abundance: the closed terms over $\{1,+\}$ with $\ell$ leaves are the full binary trees, $C_{\ell-1}\ge2^{\ell-2}$ in number. In $\M_p$ all have the value $\ell\bmod p$, so any two give a true equation of length $O(\ell)$, at least $2^{\ell}$ of them for $\ell\ge6$. The true sentences of length at most $L$ number at least $2^{\alpha L}$ for large $L$, $\alpha>0$ constant. -/
theorem p25019 : (∀ (n : ℕ), (2 : ℕ) ^ n ≤ catalan (n + (1 : ℕ))) ∧ (∀ (n : ℕ), (2 : ℕ) ^ (n + (6 : ℕ)) ≤ (catalan (n + (5 : ℕ))).choose (2 : ℕ)) ∧ ∀ (n : ℕ), (2 : ℕ) ^ n ≤ (BinaryTree.treesOfNumNodesEq (n + (1 : ℕ))).card :=
  And.intro @FRC.Godel.two_pow_le_catalan (And.intro @FRC.Godel.cohort_lower (@FRC.Godel.abundance))
/-- 25:E2 (p25020) — Vanishing reach: an agent of capacity $(K,H)$ certifies at most $a^{B+1}$ sentences over all its runs, the records being strings of length at most $B$. The certified fraction of the truths of length at most $L$ (E1) is at most $a^{B+1}/2^{\alpha L}$, below $1/N$ for every $N$ once $L$ is large enough. -/
theorem p25020 : ∀ (a B : ℕ), (2 : ℕ) ≤ a → ∑ i ∈ Finset.range (B + (1 : ℕ)), a ^ i < a ^ (B + (1 : ℕ)) :=
  @FRC.Godel.records_lt
/-- 25:F4 (p25026) — Density: an injective coding of length-$n$ strings into $\M$-tuples needs $k\ge n\log a/\log m$ coordinates ($m^{k}\ge a^{n}$). The variable names alone cost order $k\log_{a}k$ symbols. The template therefore fails at every scale beyond a threshold $t(\M)$ of order $m\log_{a}m$: at $a=2$, about $10^{32}$ symbols at $m=2^{100}$, beyond $10^{300}$ at $m=2^{1000}$. -/
theorem p25026 : ∀ {A : Type u_1} {M : Type u_2} [Fintype A] [Fintype M] (n k : ℕ) (c : (Fin n → A) → Fin k → M), Function.Injective c → Fintype.card A ^ n ≤ Fintype.card M ^ k :=
  @FRC.Godel.dense_coding
/-- 25:H2 (p25036) — Finiteness, the finite direction: for finite $\M$ the full second-order theory $\ThSO(\M)$ is decidable. A second-order quantifier over $k$-ary relations ranges over the $2^{m^{k}}$ subsets of $\M^{k}$, and exhaustive evaluation decides every second-order sentence. Cited definitions (not proofs): FRC.Godel.decideAllRelations. -/
theorem p25036 : ∀ (M : Type u_1) [Fintype M] [DecidableEq M] (k : ℕ), Fintype.card (Finset (Fin k → M)) = (2 : ℕ) ^ Fintype.card M ^ k :=
  @FRC.Godel.card_relations
-- end ledger predicates

end FRC.Godel

-- Ledger predicates: axioms (each predicate's, computed here)
#print axioms FRC.Godel.p25010
#print axioms FRC.Godel.p25011
#print axioms FRC.Godel.p25014
#print axioms FRC.Godel.p25015
#print axioms FRC.Godel.p25017
#print axioms FRC.Godel.p25019
#print axioms FRC.Godel.p25020
#print axioms FRC.Godel.p25026
#print axioms FRC.Godel.p25036
