import FrcLedger.Theme.Extension

/-!
# FrcLedger.Keys.Extension — the keyed theorems of the extension theme (ledger migration, task LM19)

One declaration per key, `FRC.LedgerML.p<key>`, generated by `make_keys.py` from the ledgers' Lean bindings: the theorem
that every row carrying the key asserts, proved from the themes alone. The paper's module keeps its declaration
`FRC.<Module>.p<key>` as an alias. Every declaration has the axioms of Mathlib's hierarchy at most (`check_axioms.py`).
-/

namespace FRC.LedgerML

-- Keys of the extension theme (generated by make_keys.py from the ledgers' Lean bindings; edit the ledgers, not this file)
/-- p03006 — 3:B2. Nonexistence of a causal square root: no $c\in\Fp$ has $c^{2}=\nu$ for $\nu\in N$; for $c\in\Fpx$ every coefficient of $-c^{2}t^{2}+x^{2}+y^{2}+z^{2}$ is a square ($-1=\im^{2}$), the form Euclidean with $\p^{3}+\p^{2}-\p$ zeros; $c=0$ gives a degenerate form. -/
theorem p03006 : (∀ {F : Type u_1} [Field F] (ν c : F), ¬IsSquare ν → c ^ (2 : ℕ) ≠ ν) ∧ ∀ {F : Type u_2} [Field F] [Fintype F], Fintype.card F % (4 : ℕ) ≠ (3 : ℕ) → ∀ (c : F), IsSquare (-c ^ (2 : ℕ)) :=
  And.intro @FRC.Extension.no_causal_root (@FRC.Extension.neg_sq_is_square)
/-- p03007 — 3:B3. Square-class absorption: if $a_{i}/a_{0}\in S$ for all $\im$ then $Q\simeq a_{0}\sum Y_{i}^{2}$ by $Y_{i}=w_{i}X_{i}$, $w_{i}^{2}=a_{i}/a_{0}$; no root of $a_{0}$ is needed, and none exists for $a_{0}\in N$ ($-a_{0}$ is a nonsquare with it). -/
theorem p03007 : ∀ {F : Type u_1} [Field F] (a0 a1 a2 a3 w1 w2 w3 x0 x1 x2 x3 : F), w1 ^ (2 : ℕ) * a0 = a1 → w2 ^ (2 : ℕ) * a0 = a2 → w3 ^ (2 : ℕ) * a0 = a3 → a0 * x0 ^ (2 : ℕ) + a1 * x1 ^ (2 : ℕ) + a2 * x2 ^ (2 : ℕ) + a3 * x3 ^ (2 : ℕ) = a0 * (x0 ^ (2 : ℕ) + (w1 * x1) ^ (2 : ℕ) + (w2 * x2) ^ (2 : ℕ) + (w3 * x3) ^ (2 : ℕ)) :=
  @FRC.Extension.absorb
/-- p03009 — 3:B5. The Witt decomposition: for $\nu\in N$ the plane $x^{2}-\nu t^{2}$ (the norm of $\Fpq$) is anisotropic and $y^{2}+z^{2}=(y+iz)(y-iz)$ hyperbolic, so $Q_{\nu}=H\perp\langle1,-\nu\rangle$, index one; for $\nu=w^{2}$ the $(t,x)$-plane is hyperbolic too, $H\perp H$. Over $\Fpq$, $\nu=c^{2}$ and $Q_{\nu}\simeq\sum X_{i}^{2}$: hyperbolic ($16\,225$ zeros at $q=25$); the extension dissolves the split. -/
theorem p03009 : ∀ {F : Type u_1} [Field F] (ν t x : F), ¬IsSquare ν → x ^ (2 : ℕ) = ν * t ^ (2 : ℕ) → t = (0 : F) ∧ x = (0 : F) :=
  @FRC.Extension.aniso_tx
/-- p03013 — 3:C2. $\Lambda(\gamma,b)$ preserves $-\nu t^{2}+x^{2}$ exactly and $\Lambda(z_{1})\Lambda(z_{2})=\Lambda(z_{1}z_{2})$: the boosts are the norm-one cycle $N^{1}\simeq C_{\p+1}$, the non-split torus, and exhaust $SO(Q_{\nu},\Fp)$ in dimension $1{+}1$ ($6$, $14$, $18$ at $5$, $13$, $17$); with $\nu\in S$ the same construction is the split torus $C_{\p-1}$ --- the two tori are the two signatures (00:C3). -/
theorem p03013 : (∀ {F : Type u_1} [Field F] (ν γ b t x : F), γ ^ (2 : ℕ) - ν * b ^ (2 : ℕ) = (1 : F) → (γ * x + ν * b * t) ^ (2 : ℕ) - ν * (γ * t + b * x) ^ (2 : ℕ) = x ^ (2 : ℕ) - ν * t ^ (2 : ℕ)) ∧ (∀ {F : Type u_2} [Field F] (ν γ1 b1 γ2 b2 : F), !![γ1, b1; ν * b1, γ1] * !![γ2, b2; ν * b2, γ2] = !![γ1 * γ2 + ν * (b1 * b2), γ1 * b2 + b1 * γ2; ν * (γ1 * b2 + b1 * γ2), γ1 * γ2 + ν * (b1 * b2)]) ∧ ∀ {F : Type u_3} [Field F] (ν γ b : F), γ ^ (2 : ℕ) - ν * b ^ (2 : ℕ) = (1 : F) → !![γ, b; ν * b, γ].transpose * !![-ν, (0 : F); (0 : F), (1 : F)] * !![γ, b; ν * b, γ] = !![-ν, (0 : F); (0 : F), (1 : F)] :=
  And.intro @FRC.Extension.boost_preserves (And.intro @FRC.Extension.boost_comp (@FRC.Extension.boost_orthogonal))
/-- p03014 — 3:C3. Velocity: $\gamma\neq0$ on every boost; $v=-\nu b/\gamma\in\Fp$; $\gamma^{2}(\nu-v^{2})=\nu$, the finite $\gamma=1/\sqrt{1-\beta^{2}}$ with $\beta^{2}=v^{2}/\nu$ ($\beta$ itself is no shell quantity, 8:B8); Einstein's law $v_{12}=(v_{1}+v_{2})/(1+v_{1}v_{2}/\nu)$ exact, the denominator never zero; $v$ is two-to-one on $N^{1}$. -/
theorem p03014 : (∀ {F : Type u_1} [Field F] [Fintype F], Fintype.card F % (4 : ℕ) ≠ (3 : ℕ) → ∀ (ν γ b : F), ¬IsSquare ν → γ ^ (2 : ℕ) - ν * b ^ (2 : ℕ) = (1 : F) → γ ≠ (0 : F)) ∧ (∀ {F : Type u_2} [Field F] (ν γ b v : F), γ ^ (2 : ℕ) - ν * b ^ (2 : ℕ) = (1 : F) → v * γ = -(ν * b) → γ ^ (2 : ℕ) * (ν - v ^ (2 : ℕ)) = ν) ∧ ∀ {F : Type u_3} [Field F] (ν γ1 b1 γ2 b2 v1 v2 v12 : F), γ1 * γ2 ≠ (0 : F) → v1 * γ1 = -(ν * b1) → v2 * γ2 = -(ν * b2) → v12 * (γ1 * γ2 + ν * (b1 * b2)) = -(ν * (γ1 * b2 + b1 * γ2)) → v12 * (ν + v1 * v2) = ν * (v1 + v2) :=
  And.intro @FRC.Extension.gamma_ne_zero (And.intro @FRC.Extension.gamma_velocity (@FRC.Extension.velocity_addition))
-- end keys

end FRC.LedgerML
