import FrcLedger.Keys.Chart

/-!
# FrcLedger.Ledgers.Master.Chart — the certificate of the master's blocks L and P, the chart clauses, Mathlib (ledger migration, task LM30)

Generated by `ci/make_ledgers.py` from the master's data (`docs/00-ledger.json`, `docs/predictions.json`), the ledger file's `CHART` and the key files. One
`#print axioms` per key of the ledger that this library proves, guarded by the message it must print: the build
fails if a key's axioms change (the axioms of Mathlib's hierarchy at most). Nothing imports this file; `lake build FrcLedger.Ledgers.Master.Chart` checks it.
-/

-- 00:L1 (p00084)
/-- info: 'FRC.LedgerML.p00084' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms FRC.LedgerML.p00084

-- 00:L3 (p00181)
/-- info: 'FRC.LedgerML.p00181' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms FRC.LedgerML.p00181

-- 00:L8 (p00148)
/-- info: 'FRC.LedgerML.p00148' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms FRC.LedgerML.p00148

-- 00:P1 (p00133)
/-- info: 'FRC.LedgerML.p00133' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms FRC.LedgerML.p00133
