# 10-dimensions — validation package
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/gamayos/finite-ring-space/blob/main/src/10-dimensions/10-dimensions-main.ipynb)

**Paper.** *Dimensional Analysis over Finite Holographic Substrate* (Akhtman, 2026), `10-dim` of the FRC corpus.
**Package.** `finite-ring-space/src/10-dimensions` — two exact suites driven by this notebook, 13 family checks aggregating
210 exact micro-checks (integers, residues, exact rationals; no floats, no random sampling). A family check is a layer of
`verify_domains.py` (A–H) or a claim of `check_lift.py` (L1–L5), identified as `<script>.<family>`; each names the row(s) of the paper's
predicate ledger it witnesses (the paper's Section "Machine verification and predicate ledger", rows cited as `10:XN`; public copy at
`docs/10-dimensions/10-dimensions-ledger.html`), and the ledger's source column cites the check ids in return. Master-ledger rows of the
corpus reached through the paper rows: `00:D7` (a unit is a reciprocal cross-frame relation), `00:C12` (temperature and the arity),
`00:C13` (the window ladder and the minimal pair), `00:C8` (the c-square congruence), `00:B10` (the pair-inert sign sector).
The manuscript's 105 source gates (`check_gates.py`) read the paper's LaTeX and run in the corpus tree, not here.

**Kinds.** Every check is `EXACT`: a pass is a proof on the tested instances (the toy shell F_13, the shells p = 29 and 229, the
laboratory-scale shell 173, and both instantiated Carriers Ω = 233 and Ω = 2 408 561).

**Run.** Cell by cell, or *Runtime → Run all*; ≈ 10 s on Colab. The last cell writes `results.json` and fails loudly if any check fails.

In [1]:
# --- environment: clone the package if this notebook is not already running inside it (Colab). Pure Python; nothing to install.
import os
if not os.path.exists("dimcommon.py"):
    if not os.path.exists("finite-ring-space"):
        !git clone --filter=blob:none --sparse https://github.com/gamayos/finite-ring-space.git
        os.chdir("finite-ring-space")
        !git sparse-checkout set src/10-dimensions
        os.chdir("src/10-dimensions")
    else:
        os.chdir("finite-ring-space/src/10-dimensions")
print("working directory:", os.path.join(*os.getcwd().split(os.sep)[-3:]))

working directory: finite-ring-space/src/10-dimensions


In [2]:
import importlib, dimcommon as dcommon
importlib.reload(dcommon)         # a fresh registry if the notebook is re-run
print("families registered:", len(dcommon.LABELS))

families registered: 13


## The exact suite, layers A–H  (`verify_domains.py`, EXACT)
The shell datum and domain algebra on F_13 (A), the quartet at the unit face in exact rationals (B), the defining congruences on the lab Carrier (C), both Carriers with faces, minimality and temperature (D), covariance witnesses (E), the window bound and twisted action (F), realized action, the window ladder and meridian transport (G), the pair layer and representative inertness (H).

| id | claim | ledger rows |
|---|---|---|
| `dom.A` | shell datum and domain algebra on F_13: frame datum (g = 2, i = −g^κ, π = 2κ, 4κ = p−1); the group law, inverses and grading of D_p = Z_p × Z_{p−1}; the internal flag I_q = [T]^κ unique of order four, no flag of space, horizon-inaccessible, covariant; realization a homomorphism; the derived domains (m, F, S, G, Compton, Planck area, Schwarzschild, orbital frequency); fibrewise addition and local recovery at H = 5 | 10:C2, 10:C3, 10:D2, 10:D6, 10:F2, 10:F4, 10:G1, 10:G3 |
| `dom.B` | the quartet at the unit face: exponent-vector relation lattice over {ℓ_P, t_P, ħ} (both faces of c and ħ differ by ℓp = tE; rank two; k_B and ℓE add nothing); exact-rational instantiation of every stated equality (|k_B|c = ħ, m_P, G, Θ_P, {c, ħ, G} ↔ quartet); 4 − 1 = 3 degrees of freedom; flag positions (0,0,1,1) | 10:E2, 10:E3 |
| `dom.C` | the defining congruences on the lab Carrier Ω = 2 408 561 (S = 602 140): admissibility; 2G ≡ −1 unique; ħ² ≡ −1, k_B² ≡ −2, 2c² ≡ 1 with their exact root pairs; G ≡ −c², G² ≡ 4⁻¹, h ≡ −ħ; m_P² ≐ Ω ≡ 0 | 10:E4 |
| `dom.D` | both Carriers (233 and the lab Carrier): the congruence-and-closure system, ħcG⁻¹ landing in the k_B pair; the representative annex; the admissibility minimality scan certifying (13, 233) with the counterfactuals; [Θ] = [L][T]⁻² and the Unruh closure; the crossing-degree embedding injective and windowed-faithful | 10:E4, 10:E5, 10:E9, 10:F3, 10:G1 |
| `dom.E` | covariance: the naive character ill-defined on the modular projection; (p−1, 0) trivial character yet non-neutral; the ε-composition failure; window covariance below the bound; pushforward-invariant labels {0, π}; the quarter-turn fix/swap criterion ε ≡ ±1 (mod 4); the index-two sublattice ⟨c, ħ, G⟩ (det −2) | 10:C5 |
| `dom.F` | the (0, π) witness forcing H < 2κ; the σ-twisted action equivariant by full sweep on p = 13 and 229 with the plain-lift failure; σ multiplicative mod 4; δ_S, δ_C involutions, δ_C carrying [L] ↦ [p], [T] ↦ [E] | 10:C5, 10:D1 |
| `dom.G` | realized action against the Z³-representative failure; the flagged label (0, 0; 1) moving under ε = −1; the window ladder 2√κ < κ/2 < κ < 2κ nested for every κ ≥ 17 and failing for κ = 3; (2√κ)² = p−1, (2√S)² = Ω−1; the flagged ratio F/a; meridian transport (L T^κ)^p = I_q on three shells; both roots on both Carriers | 10:C5, 10:D2, 10:G2 |
| `dom.H` | the pair layer: pair multiplication well defined; the linkage {±k_B}{±c} = {±ħ} derived at pair level; ħcG⁻¹ in the k_B pair via (ħcG⁻¹)² ≡ −2; representative inertness — exactly the four assignments with σ_ħ = σ_c σ_k admissible, a (Z/2)², every identity holding on each; the ħ-flip relabelling of {ħ, h} | 10:E4, 10:E5 |

Ledger rows witnessed: 10:C2, 10:C3, 10:C5, 10:D1, 10:D2, 10:D6, 10:E2, 10:E3, 10:E4, 10:E5, 10:E9, 10:F2, 10:F3, 10:F4, 10:G1, 10:G2, 10:G3.

In [3]:
import verify_domains; verify_domains.run()

  [PASS] dom.A    EXACT [10:C2, 10:C3, 10:D2, 10:D6, 10:F2, 10:F4, 10:G1, 10:G3] shell datum and domain algebra on F_13: frame datum (g = 2, i = −g^κ, π = 2κ, 4κ = p−1); the group law, invers  --  32 exact micro-checks
  [PASS] dom.B    EXACT [10:E2, 10:E3] the quartet at the unit face: exponent-vector relation lattice over {ℓ_P, t_P, ħ} (both faces of c and ħ diffe  --  30 exact micro-checks
  [PASS] dom.C    EXACT [10:E4] the defining congruences on the lab Carrier Ω = 2 408 561 (S = 602 140): admissibility; 2G ≡ −1 unique; ħ² ≡ −  --  13 exact micro-checks
  [PASS] dom.D    EXACT [10:E4, 10:E5, 10:E9, 10:F3, 10:G1] both Carriers (233 and the lab Carrier): the congruence-and-closure system, ħcG⁻¹ landing in the k_B pair; the  --  50 exact micro-checks
  [PASS] dom.E    EXACT [10:C5] covariance: the naive character ill-defined on the modular projection; (p−1, 0) trivial character yet non-neut  --  18 exact micro-checks
  [PASS] dom.F    EXACT [10:C5, 10:D1] the (0, π) witness forcing 

## The lift  (`check_lift.py`, EXACT)
Proposition `lift`: the flag records the fractional-Fourier quarter the chart duality forgets — the operator four-cycle, the chart shadow, the record map, the Carrier face of order four, and the invariance classification, on the shells (13, 2) and (173, 3) and the Carriers 233 and 2 408 561.

| id | claim | ledger rows |
|---|---|---|
| `lift.L1` | operator four-cycle: F = iW on F_p^{p−1}, F² = J, F⁴ = I, F² ≠ I (p = 13, 173) | 10:D3 |
| `lift.L2` | chart shadow of order two: F exchanges the two dual charts, J exchanges none; the cardinal skeleton acts on charts as s mod 2 | 10:D3 |
| `lift.L3` | record map s ↦ I_q^s an isomorphism Z_4 → the flag subgroup {0, κ, 2κ, 3κ}; the quotient by {0, 2κ} returns s mod 2 | 10:D3 |
| `lift.L4` | Carrier face: ħ² = −1 (mod Ω), ħ⁴ = 1, ħ² ≠ 1 — the crossing quantum has order four, never two (Ω = 233, 2 408 561) | 10:D3 |
| `lift.L5` | invariance on the realized lattice: {u : εu = u for every admissible ε} = {0, 2κ}; witnesses (κ,1) ↦ 2κ and (−κ,1) ↦ 0 invariant, (0,1) ↦ κ not, (0,2) ↦ 2κ invariant | 10:C5, 10:D3 |

Ledger rows witnessed: 10:C5, 10:D3.

In [4]:
import check_lift; check_lift.run()

  [PASS] lift.L1  EXACT [10:D3] operator four-cycle: F = iW on F_p^{p−1}, F² = J, F⁴ = I, F² ≠ I (p = 13, 173)  --  2 exact micro-checks
  [PASS] lift.L2  EXACT [10:D3] chart shadow of order two: F exchanges the two dual charts, J exchanges none; the cardinal skeleton acts on ch  --  2 exact micro-checks
  [PASS] lift.L3  EXACT [10:D3] record map s ↦ I_q^s an isomorphism Z_4 → the flag subgroup {0, κ, 2κ, 3κ}; the quotient by {0, 2κ} returns s   --  2 exact micro-checks
  [PASS] lift.L4  EXACT [10:D3] Carrier face: ħ² = −1 (mod Ω), ħ⁴ = 1, ħ² ≠ 1 — the crossing quantum has order four, never two (Ω = 233, 2 408  --  2 exact micro-checks
  [PASS] lift.L5  EXACT [10:C5, 10:D3] invariance on the realized lattice: {u : εu = u for every admissible ε} = {0, 2κ}; witnesses (κ,1) ↦ 2κ and (−  --  2 exact micro-checks


## Summary
Writes `results.json` (one record per family check: id, the ledger row(s) witnessed, claim, PASS/FAIL, the micro-check count) and raises if any check failed.

In [5]:
ok = dcommon.summary(write=True)
failed = [r["id"] for r in dcommon.RESULTS if not r["ok"]]
assert ok, f"FAILED checks: {failed}"
print(f"all {len(dcommon.RESULTS)} family checks pass ({len(dcommon.MICRO)} exact micro-checks); records in results.json")


SUMMARY: 13/13 checks passed (210 exact micro-checks)
all 13 family checks pass (210 exact micro-checks); records in results.json
