import FrcLedger.Keys.Extension

/-!
# FrcLedger.Ledgers.P03Causality — the certificate of the ledger of 3-causality, Mathlib (ledger migration, task LM20)

Generated by `ci/make_ledgers.py` from the ledger (`docs/3-causality/3-causality-ledger.json`) and the key files. One
`#print axioms` per key of the ledger that this library proves, guarded by the message it must print: the build
fails if a key's axioms change (the axioms of Mathlib's hierarchy at most). Nothing imports this file; `lake build FrcLedger.Ledgers.P03Causality` checks it.
-/

-- 3:B2 (p03006)
/-- info: 'FRC.LedgerML.p03006' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms FRC.LedgerML.p03006

-- 3:B3 (p03007)
/-- info: 'FRC.LedgerML.p03007' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms FRC.LedgerML.p03007

-- 3:B5 (p03009)
/-- info: 'FRC.LedgerML.p03009' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms FRC.LedgerML.p03009

-- 3:C2 (p03013)
/-- info: 'FRC.LedgerML.p03013' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms FRC.LedgerML.p03013

-- 3:C3 (p03014)
/-- info: 'FRC.LedgerML.p03014' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms FRC.LedgerML.p03014
