"""master/foundation — the ledger file of the master's block A, the Foundation (ledger migration, task LM23, 5 October 2026).

The master predicate ledger (00-ledger/predicates/index.md, published as docs/00-ledger.json) states block A. This file
binds its theorem rows to the framework: the table of keys (generated from docs/00-ledger.json by ci/make_ledgers.py),
the Lean proofs each key conjoins (PROOFS, written here), the shells, and the checks, which call the foundation theme
(frc/foundation.py). Each check names the rows it decides or corroborates (LEDGER), under a `# 00:A6 (p00188)` marker on
the check that decides the row (PREDICATES).

The rows are A4 (the bounded observer), A6, A11, A12 and A13, the block's T rows: the pillars' formal shadows, proved in
lean/FrcCore/Theme/Foundation.lean and lean/FrcCore/Theme/Drive.lean with no generator assumed. A10, the trusted base, is
a D row: gate G19 enforces its clause on unboundedness, and every key's empty axiom list (gate G08) its kernel clause.
The checks run on the three Carriers of the Carrier's block file, Ω = 233, 30 089 and 2 408 561, with their Subjects
13, 173 and 1 373, and as sweeps over every modulus or prime below a bound. The Lean side is the key file
lean/FrcCore/Keys/Foundation.lean and the certificate lean/FrcCore/Ledgers/Master/Foundation.lean.

    python3 -m frc.ledgers.master.foundation        every block, the census; exit 1 if a check fails (≈ 15 s)
    python3 -m frc.ledgers.master.foundation M      one block (U, Q, I, H or M)
    from frc.ledgers.master.foundation import R; R.predicate("00:A13")    one row: its blocks run once per session

Blocks:  U  a bounded observer is a proper part          EXACT  (00:A4)
         Q  counting closes by return                     EXACT  (00:A6)
         I  completeness is primality                     EXACT  (00:A11)
         H  the quarter-turn exists iff p ≡ 1 (mod 4)     EXACT  (00:A12)
         M  every prime carries a frame                   EXACT  (00:A13)

The notebook frc/ledgers/master/foundation.ipynb runs one row per cell, the cell's id its key (gate G13).
"""
import itertools
import sys

from frc import arith
from frc.registry import Registry
from frc.foundation import (half_power, quarter_turn, quarter_turns, successor_orbit, principal_ideal, is_complete,
                            zero_divisors, element_order, drive, collision)

# ---- generated by ci/make_ledgers.py from docs/00-ledger.json; edit the ledger, not this table ----
BLOCK = "A"
KEYS = {"A1": "p00001", "A2": "p00004", "A3": "p00003", "A4": "p00159", "A5": "p00195", "A6": "p00188", "A7": "p00008", "A8": "p00009", "A9": "p00010", "A10": "p00161", "A11": "p00162", "A12": "p00163", "A13": "p00164", "A14": "p00196"}       # every row of the block: its label and its accession key
LEAN = {"A4": "core", "A6": "core", "A11": "core", "A12": "core", "A13": "core"}       # the rows with a Lean declaration: the libraries whose key files prove them
# ---- end of the generated table ----

# The Lean proofs of the rows' keys: the theorems of the themes that each key conjoins (lean/make_keys.py writes the keys
# FRC.Ledger.p<key> from them). The master's block file is the binding's source, as a paper's \lean{} cells are its own.
PROOFS = {
    "A4": ["FRC.Foundation.observer_part"],
    "A6": ["FRC.Foundation.successor_cycle"],
    "A11": ["FRC.Shell.Prime.isPrime_iff_complete"],
    "A12": ["FRC.Shell.Prime.quarter_turn_iff"],
    "A13": ["FRC.Shell.Prime.exists_drive"],
}

LEAN_ONLY = ()                  # the rows with a Lean declaration and no python check (gate G12): none

# The Carriers (Ω, the Subject p), as in the Carrier's block file: Ω = 4S + 1 prime, p prime with p² < Ω.
SHELLS = [(233, 13), (30089, 173), (2408561, 1373)]
SWEEP = 5000                    # the sweeps over primes run below it
SMALL = 6                       # the exhaustive readings run over every total of at most SMALL points

# The rows each check decides or corroborates.
LEDGER = {
    "U1": "00:A4", "U2": "00:A4", "U3": "00:A4",
    "Q1": "00:A6", "Q2": "00:A6",
    "I1": "00:A11", "I2": "00:A11",
    "H1": "00:A12", "H2": "00:A12",
    "M1": "00:A13", "M2": "00:A13", "M3": "00:A13",
}

BLOCKS = {"U": "a bounded observer is a proper part", "Q": "counting closes by return", "I": "completeness is primality",
          "H": "the quarter-turn exists iff p ≡ 1 (mod 4)", "M": "every prime carries a frame"}

# the deciding check of each row; the sweeps corroborate
PREDICATES = {"00:A4": "U1", "00:A6": "Q1", "00:A11": "I2", "00:A12": "H1", "00:A13": "M1"}

R = Registry("00", "foundation", LEDGER, PREDICATES, sources=[__file__])

for _Om, _p in SHELLS:
    assert arith.is_prime(_Om) and _Om % 4 == 1 and arith.is_prime(_p) and _p * _p < _Om, (_Om, _p)


def _primes(lo, hi):
    return [n for n in range(lo, hi) if arith.is_prime(n)]


# ------------------------------------------------------------------------------------------------------------
# block U: a bounded observer is a proper part (00:A4)
# an observer with o < Ω states holds no injective encoding of the Ω points: every reading identifies two distinct points
# (Foundation.lean, observer_part; the pigeonhole).
@R.block("U", BLOCKS["U"])
def block_U():
    """Block U — a bounded observer is a proper part (EXACT): U1–U3."""
    # 00:A4 (p00159)
    total, bad = 0, []
    for n in range(1, SMALL + 1):
        for o in range(n):
            for rho in itertools.product(range(o), repeat=n):
                total += 1
                if collision(lambda x: rho[x], n) is None: bad.append((n, o, rho))
    R.check("U1", f"every total of n ≤ {SMALL} points and every observer of o < n states: each of the o^n readings identifies two "
            "distinct points (exhaustive)", not bad, f"{total} readings; injective ones {bad[:3]}")
    # U2 the bound is sharp: o = n states admit an injective reading
    ok = all(collision(lambda x: x, n) is None for n in range(1, SMALL + 1)) and all(
        all(collision(lambda x: rho[x], n) is None for rho in itertools.permutations(range(n))) for n in range(1, SMALL + 1))
    R.check("U2", f"the bound is sharp: for every n ≤ {SMALL}, an observer of n states reads the n points injectively (each of the n! "
            "bijections, the identity among them)", ok, "o < n forces a collision, o = n does not")
    # U3 on the three Carriers, an observer of Ω − 1 states: three readings, each with two distinct points found by search
    ok, det = True, []
    for Om, p in SHELLS:
        o = Om - 1
        readings = {"x mod (Ω−1)": lambda x: x % o, "min(x, Ω−2)": lambda x: min(x, o - 1),
                    "p x mod (Ω−1)": lambda x: p * x % o}
        for name, rho in readings.items():
            c = collision(rho, Om)
            ok &= c is not None and c[0] != c[1] and rho(c[0]) == rho(c[1]) and all(0 <= rho(x) < o for x in (c[0], c[1]))
        det.append(f"Ω={Om}: x mod (Ω−1) identifies {collision(readings['x mod (Ω−1)'], Om)}")
    R.check("U3", "on the three Carriers, an observer of Ω − 1 states: the readings x mod (Ω−1), min(x, Ω−2) and p·x mod (Ω−1) each "
            "identify two distinct points, found by search", ok, "; ".join(det))


# ------------------------------------------------------------------------------------------------------------
# block Q: counting closes by return (00:A6)
# on q ≥ 2 points the successor x ↦ x + 1 has no fixed point, returns after exactly the multiples of q steps and
# reaches every point (Foundation.lean, successor_cycle).
@R.block("Q", BLOCKS["Q"])
def block_Q():
    """Block Q — counting closes by return (EXACT): Q1, Q2."""
    # 00:A6 (p00188)
    ok, det = True, []
    for Om, p in SHELLS:
        for q in (Om, p):
            orb = successor_orbit(q, 0)
            ok &= len(orb) == q and sorted(orb) == list(range(q)) and all((x + 1) % q != x for x in (0, 1, q - 1))
        det.append(f"Ω={Om}: one cycle of {Om}; p={p}: one cycle of {p}")
    R.check("Q1", "on the three Carriers and their Subjects: the orbit of 0 under x ↦ x + 1 returns after exactly q steps and "
            "visits every point; x + 1 ≠ x", ok, "; ".join(det))
    # Q2 every q in [2, 400): the k-th iterate fixes a point iff q | k (k < 3q), every orbit is all of [0, q), no fixed point
    bad = []
    for q in range(2, 400):
        for x in (0, q // 2, q - 1):
            y, ret = x, []
            for k in range(1, 3 * q):
                y = (y + 1) % q
                if y == x: ret.append(k)
            if ret != [q, 2 * q] or sorted(successor_orbit(q, x)) != list(range(q)): bad.append((q, x))
        if any((x + 1) % q == x for x in range(q)): bad.append((q, "fixed point"))
    R.check("Q2", "every q in [2, 400) and x ∈ {0, ⌊q/2⌋, q−1}: C_q^k x = x for 0 < k < 3q exactly at k = q, 2q (by iteration); every "
            "orbit is all of [0, q); no point is fixed", not bad, f"exceptions {bad[:5]}")


# ------------------------------------------------------------------------------------------------------------
# block I: completeness is primality (00:A11)
# for q ≥ 2, every ideal of Z/q holding a nonzero residue holds every residue iff q is prime (Foundation.lean,
# isPrime_iff_complete): forward by the Fermat inverse a^(q−2), backward by the annihilator of a zero divisor.
@R.block("I", BLOCKS["I"])
def block_I():
    """Block I — completeness is primality (EXACT): I1, I2."""
    # I1 the forward construction on the Carriers and the Subjects: a^(q−2) inverts every nonzero a
    ok, det = True, []
    for Om, p in SHELLS[:2]:
        for q in (Om, p):
            ok &= all(a * pow(a, q - 2, q) % q == 1 for a in range(1, q))
        det.append(f"q={Om} and q={p}: a·a^(q−2) = 1 for every a ≠ 0")
    Om = SHELLS[2][0]
    ok &= all(a * pow(a, Om - 2, Om) % Om == 1 for a in range(1, 200001))
    det.append(f"q={Om}: for a < 200 001")
    R.check("I1", "on the Carriers and their Subjects: the Fermat inverse a^(q−2) of every nonzero a, so 1 lies in every ideal holding "
            "a, and with it every residue", ok, "; ".join(det))
    # 00:A11 (p00162)
    bad, det = [], []
    for q in range(2, 260):
        comp, prime, zd = is_complete(q), arith.is_prime(q), zero_divisors(q)
        if not (comp == prime == (not zd)): bad.append(q)
        if not prime:
            a, b = zd[0]
            ann = [x for x in range(q) if x * b % q == 0]                       # the annihilator of b, an ideal holding a
            if not (a in ann and 1 not in ann and principal_ideal(a, q) != list(range(q))): bad.append((q, "annihilator"))
    R.check("I2", "every q in [2, 260): Z/q has no proper nonzero ideal (every residue's ideal holds 1, by search) iff q is prime iff "
            "no zero divisors; for composite q the annihilator of a zero divisor b is a proper ideal holding a ≠ 0", not bad,
            f"258 moduli, {sum(1 for q in range(2, 260) if arith.is_prime(q))} prime; exceptions {bad[:5]}")


# ------------------------------------------------------------------------------------------------------------
# block H: the quarter-turn exists iff p ≡ 1 (mod 4) (00:A12)
# for an odd prime p, x² = −1 is solvable iff p ≡ 1 (mod 4) (Foundation.lean, quarter_turn_iff): backward ħ = a^((p−1)/4)
# with a^((p−1)/2) = −1; forward ħ⁴ = 1 and Fermat leave (p − 1) mod 4 = 0.
@R.block("H", BLOCKS["H"])
def block_H():
    """Block H — the quarter-turn exists iff p ≡ 1 (mod 4) (EXACT): H1, H2."""
    # 00:A12 (p00163)
    primes = _primes(3, SWEEP)
    bad = [p for p in primes if bool(quarter_turns(p)) != (p % 4 == 1)]
    built = [p for p in primes if p % 4 == 1 and quarter_turn(p) ** 2 % p != p - 1]
    R.check("H1", f"every odd prime p < {SWEEP}: x² = −1 has a root (by search) iff p ≡ 1 (mod 4); on p ≡ 1 (mod 4) the generator-free "
            "ħ = a^((p−1)/4) is one", not bad and not built, f"{len(primes)} primes; exceptions {bad + built}")
    # H2 the Carriers and their Subjects: ħ = a^S, ħ² = −1, and the two roots ±ħ
    ok, det = True, []
    for Om, p in SHELLS:
        for q in (Om, p):
            h = quarter_turn(q); a = half_power(q)
            ok &= q % 4 == 1 and pow(a, (q - 1) // 2, q) == q - 1 and h == pow(a, (q - 1) // 4, q) and h * h % q == q - 1
            if q < 10 ** 5: ok &= sorted(quarter_turns(q)) == sorted({h, q - h})
        det.append(f"Ω={Om}: ħ={quarter_turn(Om)}; p={p}: ħ={quarter_turn(p)}")
    R.check("H2", "on the three Carriers and their Subjects (all ≡ 1 mod 4): ħ = a^S with a^(2S) = −1 solves x² = −1, and below 10⁵ the "
            "roots are exactly ±ħ (by search)", ok, "; ".join(det))


# ------------------------------------------------------------------------------------------------------------
# block M: every prime carries a frame (00:A13)
# every prime field has a primitive root, and its powers reach every nonzero residue (Drive.lean, exists_drive): the
# proof's construction is the product over the prime powers qᵉ ∥ p − 1 of a^((p−1)/qᵉ), a the least with a^((p−1)/q) ≠ 1.
@R.block("M", BLOCKS["M"])
def block_M():
    """Block M — every prime carries a frame (EXACT): M1–M3."""
    # 00:A13 (p00164)
    ok, det = True, []
    for Om, p in SHELLS:
        for q in (Om, p):
            g = drive(q)
            n = element_order(g, q)                                          # by iteration
            powers, y = set(), 1
            for _ in range(q - 1):
                powers.add(y); y = y * g % q
            ok &= n == q - 1 and arith.is_primitive_root(g, q) and powers == set(range(1, q))
        det.append(f"Ω={Om}: g={drive(Om)}; p={p}: g={drive(p)}")
    R.check("M1", "on the three Carriers and their Subjects: the drive g built by the proof's construction has order p − 1 (by iteration "
            "and by the factorisation of p − 1), and g⁰, …, g^(p−2) are all p − 1 nonzero residues", ok, "; ".join(det))
    # M2 every prime below SWEEP: the construction gives a primitive root, each factor z_q of order exactly qᵉ
    bad = []
    for p in _primes(2, SWEEP):
        n = p - 1
        for q, e in arith.factorize(n).items():
            a = next(a for a in range(1, p) if pow(a, n // q, p) != 1)
            z = pow(a, n // q ** e, p)
            if not (pow(z, q ** e, p) == 1 and pow(z, q ** (e - 1), p) != 1): bad.append((p, q))
        if arith.order(drive(p), p) != n: bad.append(p)
    R.check("M2", f"every prime p < {SWEEP}: for each qᵉ ∥ p − 1 the factor z_q = a^((p−1)/qᵉ) has order exactly qᵉ, and their product "
            "is a primitive root", not bad, f"{len(_primes(2, SWEEP))} primes; exceptions {bad[:5]}")
    # M3 every prime below 400: the elements of order p − 1, by iteration, number φ(p − 1), the drive among them
    bad = []
    for p in _primes(2, 400):
        prim = [x for x in range(1, p) if element_order(x, p) == p - 1]
        if len(prim) != arith.phi(p - 1) or drive(p) not in prim: bad.append(p)
    R.check("M3", "every prime p < 400: the elements of order p − 1, found by iteration, number φ(p − 1) and include the drive", not bad,
            f"{len(_primes(2, 400))} primes; exceptions {bad}")


if __name__ == "__main__":
    blocks = [a for a in sys.argv[1:] if a in R.blocks]
    if blocks:
        for b in blocks: R.run_block(b)
        sys.exit(0 if R.summary(write=False) else 1)
    sys.exit(0 if R.verify_all() else 1)
