"""master/gravity — a ledger file of the master's block E, gravity: the rows the gravity theme proves (ledger migration,
task LM27, 6 October 2026).

The master's block E is bound by this file (the gravity theme). It binds E6, the horizon count, and E7, the horizon
triple: the table of keys (generated from docs/00-ledger.json by ci/make_ledgers.py), the Lean proofs each key conjoins
(PROOFS), the shells, and the checks, which call the gravity theme (frc/gravity.py). Each check names the rows it decides
or corroborates (LEDGER), under a `# 00:E6 (p00176)` marker on the check that decides the row (PREDICATES). The Lean side
is lean/FrcCore/Theme/Gravity.lean, the key file lean/FrcCore/Keys/Gravity.lean and the certificate
lean/FrcCore/Ledgers/Master/Gravity.lean.

    python3 -m frc.ledgers.master.gravity        every block, the census; exit 1 if a check fails
    python3 -m frc.ledgers.master.gravity W      one block (W or U)

Blocks:  W  the horizon count: the registration sphere, the record, the merger law     EXACT  (00:E6)
         U  the horizon triple: the record on the rate face, the response, Smarr       EXACT  (00:E7)

The notebook frc/ledgers/master/gravity.ipynb runs one row per cell, the cell's id its key (gate G13).
"""
import sys
from fractions import Fraction

from frc import arith
from frc.registry import Registry
from frc.gravity import (squares, conic_points, sphere_points, sphere_brute, record, area, rate_mass, temperature,
                         response, merger_area)

# ---- generated by ci/make_ledgers.py from docs/00-ledger.json; edit the ledger, not this table ----
BLOCK = "E"
KEYS = {"E1": "p00052", "E3": "p00154", "E4": "p00055", "E5": "p00056", "E6": "p00176", "E7": "p00058", "E10": "p00147"}       # every row of the block: its label and its accession key
LEAN = {"E6": "core", "E7": "core"}       # the rows with a Lean declaration: the libraries whose key files prove them
# ---- end of the generated table ----

# The Lean proofs of the rows' keys: the theorems of the themes that each key conjoins (lean/make_keys.py writes the keys
# FRC.Ledger.p<key> from them). The master's block file is the binding's source, as a paper's \lean{} cells are its own.
PROOFS = {
    "E6": ["FRC.Grav.sphere_area", "FRC.Grav.sphere_area_rung", "FRC.Grav.count_identity", "FRC.Grav.merger_area"],
    "E7": ["FRC.Grav.count_identity", "FRC.Grav.record_mass", "FRC.Grav.record_response", "FRC.Grav.temperature_rate",
           "FRC.Grav.smarr"],
}

LEAN_ONLY = ()                  # the rows with a Lean declaration and no python check (gate G12): none

SWEEP = 200                     # the sphere sweep runs over every prime p = 4κ + 1 below it
BRUTE = [5, 13, 17, 29, 37]     # the shells enumerated point by point
IDENT = 10000                   # the identities run over every prime p = 4κ + 1 below it
MERGER = (27811, 1596)          # the merger instance of 21-gravity and 37-sim

LEDGER = {"W1": "00:E6", "W2": "00:E6", "W3": "00:E6", "U1": "00:E7", "U2": "00:E7"}
BLOCKS = {"W": "the horizon count: the registration sphere, the record, the merger law",
          "U": "the horizon triple: the record on the rate face, the response, Smarr"}
PREDICATES = {"00:E6": "W1", "00:E7": "U1"}

R = Registry("00", "gravity", LEDGER, PREDICATES, sources=[__file__])


def _shells(lo, hi):
    return [n for n in range(lo, hi) if n % 4 == 1 and arith.is_prime(n)]


# ------------------------------------------------------------------------------------------------------------
# block W: the horizon count (00:E6)
# the registration sphere x² + y² + z² = κ² has p(p + 1) points, at every nonzero square rung; the record S = κ(p + 1)
# with 4S + 1 = p² and S/A = κ/p; the merger law ΔA = 2 M₁ M₂ on A = M(M + 1) (Gravity.lean: sphere_area,
# sphere_area_rung, count_identity, merger_area).
@R.block("W", BLOCKS["W"])
def block_W():
    """Block W — the horizon count (EXACT): W1–W3."""
    # 00:E6 (p00176)
    bad = []
    for p in _shells(5, SWEEP):
        k = (p - 1) // 4
        r = squares(p)
        ok = sphere_points(p, k * k % p) == area(p)
        ok &= all(sphere_points(p, a) == p * p + p * (r[a] - 1) for a in range(1, p))      # p² + p χ(a), χ(a) = r[a] − 1
        ok &= all(conic_points(p, c) == (p - 1 if c else 2 * p - 1) for c in range(p))
        S, A = record(p), area(p)
        ok &= 4 * S + 1 == p * p and Fraction(S, A) == Fraction(k, p) and 4 * S * p == A * (p - 1)
        if not ok: bad.append(p)
    mbad = [(a, b) for a in range(1, 120) for b in range(1, 120) if merger_area(a, b) != 2 * a * b]
    R.check("W1", f"every prime p = 4κ + 1 below {SWEEP}: the sphere x² + y² + z² = κ² has p(p + 1) points, every rung a ≠ 0 "
            "p² + p χ(a), the conic x² + y² = c has p − 1 points (c ≠ 0) and 2p − 1 (c = 0); the record S = κ(p + 1) with "
            "4S + 1 = p², S/A = κ/p and 4Sp = A(p − 1); the merger law A(M₁ + M₂) − A(M₁) − A(M₂) = 2M₁M₂ on A = M(M + 1) "
            "for all M₁, M₂ < 120", not bad and not mbad,
            f"{len(_shells(5, SWEEP))} shells; exceptions {bad} {mbad[:2]}")
    # W2 a second method: the spheres enumerated point by point
    bad = [p for p in BRUTE if sphere_brute(p, ((p - 1) // 4) ** 2) != area(p)]
    R.check("W2", f"the shells {', '.join(map(str, BRUTE))} enumerated point by point: the sphere at the capacity has p(p + 1) "
            "points (30 at p = 5, the rate 30/125 = 6/25 of 37-sim)", not bad and temperature(5) == Fraction(6, 25),
            f"exceptions {bad}")
    # W3 the record law closes at the coherence horizon: S = (Ω − 1)/4 at Ω = p²; the merger instance
    bad = [p for p in _shells(5, IDENT) if (p * p - 1) % 4 or (p * p - 1) // 4 != record(p)]
    m1, m2 = MERGER
    ok = not bad and merger_area(m1, m2) == 88772712 == 2 * m1 * m2
    R.check("W3", f"every prime p = 4κ + 1 below {IDENT}: at Ω = p² the record S = κ(p + 1) is (Ω − 1)/4; the merger "
            "27 811 + 1 596 → 29 407 gives ΔA = 88 772 712 = 2 · 27 811 · 1 596", ok, f"exceptions {bad}")


# ------------------------------------------------------------------------------------------------------------
# block U: the horizon triple (00:E7)
# S = (A/4)(1 − 1/p) = M(M − 1) on M = (p + 1)/2; dS/dM = p; T = (p + 1)/p², T_resp = 1/p, T = T_resp(1 + 1/p); Smarr
# 2 T_resp S = M(1 − 1/p) and 2 T S = M(1 − 1/p²) (Gravity.lean: count_identity, record_mass, record_response,
# temperature_rate, smarr).
@R.block("U", BLOCKS["U"])
def block_U():
    """Block U — the horizon triple (EXACT): U1–U2."""
    # 00:E7 (p00058)
    bad = []
    for p in _shells(5, IDENT):
        S, A, M, T, Tr = record(p), area(p), rate_mass(p), temperature(p), response(p)
        Sf = lambda m: m * (m - 1)
        ok = Fraction(S) == Fraction(A, 4) * (1 - Fraction(1, p)) and S == M * (M - 1)
        ok &= Fraction(Sf(M + 3) - Sf(M - 3), 6) == p and Sf(M + 1) - Sf(M) == p + 1   # dS/dM = 2M − 1 = p
        ok &= T == Fraction(p + 1, p * p) and Tr == Fraction(1, p) and T == Tr * (1 + Fraction(1, p))
        ok &= 2 * Tr * S == M * (1 - Fraction(1, p)) and 2 * T * S == M * (1 - Fraction(1, p * p))
        if not ok: bad.append(p)
    R.check("U1", f"every prime p = 4κ + 1 below {IDENT}: S = (A/4)(1 − 1/p) = M(M − 1) on M = (p + 1)/2; the central difference "
            "of S(M) is p (dS/dM = p); T = A/p³ = (p + 1)/p², T_resp = 1/p and T = T_resp(1 + 1/p); 2 T_resp S = M(1 − 1/p) "
            "and 2 T S = M(1 − 1/p²), in exact fractions", not bad, f"{len(_shells(5, IDENT))} shells; exceptions {bad}")
    # U2 the Subjects 13, 173, 1373: the values
    det = []
    for p in (13, 173, 1373):
        det.append(f"p={p}: S={record(p)}, M={rate_mass(p)}, T={temperature(p)}")
    ok = record(13) == 42 == rate_mass(13) * (rate_mass(13) - 1) and temperature(13) == Fraction(14, 169)
    R.check("U2", "the Subject 13: S = 3 · 14 = 42 = 7 · 6 on M = 7, T = 14/169, T_resp = 1/13; and the Subjects 173 and 1373",
            ok, "; ".join(det))


if __name__ == "__main__":
    blocks = [a for a in sys.argv[1:] if a in R.blocks]
    if blocks:
        for b in blocks: R.run_block(b)
        sys.exit(0 if R.summary(write=False) else 1)
    sys.exit(0 if R.verify_all() else 1)
