"""
c_boost.py — block C: the finite Lorentz boosts (3:C1–C5)
=========================================================
Section 3 of the paper.  The boosts of Q_ν(t, x) = −ν t² + x² over the shell are Λ(γ, b) = [[γ, b], [νb, γ]]
with γ² − νb² = 1: the norm-one group N¹ of K = F_p(√ν), cyclic of order p + 1 (the non-split torus; 8:D5), with
Λ(z₁)Λ(z₂) = Λ(z₁z₂) (C1); the whole of SO(Q_ν, F_p) in dimension 2, by exhaustion (C2).  The velocity v = −νb/γ is a
shell quantity (γ ≠ 0 always), γ²(ν − v²) = ν, and the velocities compose by v₁₂ = (v₁+v₂)/(1 + v₁v₂/ν) exactly, the
denominator never zero (C3).  The family Λ(u), u = g^{Δm} ∈ F_p^x, has a = (u − u⁻¹)/(2c) outside F_p
for u ≠ ±1: a matrix over K, preserving Q_ν over K where Q_ν is Euclidean — the split torus of order p − 1, the
extension's rotations (C4).  In 1+3 dimensions the x-boosts with O(3, F_p) generate O(Q_ν, F_5) = O_4^−(5), order
31 200 (C5).
"""
import lcommon as lc

def boost(g, b, nu, p):
    return ((g % p, b % p), (nu * b % p, g % p))

def mat_mul(A, B, p):
    n = len(A)
    return tuple(tuple(sum(A[i][k] * B[k][j] for k in range(n)) % p for j in range(n)) for i in range(n))

def preserves(M, coeffs, p):
    n = len(coeffs)
    import itertools
    for v in itertools.product(range(p), repeat=n):
        w = tuple(sum(M[i][j] * v[j] for j in range(n)) % p for i in range(n))
        if lc.Q(coeffs, w, p) != lc.Q(coeffs, v, p): return False
    return True

def closure(gens, p, limit=None):
    """The group generated by gens (tuples of tuples) by breadth-first multiplication."""
    n = len(gens[0]); I = tuple(tuple(int(i == j) for j in range(n)) for i in range(n))
    seen = {I}; frontier = [I]
    while frontier:
        nxt = []
        for A in frontier:
            for G in gens:
                Bm = mat_mul(A, G, p)
                if Bm not in seen:
                    seen.add(Bm); nxt.append(Bm)
                    if limit and len(seen) > limit: return seen
        frontier = nxt
    return seen

def run():
    # C1 the norm-one group: order p + 1, cyclic, Lambda(z) preserves Q_nu, Lambda(z1 z2) = Lambda(z1) Lambda(z2) (3:C2)
    ok = True; det = []
    for p, k in lc.SHELLS:
        nu = lc.nonsquares(p)[0]; K = lc.Ext(p, nu); N1 = K.norm_one()
        ok &= len(N1) == p + 1
        ok &= any(all(K.pow(z, d) != (1, 0) for d in range(1, p + 1)) for z in N1)          # an element of order p+1: cyclic
        coeffs = ((-nu) % p, 1)
        for z in N1:
            ok &= preserves(boost(z[0], z[1], nu, p), coeffs, p)
        for z1 in N1[:8]:
            for z2 in N1:
                z = K.mul(z1, z2)
                ok &= mat_mul(boost(*z1, nu, p), boost(*z2, nu, p), p) == boost(*z, nu, p)
        det.append(f"p={p}: |N^1|={len(N1)}")
    lc.check("C1", "the boosts Lambda(gamma, b), gamma^2 - nu b^2 = 1, form the norm-one cycle of order p+1; each preserves Q_nu; Lambda(z1)Lambda(z2) = Lambda(z1 z2)", ok, "; ".join(det))

    # C2 SO(Q_nu, F_p) in dimension 2 is exactly the boosts: p + 1 matrices for nu nonsquare, p - 1 for nu square (3:C2)
    ok = True; det = []
    for p in (5, 13, 17):
        nu = lc.nonsquares(p)[0]; s = lc.squares(p)[-1]
        for coeff, expect in ((nu, p + 1), (s, p - 1)):
            coeffs = ((-coeff) % p, 1); n = 0; shape = True
            for a in range(p):
                for b in range(p):
                    for c in range(p):
                        for d in range(p):
                            M = ((a, b), (c, d))
                            if (a * d - b * c) % p == 1 and preserves(M, coeffs, p):
                                n += 1; shape &= (d == a and c == coeff * b % p)
            ok &= n == expect and shape
            det.append(f"p={p}, nu={coeff}: |SO|={n}")
    lc.check("C2", "SO(Q_nu, F_p) in 1+1 dimensions has p+1 elements (nu nonsquare, non-split torus), p-1 (nu square, split torus), all of the shape [[g, b], [nu b, g]]", ok, "; ".join(det))

    # C3 velocity: gamma != 0, v = -nu b / gamma in F_p, gamma^2 (nu - v^2) = nu, exact Einstein addition (3:C3)
    ok = True; det = []
    for p, k in lc.SHELLS:
        nu = lc.nonsquares(p)[0]; K = lc.Ext(p, nu); N1 = K.norm_one()
        ok &= all(z[0] != 0 for z in N1)
        vel = {}
        for z in N1:
            g, b = z; v = (-nu * b * pow(g, -1, p)) % p; vel[z] = v
            ok &= (g * g * (nu - v * v)) % p == nu % p
        ok &= len(set(vel.values())) == (p + 1) // 2                                   # v is 2-to-1 (z and -z)
        for z1 in N1:
            for z2 in N1:
                v1, v2 = vel[z1], vel[z2]; z12 = K.mul(z1, z2)
                den = (1 + v1 * v2 * pow(nu, -1, p)) % p
                ok &= den != 0 and vel[z12] == (v1 + v2) * pow(den, -1, p) % p
        det.append(f"p={p}: {(p + 1) // 2} velocities")
    lc.check("C3", "gamma != 0 on every boost; v = -nu b/gamma; gamma^2 (nu - v^2) = nu; v12 = (v1 + v2)/(1 + v1 v2/nu) exactly, denominator never zero", ok, "; ".join(det[:3]))

    # C4 the family Lambda(u), u = g^{Delta m} in F_p^x: entries in K \ F_p, preserves Q_nu over K, the split torus of order p-1 (3:C5)
    ok = True; det = []
    for p in (13, 17):
        nu = lc.nonsquares(p)[0]; K = lc.Ext(p, nu); g = lc.generators(p)[0]; c = (0, 1); c_inv = K.inv(c)
        two_inv = pow(2, -1, p)
        seen = set()
        for dm in range(p - 1):
            u = (pow(g, dm, p), 0); ui = K.inv(u)
            gam = K.mul(K.scalar(two_inv), K.add(u, ui)); a = K.mul(K.mul(K.scalar(two_inv), K.sub(u, ui)), c_inv)
            ok &= gam[1] == 0 and (a[0] == 0) and ((a[1] != 0) == (u[0] not in (1, p - 1)))   # gamma in F_p, a in c.F_p
            ok &= K.sub(K.mul(gam, gam), K.mul(K.scalar(nu), K.mul(a, a))) == (1, 0)          # gamma^2 - nu a^2 = 1 in K
            # Lambda(u) preserves Q_nu over K on a sample of K^2
            for t in K.elements()[:5]:
                for x in K.elements()[7:12]:
                    t2 = K.add(K.mul(gam, t), K.mul(a, x)); x2 = K.add(K.mul(K.scalar(nu), K.mul(a, t)), K.mul(gam, x))
                    q = lambda tt, xx: K.add(K.neg(K.mul(K.scalar(nu), K.mul(tt, tt))), K.mul(xx, xx))
                    ok &= q(t2, x2) == q(t, x)
            seen.add((gam, a))
        ok &= len(seen) == p - 1
        det.append(f"p={p}: {len(seen)} matrices Lambda(u), a in c.F_p, a not in F_p for u != +-1")
    lc.check("C4", "the family Lambda(u), u = g^dm in F_p^x: gamma in F_p but a in c.F_p (not in F_p for u != +-1); preserves Q_nu over K; p-1 matrices, the split torus", ok, "; ".join(det))

    # C5 1+3: the x-boosts with O(3, F_5) generate O(Q_nu, F_5) = O_4^-(5) of order 31200; O(3, F_5) has order 240 (3:C4)
    p = 5; nu = lc.nonsquares(p)[0]; K = lc.Ext(p, nu); N1 = K.norm_one()
    z0 = next(z for z in N1 if all(K.pow(z, d) != (1, 0) for d in range(1, p + 1)))
    Lx = ((z0[0], z0[1], 0, 0), (nu * z0[1] % p, z0[0], 0, 0), (0, 0, 1, 0), (0, 0, 0, 1))
    coeffs = ((-nu) % p, 1, 1, 1)
    def reflection(w):
        qw = lc.Q(coeffs, w, p); qi = pow(qw, -1, p)
        M = []
        for i in range(4):
            row = []
            for j in range(4):
                e = tuple(int(k == j) for k in range(4))
                Bw = sum(a * ei * wi for a, ei, wi in zip(coeffs, e, w)) % p
                row.append((int(i == j) - 2 * Bw * qi * w[i]) % p)
            M.append(tuple(row))
        return tuple(M)
    spatial = [(0, 1, 0, 0), (0, 0, 1, 0), (0, 0, 0, 1), (0, 1, 1, 0), (0, 1, 2, 0), (0, 0, 1, 2), (0, 1, 1, 1)]
    spatial = [w for w in spatial if lc.Q(coeffs, w, p) != 0]
    O3 = closure([reflection(w) for w in spatial], p)
    G = closure([Lx] + [reflection(w) for w in spatial], p)
    ok = len(O3) == 2 * p * (p * p - 1) and len(G) == lc.o_minus_4(p) and all(preserves(M, coeffs, p) for M in list(G)[:200])
    lc.check("C5", "at p = 5 the x-boosts and O(3, F_p) (order 240) generate O(Q_nu, F_p) = O_4^-(5) of order 31200", ok,
             f"|O(3,F_5)|={len(O3)}, generated group {len(G)}")

if __name__ == "__main__":
    run(); lc.summary(write=False)
