"""Builds 3-causality-main.ipynb (the Colab driver of the 3-causality validation package). Run: python3 make_notebook.py"""
import json

NB = "3-causality-main.ipynb"
PKG = "3-causality"
COLAB = f"https://colab.research.google.com/github/gamayos/finite-ring-space/blob/main/src/{PKG}/{NB}"
cells = []
def md(s): cells.append({"cell_type": "markdown", "metadata": {}, "source": s})
def code(s): cells.append({"cell_type": "code", "metadata": {}, "execution_count": None, "outputs": [], "source": s})

md(f"""[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)]({COLAB})

## Euclidean–Lorentzian Dichotomy and Algebraic Causality in Finite Ring Continuum (Akhtman, Entropy 2025, 27, 1098)

**Validation Package.** `finite-ring-space/src/{PKG}` — four block scripts, sixteen exact checks, standard library only,
added with the paper's predicate ledger (Appendix A, 17 September 2026). Each check names the row(s) of the paper's
ledger it witnesses (rows cited as `3:XN`; public copy at `docs/{PKG}/{PKG}-ledger.html`), and the ledger's source
column cites the check ids in return. Block A decides the square classes: no causal square root of a nonsquare, `−c²` a
square for every `c ≠ 0` (`3:B2`), the absorption lemma with its repaired proof (`3:B3`), the class as the datum with
`ν = g` canonical (`3:B1`). Block B decides the signature by counting: `p³ − p² + p` zeros for a nonsquare `ν`
(elliptic, Witt index one — the Lorentzian class) against `p³ + p² − p` (hyperbolic) on the shell (`3:B4`), the
collapse of the dichotomy over `F_{{p²}}` (`3:B5`), the orders of `O₄⁻(p)` and `O₄⁺(p)` by frame counting (`3:B6`), and
the invariant causal classes (`3:B7`). Block C decides the boosts: the norm-one cycle of order `p + 1`, exhausting
`SO(Q_ν, F_p)` in `1+1` dimensions (`3:C2`), the velocities and Einstein's addition law exact (`3:C3`), the printed
`u = g^Δm` boost as the split torus over the extension (`3:C5`), and `O₄⁻(5)` generated by `x`-boosts and `O(3)` (`3:C4`).
Block D is the worked shell `F₁₃` (`3:D1`).

**Kinds** — every check is `EXACT`: integer arithmetic in `F_p` or `F_{{p²}}`, no float behind any claim.

**Run.** Cell by cell, or *Runtime → Run all*; ≈ 30 s. The last cell writes `results.json` and fails loudly if any
check fails.""")

code(f"""# --- environment: clone the package if this notebook is not already running inside it (Colab).
import os
if not os.path.exists("lcommon.py"):
    if not os.path.exists("finite-ring-space"):
        !git clone --filter=blob:none --sparse https://github.com/gamayos/finite-ring-space.git
        os.chdir("finite-ring-space")
        !git sparse-checkout set src/{PKG}
        os.chdir("src/{PKG}")
    else:
        os.chdir("finite-ring-space/src/{PKG}")
print("working directory:", os.path.join(*os.getcwd().split(os.sep)[-3:]))""")

code("""import importlib, lcommon as lc
importlib.reload(lc)         # a fresh registry if the notebook is re-run
lc.RESULTS.clear()""")

md("""## Block A — the square classes and the nonexistence theorem
The two classes on `p ∈ {5, 13, 17, 29, 37, 41}`; `−1`, `c²` and `−c²` squares; no root of a nonsquare; the absorption of a common
class by rescaling (all one-class coefficient tuples at 5, 13, 17), with the step of the printed proof that fails; the drive as the
canonical nonsquare.""")
code("""import a_classes; importlib.reload(a_classes); a_classes.run()""")

md("""## Block B — the signature on the shell and in the extension
The zero counts that decide the type; the extension `F_{p²}` as pairs `a + b√ν` with `ν = c²` and every element of `F_p` a square there;
the isometry groups by frame counting; the null cone and the two non-null classes; the anisotropic and hyperbolic planes.""")
code("""import b_signature; importlib.reload(b_signature); b_signature.run()""")

md("""## Block C — the finite Lorentz boosts
The norm-one cycle, its order `p + 1`, invariance and composition; the exhaustive `SO(Q_ν, F_p)` in `1+1` dimensions; velocities and
the addition law; the printed parametrisation over the extension; the closure at `p = 5`.""")
code("""import c_boost; importlib.reload(c_boost); c_boost.run()""")

md("""## Block D — the worked shell `F₁₃`""")
code("""import d_example; importlib.reload(d_example); d_example.run()""")

md("""## Summary
`results.json` — one record per check (id, ledger rows, script, kind, claim, PASS/FAIL, detail). The site generator reads it to
colour the witnesses on the public ledger page.""")
code("""ok = lc.summary(write=True)
assert ok, "some checks failed — see the FAIL lines above"
print("all checks passed; results.json written")""")

nb = {"cells": cells, "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
      "language_info": {"name": "python"}, "colab": {"provenance": []}}, "nbformat": 4, "nbformat_minor": 5}
with open(NB, "w") as f:
    json.dump(nb, f, indent=1)
print(f"{NB}: {len(cells)} cells")
