"""frc.shell — the shell and its frame (the frame theme; ledger migration, tasks LM16 and LM20, 5 October 2026).

The shell F_p for a prime p = 4κ + 1: its two square classes, its primitive generators (the drives), and the diagonal
quadratic forms and the matrices over it. Exact integers only, the standard library only (gate G09). A helper enters
the theme when the first ledger that uses it migrates (task LM16); the first was 3-causality (task LM20).

    kappa(p)                                   κ with p = 4κ + 1, p prime
    squares, nonsquares, is_square             the classes S = (F_p^×)² and N = F_p^× \\ S; Euler's criterion
    generators(p)                              the primitive roots of F_p^×, ascending
    Q, value_counts, isotropic_count           a diagonal form Σ a_i x_i², its value distribution, its zeros
    orthogonal_order, o_plus_4, o_minus_4      |O(Q)| by orthogonal frames; |O_4^±(q)|
    mat_mul, preserves, closure                matrices over F_p: products, the isometries of Q, the group generated
"""
import itertools

from frc import arith


def kappa(p):
    """κ = (p − 1)/4 for a prime p ≡ 1 (mod 4)."""
    if not (arith.is_prime(p) and p % 4 == 1): raise ValueError(f"kappa: {p} is not a prime 4κ + 1")
    return (p - 1) // 4


def squares(p):
    """The nonzero squares S = (F_p^×)², ascending."""
    return sorted({x * x % p for x in range(1, p)})


def nonsquares(p):
    """The nonsquares N = F_p^× \\ S, ascending."""
    S = set(squares(p))
    return [x for x in range(1, p) if x not in S]


def is_square(x, p):
    """x is a nonzero square mod the odd prime p (Euler's criterion)."""
    return x % p != 0 and pow(x % p, (p - 1) // 2, p) == 1


def generators(p):
    """The primitive generators of F_p^×, ascending."""
    return [g for g in range(2, p) if arith.order(g, p) == p - 1]


def Q(coeffs, v, p):
    """The diagonal form Σ a_i v_i² mod p."""
    return sum(a * x * x for a, x in zip(coeffs, v)) % p


def value_counts(coeffs, p):
    """counts[w] = #{v in F_p^n : Q(v) = w}, by convolving the one-variable distributions (O(n p²))."""
    dist = [1] + [0] * (p - 1)                      # the empty form: Q = 0 once
    for a in coeffs:
        one = [0] * p
        for x in range(p): one[a * x * x % p] += 1
        new = [0] * p
        for u in range(p):
            if dist[u]:
                for w in range(p):
                    if one[w]: new[(u + w) % p] += dist[u] * one[w]
        dist = new
    return dist


def isotropic_count(coeffs, p):
    """#{v : Q(v) = 0}, the zero vector included."""
    return value_counts(coeffs, p)[0]


def orthogonal_order(coeffs, p):
    """|O(Q)| for a diagonal form by frame counting: the ordered orthogonal frames (v_0, …, v_n) with Q(v_i) = a_i,
    ∏_i #{v in <e_i, …, e_n> : Q(v) = a_i} (Witt: the count in the complement depends only on the isometry class of the
    restricted form)."""
    n = 1
    for i, a in enumerate(coeffs):
        n *= value_counts(coeffs[i:], p)[a % p]
    return n


def o_plus_4(q):
    """|O_4^+(q)|, Witt index 2."""
    return 2 * q * q * (q * q - 1) ** 2


def o_minus_4(q):
    """|O_4^-(q)|, Witt index 1."""
    return 2 * q * q * (q ** 4 - 1)


def mat_mul(A, B, p):
    """The product of two square matrices over F_p (tuples of tuples)."""
    n = len(A)
    return tuple(tuple(sum(A[i][k] * B[k][j] for k in range(n)) % p for j in range(n)) for i in range(n))


def preserves(M, coeffs, p):
    """M is an isometry of the diagonal form: Q(Mv) = Q(v) for every v in F_p^n."""
    n = len(coeffs)
    for v in itertools.product(range(p), repeat=n):
        w = tuple(sum(M[i][j] * v[j] for j in range(n)) % p for i in range(n))
        if Q(coeffs, w, p) != Q(coeffs, v, p): return False
    return True


def closure(gens, p, limit=None):
    """The group generated by gens (tuples of tuples) by breadth-first multiplication."""
    n = len(gens[0]); I = tuple(tuple(int(i == j) for j in range(n)) for i in range(n))
    seen = {I}; frontier = [I]
    while frontier:
        nxt = []
        for A in frontier:
            for G in gens:
                Bm = mat_mul(A, G, p)
                if Bm not in seen:
                    seen.add(Bm); nxt.append(Bm)
                    if limit and len(seen) > limit: return seen
        frontier = nxt
    return seen


# ---- the unit-domain lattice (10-dimensions C1, C2, F2, F3; 00:C12; Theme/Domain.lean of the frame theme) ----
# Exponent triples (r, s, j) of L^r T^s Iq^j: the torsion-free lift of the Subject's modular domain group
# D_p = C_p × C_{p−1} (L on the additive meridian chart, T on the drive's phase chart, the flag Iq = T^κ of order four).
def dom(*terms):
    """The product of domains given as triples, or as (triple, exponent) pairs."""
    out = [0, 0, 0]
    for t in terms:
        v, e = (t, 1) if len(t) == 3 else t
        for i in range(3): out[i] += e * v[i]
    return tuple(out)


L, T, FLAG = (1, 0, 0), (0, 1, 0), (0, 0, 1)
SPEED, ACCEL, ENERGY = dom(L, (T, -1)), dom(L, (T, -2)), dom(FLAG, (T, -1))
HBAR = dom(ENERGY, T)                                  # [ħ] = [E][T] = Iq
KB = dom(HBAR, (SPEED, -1))                            # [k_B] = [ħ][c]⁻¹: the Carrier linkage k_B c = −ħ in domains
TEMP = dom(ENERGY, (KB, -1))                           # [Θ] = [E][k_B]⁻¹
MASS = dom(FLAG, (L, -2), T)                           # [m] = Iq L⁻² T (10:F2)
DOMAINS = {"m": MASS, "v": SPEED, "a": ACCEL, "E": ENERGY, "ħ": HBAR, "k_B": KB, "Θ": TEMP,
           "F": dom(MASS, ACCEL), "p": dom(MASS, SPEED), "S": HBAR, "P": dom(ENERGY, (T, -1)),
           "pressure": dom(MASS, ACCEL, (L, -2)), "G": dom(ACCEL, (L, 2), (MASS, -1))}
# the classical M-L-T-Θ exponents of the same quantities (a, b, c, d)
CLASSICAL = {"m": (1, 0, 0, 0), "v": (0, 1, -1, 0), "a": (0, 1, -2, 0), "E": (1, 2, -2, 0), "ħ": (1, 2, -1, 0),
             "k_B": (1, 2, -2, -1), "Θ": (0, 0, 0, 1), "F": (1, 1, -2, 0), "p": (1, 1, -1, 0), "S": (1, 2, -1, 0),
             "P": (1, 2, -3, 0), "pressure": (1, -1, -2, 0), "G": (-1, 3, -2, 0)}


def classical(a, b, c, d):
    """The classical exponent vector M^a L^b T^c Θ^d read in the lift: M ↦ Iq L⁻² T, Θ ↦ L T⁻² (the dictionary of 10:F3)."""
    return dom((MASS, a), (L, b), (T, c), (TEMP, d))


def modular(triple, p, kappa):
    """The image of a lift triple in the modular group D_p = C_p × C_{4κ}: (r mod p, s + jκ mod 4κ)."""
    r, s, j = triple
    return (r % p, (s + j * kappa) % (4 * kappa))
