#!/usr/bin/env python3
"""make_ledgers.py — the generated parts of the ledger files (ledger migration, task LM20, 5 October 2026).

A migrated ledger has a python ledger file, frc/ledgers/p<NN>_<topic>.py, written by hand: its shells and its checks,
which call the themes, each check marked by the predicates it decides (`# 3:B2 (p03006)`). From that file and the
ledger (docs/<paper>/<paper>-ledger.json, field "lean" for the Lean bindings) this tool writes the rest:

  * the table at the head of the ledger file: KEYS (every row's label and accession key) and LEAN (the rows with a
    Lean declaration, and the libraries whose key files prove them);
  * the notebook frc/ledgers/p<NN>_<topic>.ipynb: one cell per predicate with a python check, the cell's id its key, run
    and stored with its outputs; gate G13 executes it again;
  * the Lean certificates lean/FrcCore/Ledgers/P<NN><Topic>.lean and lean/FrcLedger/Ledgers/P<NN><Topic>.lean, where the
    ledger has content in that library: the key files the ledger needs, and one `#print axioms` per key, guarded by the
    message it must print (`#guard_msgs`), taken from the axiom logs; the build fails if a key's axioms change.

A ledger file is migrated when it carries the generated table's two marker lines; the tool leaves the others alone.
Every Lean declaration of a migrated ledger must be a key of the key files (lean/make_keys.py): a certificate imports
key files only (gate G09). Run lean/make_keys.py, lean/make_predicates.py and the axiom checks first.

    python3 ci/make_ledgers.py            write the generated parts, execute the notebooks
    python3 ci/make_ledgers.py --check    exit 1 if a generated part is stale (no execution; gate G12 runs the same check)
"""
import contextlib, importlib, importlib.util, io, json, os, re, sys, traceback
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = "https://finitering.space"
REPO = "https://github.com/gamayos/finite-ring-space"          # the notebooks clone it on Colab until a release serves the framework (LM33)
LIBS = {"FrcCore": ("core", "FRC.Ledger", "FrcCore/axioms.log"), "FrcLedger": ("ml", "FRC.LedgerML", "axioms.log")}
TABLE = re.compile(r"(# ---- generated by ci/make_ledgers\.py[^\n]*\n)(.*?)(# ---- end of the generated table ----\n)", re.S)


def make_predicates():
    spec = importlib.util.spec_from_file_location("make_predicates", ROOT / "lean" / "make_predicates.py")
    m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m); return m


def ledger_files():
    d = ROOT / "frc" / "ledgers"
    return sorted(p for p in d.glob("p*.py")) if d.exists() else []


def lean_name(stem):
    """p03_causality -> P03Causality"""
    num, topic = stem.split("_", 1)
    return num.upper() + "".join(w.capitalize() for w in topic.split("_"))


def bindings(MP, data, paper):
    """label -> {lib: key} for the rows whose ledger cells cite theorems of the library (the rows with a predicate
    declaration, as make_predicates.py writes them); and the rows whose key no key file proves."""
    reg = json.loads((ROOT / "lean" / "predicates.json").read_text(encoding="utf-8"))
    module = (reg.get(paper) or {}).get("module")
    keys = {r["label"]: r.get("key") for b in data["blocks"] for r in b["rows"]}
    out, missing = {}, []
    for lib in LIBS:
        where, kd = MP.declared(lib), MP.keyed(lib)
        for label, cites in (data.get("lean") or {}).items():
            if label.startswith("V") or not keys.get(label): continue
            cs = [x for x in cites if x["module"].split("/")[0] == lib and (lib == "FrcCore" or x["module"] == f"{lib}/{module}")]
            if not any(where.get(x["name"], (None, None))[1] in ("theorem", "lemma") for x in cs): continue
            if keys[label] in kd: out.setdefault(label, {})[lib] = keys[label]
            else: missing.append(f"{lib}: {label} ({keys[label]})")
    return out, missing


def table(paper, data, lean):
    rows = [(r["label"], r["key"]) for b in data["blocks"] for r in b["rows"] if r.get("key")]
    k = ", ".join(f'"{l}": "{key}"' for l, key in rows)
    ln = ", ".join(f'"{l}": "{", ".join(LIBS[lib][0] for lib in LIBS if lib in libs)}"' for l, libs in
                   sorted(lean.items(), key=lambda kv: [x for x, _ in rows].index(kv[0])))
    return (f'PAPER = "{paper}"\n'
            f"KEYS = {{{k}}}       # every row of the ledger: its label and its accession key\n"
            f"LEAN = {{{ln}}}       # the rows with a Lean declaration: the libraries whose key files prove them\n")


def wrap(text, width=110, lead="#"):
    words = " ".join(text.split()).split(" "); lines, cur = [], lead
    for w in words:
        if len(cur) + 1 + len(w) > width: lines.append(cur); cur = lead
        cur += " " + w
    lines.append(cur); return "\n".join(lines)


def boot(stem):
    return ("import os, sys; ROOT = os.environ.get(\"FRC_ROOT\", \"/content/finite-ring-space\")   # the framework: this checkout, or a clone on Colab\n"
            f"if not os.path.isdir(ROOT + \"/frc\"): os.system(f\"git clone -q --depth 1 {REPO} {{ROOT}}\")\n"
            "if ROOT not in sys.path: sys.path.insert(0, ROOT)\n"
            f"from frc.ledgers.{stem} import R\n")


def notebook(stem, L, data):
    paper, num = L.PAPER, data["paper"].split("-")[0]
    rows = [r for b in data["blocks"] for r in b["rows"]]
    witnessed = [r for r in rows if f"{num}:{r['label']}" in L.R.predicates and r.get("key")]
    cells = []
    def md(s, cid): cells.append({"cell_type": "markdown", "id": cid, "metadata": {"id": cid}, "source": s})
    def code(s, cid): cells.append({"cell_type": "code", "id": cid, "metadata": {"id": cid}, "execution_count": None, "outputs": [], "source": s})
    doi = data.get("doi")
    md(f"## {data['title']}" + (f", [doi {doi.split('doi.org/')[-1]}]({doi})" if doi else "") + "\n\n"
       f"Each cell below verifies one predicate of the paper's predicate ledger ([{SITE[8:]}/{paper}/]({SITE}/{paper}/)) on the FRC "
       f"framework: it runs the blocks of the ledger file `frc/ledgers/{stem}.py` whose checks cite the predicate, prints the check "
       "that decides it and lists every record that cites it with its verdict. The cell's id is the predicate's accession key. "
       "Any cell can be run first: its first lines make the framework importable (this checkout, or a clone on Colab).", "header")
    for r in witnessed:
        lab = f"{num}:{r['label']}"
        code(boot(stem) + f"# {lab} ({r['key']}) [{r['tag']}] — the deciding check {L.R.predicates[lab]}\n{wrap(r['predicate'])}\n"
             f"assert R.predicate(\"{lab}\")", r["key"])
    md(f"## Summary\n\nThe cells above are the ledger's python-witnessed predicates. The whole ledger file, check by check, is "
       f"`python3 -m frc.ledgers.{stem}` from the framework's root ({len(L.LEDGER)} checks).", "summary")
    code(boot(stem) + "assert R.verify_all(), \"a check failed\"\nprint(\"all checks pass\")", "run-all")
    return {"cells": cells, "metadata": {"colab": {"provenance": [], "toc_visible": True},
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}, "language_info": {"name": "python"}},
            "nbformat": 4, "nbformat_minor": 5}


def execute(nb, root=ROOT):
    """Run the code cells in one namespace, in order, from the framework's root `root` (FRC_ROOT); store their outputs.
    Returns the ids of the cells that raised. Gate G13 runs it too."""
    env = os.environ.get("FRC_ROOT"); os.environ["FRC_ROOT"] = str(root); cwd = os.getcwd(); os.chdir(root)
    for m in [m for m in sys.modules if m.startswith("frc.ledgers.")]: del sys.modules[m]        # each run imports the ledger afresh
    ns, n, failed = {"__name__": "__main__"}, 0, []
    try:
        for cell in nb["cells"]:
            if cell["cell_type"] != "code": continue
            out, err = io.StringIO(), io.StringIO(); n += 1; error = None
            with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
                try: exec(compile(cell["source"], f"<cell {cell['id']}>", "exec"), ns)
                except Exception: error = traceback.format_exc()
            cell["execution_count"] = n; cell["outputs"] = []
            if out.getvalue(): cell["outputs"].append({"output_type": "stream", "name": "stdout", "text": out.getvalue()})
            if err.getvalue(): cell["outputs"].append({"output_type": "stream", "name": "stderr", "text": err.getvalue()})
            if error:
                failed.append(cell["id"])
                cell["outputs"].append({"output_type": "error", "ename": "Exception", "evalue": error.strip().split("\n")[-1], "traceback": error.split("\n")})
    finally:
        os.chdir(cwd)
        if env is None: os.environ.pop("FRC_ROOT", None)
        else: os.environ["FRC_ROOT"] = env
    return failed


def certificate(lib, stem, paper, data, lean, MP):
    kind, ns, log = LIBS[lib]
    mine = [(label, libs[lib]) for label, libs in lean.items() if lib in libs]
    if not mine: return None
    num = data["paper"].split("-")[0]
    kd = MP.keyed(lib)
    mods = sorted({kd[k] for _, k in mine}, key=lambda m: m)
    axioms = {}
    for line in (ROOT / "lean" / log).read_text(encoding="utf-8").splitlines():
        m = re.match(r"^'(.+?)' ", line)
        if m: axioms[m.group(1)] = line.strip()
    name = lean_name(stem); tier = "no axioms" if lib == "FrcCore" else "the axioms of Mathlib's hierarchy at most"
    out = [f"import {lib}.{m}" for m in mods] + ["", "/-!",
           f"# {lib}.Ledgers.{name} — the certificate of the ledger of {paper}, {'core' if lib == 'FrcCore' else 'Mathlib'} (ledger migration, task LM20)", "",
           f"Generated by `ci/make_ledgers.py` from the ledger (`docs/{paper}/{paper}-ledger.json`) and the key files. One",
           "`#print axioms` per key of the ledger that this library proves, guarded by the message it must print: the build",
           f"fails if a key's axioms change ({tier}). Nothing imports this file; `lake build {lib}.Ledgers.{name}` checks it.",
           "-/", ""]
    seen = set()
    for label, k in mine:
        full = f"{ns}.{k}"
        if full in seen: continue
        seen.add(full)
        if full not in axioms: raise SystemExit(f"{lib}: {full} is not in lean/{log}: run the axiom check first")
        out += [f"-- {num}:{label} ({k})", f"/-- info: {axioms[full]} -/", "#guard_msgs in", f"#print axioms {full}", ""]
    return "\n".join(out)


def run(check):
    """Write (or, with check, compare) the generated parts of every migrated ledger. Returns (stale parts, failed cells,
    problems): a problem is a ledger that cannot be generated (no PAPER, no table, a Lean declaration no key proves).
    Gate G12 calls it with check=True."""
    if str(ROOT) not in sys.path: sys.path.insert(0, str(ROOT))
    MP = make_predicates(); stale, failed, problems = [], [], []
    for f in ledger_files():
        stem = f.stem; text = f.read_text(encoding="utf-8")
        m = re.search(r'^PAPER = "([^"]+)"', text, re.M); t = TABLE.search(text)
        if not t: continue                                         # not migrated yet: the generated table's two marker lines opt a file in
        if not m: problems.append(f"{f.name}: no PAPER"); continue
        paper = m.group(1); data = json.loads((ROOT / "docs" / paper / f"{paper}-ledger.json").read_text(encoding="utf-8"))
        lean, missing = bindings(MP, data, paper)
        if missing: problems.append(f"{stem}: Lean declarations that no key file proves, so the ledger cannot migrate: {', '.join(missing)}"); continue
        new = text[:t.start(2)] + table(paper, data, lean) + text[t.end(2):]
        targets = [(f, new)]
        for lib in LIBS:
            c = certificate(lib, stem, paper, data, lean, MP)
            p = ROOT / "lean" / lib / "Ledgers" / f"{lean_name(stem)}.lean"
            if c is not None: targets.append((p, c))
            elif p.exists(): stale.append(f"{p.relative_to(ROOT)} (no content: move it to _to_delete/)")
        for p, t2 in targets:
            old = p.read_text(encoding="utf-8") if p.exists() else None
            if old == t2: continue
            if check: stale.append(str(p.relative_to(ROOT)))
            else: p.parent.mkdir(parents=True, exist_ok=True); p.write_text(t2, encoding="utf-8"); print(f"{p.relative_to(ROOT)}: written")
        nbp = f.with_suffix(".ipynb")
        sys.modules.pop(f"frc.ledgers.{stem}", None)
        L = importlib.import_module(f"frc.ledgers.{stem}")
        nb = notebook(stem, L, data)
        old = json.loads(nbp.read_text(encoding="utf-8")) if nbp.exists() else None
        if old is not None and [(c["id"], c["source"]) for c in old["cells"]] == [(c["id"], c["source"]) for c in nb["cells"]]: continue
        if check: stale.append(str(nbp.relative_to(ROOT))); continue
        bad = execute(nb); failed += [f"{stem}:{c}" for c in bad]
        nbp.write_text(json.dumps(nb, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
        print(f"{nbp.relative_to(ROOT)}: {sum(1 for c in nb['cells'] if c['cell_type'] == 'code')} code cells executed, {len(bad)} failed")
    return stale, failed, problems


def main():
    stale, failed, problems = run("--check" in sys.argv)
    if problems: sys.exit("; ".join(problems))
    if stale: sys.exit("ledger files stale: " + "; ".join(stale) + " — run ci/make_ledgers.py")
    if failed: sys.exit("notebook cells failed: " + ", ".join(failed))
    print(f"ledger files current: {', '.join(f.stem for f in ledger_files()) or 'none'}")


if __name__ == "__main__":
    main()
