#!/usr/bin/env python3
"""The core for the live editor (no imports, no Mathlib), one self-contained file each:
web/FrcCore.lean — the whole library in dependency order (the FRC-wide copy); web/core/<Module>.lean — one paper's
module with the modules it rests on inlined, ending in a `-- Ledger rows: axioms` block, one `#print axioms` per
row declaration of the module, so the editor computes each row's axioms in front of the reader. --check compares."""
import re, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent
ORDER = ["Nat", "Pigeonhole", "Shell", "Frame", "Orbit", "Sum", "Meridian", "Algebra", "Epi", "Dimensions", "Poly", "Quaternion", "Causality", "Representation", "Reductio", "Geometry", "Complex", "Instances", "Rh", "Entropy", "Gravity", "Dirac"]
PAPERS = ["Algebra", "Geometry", "Causality", "Representation", "Reductio", "Epi", "Dimensions", "Rh", "Entropy", "Gravity", "Dirac"]   # the modules that are a paper's

def src(m): return (ROOT / "FrcCore" / f"{m}.lean").read_text(encoding="utf-8")
def _topo(order):
    """ORDER in dependency order: a module after every module it imports (the listed order otherwise kept)."""
    out, seen = [], set()
    def visit(m):
        if m in seen: return
        seen.add(m)
        for d in re.findall(r"^import FrcCore\.(\w+)", src(m), re.M): visit(d)
        out.append(m)
    for m in order: visit(m)
    return out
ORDER = _topo(ORDER)
def body(m): return "\n".join(l for l in src(m).splitlines() if not l.startswith("import "))
def imports(m): return re.findall(r"^import FrcCore\.(\w+)", src(m), re.M)
def closure(m, seen=None):
    seen = set() if seen is None else seen
    for d in imports(m):
        if d not in seen: seen.add(d); closure(d, seen)
    return seen
def rows(m):
    """The row declarations of a module, fully qualified: a namespace walk (a module may host another paper's rows in a
    `namespace FRC.<Paper>` block at its end, as Quaternion hosts 1-algebra's G5)."""
    stack, out = [], []
    for line in src(m).splitlines():
        mm = re.match(r"^namespace\s+(\S+)", line)
        if mm: stack.append(mm.group(1)); continue
        mm = re.match(r"^end\s+(\S+)", line)
        if mm and stack and stack[-1] == mm.group(1): stack.pop(); continue
        mm = re.match(r"^(?:theorem|def) (row_\w+)", line)
        if mm: out.append(".".join(stack + [mm.group(1)]))
    return out

def whole():
    out = ["/-! FrcCore — the FRC substrate from first principles, one file for the live instance (no Mathlib,\n"
           "no axioms). Generated from FrcCore/*.lean in dependency order (" + ", ".join(ORDER) + ")\n"
           "by make_core_web.py; the modules' own headers follow. Check any declaration with `#print axioms`. -/\n"]
    for m in ORDER: out.append(f"\n/-! inlined: FrcCore/{m}.lean -/\n" + body(m) + "\n")
    return "".join(out)

def paper(m):
    mods = [x for x in ORDER if x in closure(m)]
    out = [f"/-! FrcCore/{m}.lean for the live instance: the core module with the {len(mods)} modules it rests on inlined\n"
           f"({', '.join(mods)}); plain Lean, no Mathlib, no axioms. Generated by make_core_web.py — edit the modules, not this file.\n"
           f"The ledger rows are the declarations `row_<label>` at the end of the module; their axioms are printed below them. -/\n"]
    for x in mods: out.append(f"\n/-! inlined: FrcCore/{x}.lean -/\n" + body(x) + "\n")
    out.append(f"\n/-! FrcCore/{m}.lean -/\n" + body(m) + "\n")
    rs = rows(m)
    if rs: out.append("\n-- Ledger rows: axioms (each row's, computed here)\n" + "".join(f"#print axioms {r}\n" for r in rs))
    return "".join(out)

targets = {ROOT / "web" / "FrcCore.lean": whole()}
(ROOT / "web" / "core").mkdir(parents=True, exist_ok=True)
for m in sorted(set(PAPERS) | {x for x in ORDER if rows(x)}, key=ORDER.index): targets[ROOT / "web" / "core" / f"{m}.lean"] = paper(m)   # every paper's module, and every module hosting row declarations
if "--check" in sys.argv:
    stale = [str(p.relative_to(ROOT)) for p, t in targets.items() if not p.exists() or p.read_text(encoding="utf-8") != t]
    sys.exit(f"stale: {', '.join(stale)} — run make_core_web.py" if stale else 0)
for p, t in targets.items(): p.write_text(t, encoding="utf-8"); print(f"{p.relative_to(ROOT)}: {len(t.splitlines())} lines")
