#!/usr/bin/env python3
"""make_keys.py — the keyed theorems, one Lean declaration per key (ledger migration, task LM19; run from lean/).

A paper's ledger binds each predicate to the Lean declarations that prove it (docs/<pkg>/<pkg>-ledger.json, field
"lean"); make_predicates.py turns each binding into the predicate's declaration `FRC.<Module>.p<key>`. When every
theorem a predicate cites lives in the themes (frc/themes.py), after a moved name is followed to its theme, the key's
proof needs no paper module. This tool then writes the key once, in the theme's key file:

    FrcCore/Keys/<Theme>.lean      theorem FRC.Ledger.p<key>   : <statement> := <the cited theorems, conjoined>
    FrcLedger/Keys/<Theme>.lean    theorem FRC.LedgerML.p<key> : <statement> := ...

The theme is the highest-ranked theme among the modules of the cited theorems; a key file imports exactly those modules,
never another key file nor a paper module (gate G09). make_predicates.py then writes the paper's declaration
`FRC.<Module>.p<key>` as an alias of the key, so every ledger cell and every page resolves as before. A key whose proof
cites a paper module stays in that module until its paper migrates (tasks LM35, LM36).

The statement is the one Lean prints for the conjunction (`#check`, the numerals typed); a key whose printed statement
does not re-elaborate is written as a definition, as make_predicates.py does. Without --typed the statements already in
the key files are kept, so --check needs no Lean run.

    python3 make_keys.py --docs ../docs --typed     # (re)write the key files of both libraries (needs `lake build`)
    python3 make_keys.py --docs ../docs --check     # exit 1 if a key file is stale or a keyable predicate has no key
    python3 make_keys.py --docs ../docs --list      # the keys, their themes and their sources
"""
import argparse, json, re, subprocess, sys, tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT.parent))
from frc import themes as TM                                                    # noqa: E402
import make_predicates as MP                                                     # noqa: E402

NS = {"FrcCore": "FRC.Ledger", "FrcLedger": "FRC.LedgerML"}
HEAD = "-- Keys of the {theme} theme (generated by make_keys.py from the ledgers' Lean bindings; edit the ledgers, not this file)"


def module_of(path, lib):
    return str(path.relative_to(ROOT / lib))[:-5].replace("/", ".")


def theme_of(lib, mod):
    rel = f"lean/{lib}/{mod.replace('.', '/')}.lean"
    for name, t in TM.THEMES.items():
        if rel in t["core"] + t["ml"]: return name, t["rank"], (t["core"] + t["ml"]).index(rel)
    return None


def index(lib):
    """Every declaration of the library: full name -> (module, kind); and the old names that LM17 kept as aliases:
    full name -> the full name of the moved declaration (the first `FRC.` name after the alias's `:=`)."""
    decl, alias = {}, {}
    for f in sorted((ROOT / lib).rglob("*.lean")):
        if "_to_delete" in f.parts: continue
        mod = module_of(f, lib)
        for n, k in MP.kinds(f).items(): decl[n] = (mod, k)
        lines = f.read_text(encoding="utf-8").split("\n"); stack, old = [], False
        for i, l in enumerate(lines):
            if l.startswith("/-! ## Old names"): old = True
            elif l.startswith("-- Ledger predicates of"): old = False
            m = re.match(r"^namespace\s+(\S+)", l)
            if m: stack.append(m.group(1)); continue
            m = re.match(r"^end\s+(\S+)", l)
            if m and stack and stack[-1] == m.group(1): stack.pop(); continue
            m = re.match(r"^(?:@\[reducible\] (?:noncomputable )?def|theorem|lemma) ([^\s:(\[{]+)", l) if old else None
            if m:
                k = i
                while ":=" not in lines[k]: k += 1
                rest = lines[k].split(":=", 1)[1] + "\n" + (lines[k + 1] if k + 1 < len(lines) else "")
                t = re.search(r"@?(FRC\.[\w.'?]+)", rest)
                if t: alias[".".join(stack + [m.group(1)])] = t.group(1)
    return decl, alias


def ledgers(docs):
    """[(pkg, module, data)] for every paper ledger with Lean bindings, and key -> [ledger:label] over all ledgers."""
    out, rows, mrows = [], {}, {}; reg = json.loads((ROOT / "predicates.json").read_text(encoding="utf-8"))
    master = Path(docs) / "00-ledger.json"
    if master.exists():
        for r in json.loads(master.read_text(encoding="utf-8"))["rows"]:
            if r.get("key"): mrows.setdefault(r["key"], []).append(f"00:{r['label']}")
    for f in sorted(Path(docs).glob("*/*-ledger.json"), key=lambda f: int(f.parent.name.split("-")[0])):
        data = json.loads(f.read_text(encoding="utf-8")); pkg = f.parent.name
        mod = (reg.get(pkg) or {}).get("module") or next((Path(m).stem for m, (paper, _) in TM.LEGACY.items() if paper == pkg), None)
        for b in data["blocks"]:
            for r in b["rows"]:
                if r.get("key"): rows.setdefault(r["key"], []).append(f"{data['paper'].split('-')[0]}:{r['label']}")
        if data.get("lean") and mod: out.append((pkg, mod, data))
    for k, v in mrows.items(): rows.setdefault(k, []).extend(v)
    return out, rows


def keyable(docs):
    """lib -> key -> {theme, thms, defs, mods, rows, label, pred, pkg}: the predicates whose cited theorems all live in themes."""
    lds, rows = ledgers(docs); res = {}
    for lib in ("FrcCore", "FrcLedger"):
        decl, alias = index(lib); keys = {}
        for pkg, module, data in lds:
            preds = {r["label"]: r for b in data["blocks"] for r in b["rows"]}
            for label, cites in data["lean"].items():
                if label.startswith("V") or not preds.get(label, {}).get("key"): continue
                cs = [x for x in cites if x["module"].split("/")[0] == lib and (lib == "FrcCore" or x["module"] == f"{lib}/{module}")]
                if not cs: continue
                full = lambda n: n if n.startswith("FRC.") else "FRC." + n
                thms, defs, mods, ok = [], [], [], True
                for x in cs:
                    n = full(x["name"]); kind = decl.get(n, (None, None))[1]
                    t = alias.get(n, n); hit = decl.get(t)
                    if hit is None: ok = False; break
                    th = theme_of(lib, hit[0])
                    if th is None: ok = False; break
                    (thms if kind in ("theorem", "lemma") else defs).append(t); mods.append((th[1], th[2], hit[0], th[0]))
                if not ok or not thms: continue
                key = preds[label]["key"]
                keys[key] = dict(theme=max(mods)[3], thms=thms, defs=defs, mods=sorted({m[2] for m in mods}, key=lambda m: min((x[0], x[1]) for x in mods if x[2] == m)),
                                 rows=rows.get(key, []), label=f"{data['paper'].split('-')[0]}:{label}", pred=preds[label]["predicate"], pkg=pkg)
        res[lib] = keys
    return res


def stated(lib, theme):
    """The statements already written in a key file: key -> statement (the theorem form only)."""
    p = ROOT / lib / "Keys" / f"{theme.capitalize()}.lean"
    if not p.exists(): return {}
    got = dict(re.findall(r"^theorem (p\d{5}) : (.*?) :=\n", p.read_text(encoding="utf-8"), re.M | re.S))
    return {k: " ".join(v.split()) for k, v in got.items()}


def lean_run(src):
    with tempfile.NamedTemporaryFile("w", suffix=".lean", dir=ROOT, delete=False) as f: f.write(src); path = Path(f.name)
    try: r = subprocess.run(["lake", "env", "lean", str(path)], cwd=ROOT, capture_output=True, text=True)
    finally: path.unlink()
    return r.stdout + r.stderr


def typed(lib, keys):
    """key -> statement as Lean prints it for the conjunction of the key's theorems; keys whose statement does not
    re-elaborate are left out (they take the def form)."""
    out = {}
    for explicit in (False, True):
        todo = [k for k in keys if k not in out]
        if not todo: break
        opts = "set_option pp.proofs false\nset_option pp.numericTypes true\n" + ("set_option pp.explicit true\n" if explicit else "")
        src = f"import {lib}\nset_option linter.defProp false\nnamespace FRC.KeyCheck\n" + "".join(
            f"def {k} := {MP.term_of(keys[k]['thms'])}\n" for k in todo) + "end FRC.KeyCheck\n" + opts + "".join(f"#check @FRC.KeyCheck.{k}\n" for k in todo)
        got = {}
        for e in re.split(r"\n(?=@?FRC\.KeyCheck\.p\d{5})", lean_run(src).strip()):
            m = re.match(r"@?FRC\.KeyCheck\.(p\d{5}) : (.*)", e, re.S)
            if m: got[m.group(1)] = re.sub(r"\[inst(?:_\d+)? : ", "[", " ".join(m.group(2).split()))
        src = f"import {lib}\nset_option linter.unusedVariables false\nnamespace FRC.KeyCheck2\n" + "".join(
            f"theorem {k} : {t} := {MP.term_of(keys[k]['thms'])}\n" for k, t in got.items()) + "end FRC.KeyCheck2\n"
        lines = src.split("\n"); bad = set()
        for m in re.finditer(r":(\d+):\d+: error", lean_run(src)):
            mm = re.match(r"theorem (p\d{5})", lines[int(m.group(1)) - 1])
            if mm: bad.add(mm.group(1))
        out.update({k: t for k, t in got.items() if k not in bad})
    return out


def key_file(lib, theme, keys, statements):
    """The text of Keys/<Theme>.lean."""
    mine = sorted(k for k, v in keys.items() if v["theme"] == theme)
    mods = []
    for k in mine:
        for m in keys[k]["mods"]:
            if m not in mods: mods.append(m)
    mods.sort(key=lambda m: (theme_of(lib, m)[1], theme_of(lib, m)[2]))
    ns = NS[lib]; tier = "no axioms (`check_core_axioms.py`)" if lib == "FrcCore" else "the axioms of Mathlib's hierarchy at most (`check_axioms.py`)"
    out = [f"import {lib}.{m}" for m in mods] + ["", "/-!",
           f"# {lib}.Keys.{theme.capitalize()} — the keyed theorems of the {theme} theme (ledger migration, task LM19)", "",
           f"One declaration per key, `{ns}.p<key>`, generated by `make_keys.py` from the ledgers' Lean bindings: the theorem",
           "that every row carrying the key asserts, proved from the themes alone. The paper's module keeps its declaration",
           f"`FRC.<Module>.p<key>` as an alias. Every declaration has {tier}.", "-/", "",
           f"namespace {ns}", "", HEAD.format(theme=theme)]
    for k in mine:
        v = keys[k]; note = f" Cited definitions (not proofs): {', '.join(v['defs'])}." if v["defs"] else ""
        doc = f"/-- {k} — {', '.join(v['rows'])}. {MP.doc_text(v['pred'])}{note} -/"
        if k in statements: out.append(f"{doc}\ntheorem {k} : {statements[k]} :=\n  {MP.term_of(v['thms'])}")
        else: out.append(f"set_option linter.defProp false in\n{doc}\ndef {k} := {MP.term_of(v['thms'])}")
    out += [MP.END.replace("ledger predicates", "keys"), "", f"end {ns}", ""]
    return "\n".join(out)


def root(lib, themes):
    """The library's root module with one import per key file, after its theme imports, in rank order."""
    p = ROOT / f"{lib}.lean"; lines = [l for l in p.read_text(encoding="utf-8").split("\n") if not l.startswith(f"import {lib}.Keys.")]
    k = max(i for i, l in enumerate(lines) if l.startswith(f"import {lib}.Theme."))
    rank = {n: (t["rank"], n) for n, t in TM.THEMES.items()}
    lines[k + 1:k + 1] = [f"import {lib}.Keys.{t.capitalize()}" for t in sorted(themes, key=rank.get)]
    return p, "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--docs", required=True); ap.add_argument("--typed", action="store_true")
    ap.add_argument("--check", action="store_true"); ap.add_argument("--list", action="store_true")
    a = ap.parse_args()
    K = keyable(a.docs); stale = []
    for lib, keys in K.items():
        if a.list:
            for k, v in sorted(keys.items()): print(f"{lib:9s} {k} {v['label']:8s} {v['theme']:10s} {' '.join(v['thms'])}")
            continue
        themes = sorted({v["theme"] for v in keys.values()})
        d = ROOT / lib / "Keys"
        for gone in sorted({p.stem.lower() for p in d.glob("*.lean")} - set(themes)) if d.exists() else []:
            stale.append(f"{lib}/Keys/{gone.capitalize()}.lean (no key left: move it to _to_delete/)")
        st = typed(lib, keys) if a.typed else {}
        targets = [(d / f"{th.capitalize()}.lean", key_file(lib, th, keys, st if a.typed else stated(lib, th))) for th in themes]
        targets.append(root(lib, themes))
        for p, text in targets:
            old = p.read_text(encoding="utf-8") if p.exists() else None; rel = p.relative_to(ROOT)
            if old == text: print(f"{rel}: current") if not a.check else None
            elif a.check: stale.append(str(rel))
            else:
                p.parent.mkdir(exist_ok=True); p.write_text(text, encoding="utf-8")
                n = sum(1 for v in keys.values() if v["theme"] == p.stem.lower()) if p.parent == d else None
                print(f"{rel}: " + (f"{n} keys written" if n is not None else "key imports written"))
    if a.check:
        if stale: sys.exit("keys stale: " + "; ".join(stale) + " — run make_keys.py")
        print("keys current: " + ", ".join(f"{lib} {len(k)}" for lib, k in K.items()))


if __name__ == "__main__":
    main()
