#!/usr/bin/env python3
"""make_rows.py — one Lean declaration per ledger row (run from lean/, the lake package root).

For a paper's module the site's ledger JSON (docs/<pkg>/<pkg>-ledger.json, field "lean") binds each row to the
declarations that prove it. This writes, in each library that carries such declarations for the module, a section

    -- Ledger rows (generated by make_rows.py from docs/<pkg>/<pkg>-ledger.json; edit the ledger, not this section)
    /-- 10:C2 — <the row's text> -/
    def row_C2 := And.intro FRC.Dimensions.Dom.mul_inv …
    -- end ledger rows

before the module's closing `end FRC.<Module>`, replacing an earlier section. A row with one cited theorem is an alias;
with several, the conjunction (`And.intro`, nested); a cited definition is not a proof and is left out of the term and
named in the docstring. Written first as `def row_X := term` (Lean infers the statement from the term); with `--typed`
the statement is then read back from the compiled module (`#check`, the numerals typed) and each row is rewritten as
`theorem row_X : <statement> := term`, so the source states what it proves — a row whose printed statement does not
re-elaborate keeps the `def` form (the explicit form `pp.explicit` is tried in between). `#print axioms` reads the row's
axioms off either form. V rows are not rows of content and get no declaration. The executable web copies (make_web.py, make_core_web.py) append `#print axioms` for every row declaration.

    python3 make_rows.py --module Dimensions --json ../docs/10-dimensions/10-dimensions-ledger.json
    python3 make_rows.py --module Dimensions --json … --typed      # then restate as theorems (needs the library built: lake build)
    python3 make_rows.py --module Dimensions --json … --check      # exit 1 if a library's section is stale
"""
import argparse, json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
LIBS = ("FrcCore", "FrcLedger")
DECL = re.compile(r"^(?:@\[[^\]]*\]\s*)?(?:noncomputable\s+|protected\s+|private\s+)*(theorem|lemma|def|abbrev|instance|structure|inductive)\s+([A-Za-z_][A-Za-z0-9_'.]*)")
BEGIN = "-- Ledger rows (generated by make_rows.py"
END = "-- end ledger rows"

def kinds(path):
    """fully qualified name -> kind, namespace-aware (the site's reader, lean_module, uses the same walk)."""
    stack, out = [], {}
    for line in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^namespace\s+(\S+)", line)
        if m: stack.append(m.group(1)); continue
        m = re.match(r"^end\s+(\S+)", line)
        if m and stack and stack[-1] == m.group(1): stack.pop(); continue
        m = DECL.match(line)
        if m: out[".".join(stack + [m.group(2)])] = m.group(1)
    return out

def doc_text(pred):
    """The row's text for the docstring: one line, TeX kept, the comment closer made safe."""
    return " ".join(pred.split()).replace("-/", "- /")

def term_of(thms):
    ts = ["@" + t for t in thms]                          # the explicit form: no implicit or instance argument is elaborated
    return ts[0] if len(ts) == 1 else "".join(f"And.intro {t} (" for t in ts[:-1]) + ts[-1] + ")" * (len(ts) - 1)

def section(rows, lib, module, pkg, stated=None):
    """stated: row name -> statement text for the theorem form; rows absent from it keep the def form."""
    lines = [f"{BEGIN} from docs/{pkg}/{pkg}-ledger.json; edit the ledger, not this section)"]
    for label, pred, thms, defs in rows:
        note = f" Cited definitions (not proofs): {', '.join(defs)}." if defs else ""
        name = "row_" + label.split(":")[1]; term = term_of(thms); doc = f"/-- {label} — {doc_text(pred)}{note} -/"
        if stated and name in stated:
            lines.append(f"{doc}\ntheorem {name} : {stated[name]} :=\n  {term}")
        else:
            lines.append(f"set_option linter.defProp false in\n{doc}\ndef {name} := {term}")
    lines.append(END)
    return "\n".join(lines) + "\n"

def statements(lib, module, names, explicit=False):
    """The statements of the row declarations as Lean prints them (`#check`), one per row, numerals typed."""
    import subprocess, tempfile
    opts = "set_option pp.proofs false\nset_option pp.numericTypes true\n" + ("set_option pp.explicit true\n" if explicit else "")
    src = f"import {lib}.{module}\n{opts}" + "".join(f"#check @FRC.{module}.{n}\n" for n in names)
    with tempfile.NamedTemporaryFile("w", suffix=".lean", dir=ROOT, delete=False) as f: f.write(src); path = Path(f.name)
    try: out = subprocess.run(["lake", "env", "lean", str(path)], cwd=ROOT, capture_output=True, text=True).stdout
    finally: path.unlink()
    got = {}
    for e in re.split(r"\n(?=@?FRC\.%s\.row_)" % module, out.strip()):
        m = re.match(r"@?FRC\.%s\.(row_\w+) : (.*)" % module, e, re.S)
        if m: got[m.group(1)] = re.sub(r"\[inst(?:_\d+)? : ", "[", " ".join(m.group(2).split()))
    return got

def compiles(lib, module, rows, stated):
    """Which rows of `stated` re-elaborate as theorems: a scratch file in a side namespace, one theorem per row."""
    import subprocess, tempfile
    names = {"row_" + r[0].split(":")[1]: r for r in rows}
    src = f"import {lib}.{module}\nset_option linter.unusedVariables false\nnamespace FRC.{module}.RowCheck\n" + "".join(
        f"theorem {n} : {t} := {term_of(names[n][2])}\n" for n, t in stated.items()) + f"end FRC.{module}.RowCheck\n"
    with tempfile.NamedTemporaryFile("w", suffix=".lean", dir=ROOT, delete=False) as f: f.write(src); path = Path(f.name)
    try: res = subprocess.run(["lake", "env", "lean", str(path)], cwd=ROOT, capture_output=True, text=True)
    finally: path.unlink()
    lines = src.split("\n"); bad = set()
    for m in re.finditer(r":(\d+):\d+: error", res.stdout + res.stderr):
        l = lines[int(m.group(1)) - 1]; mm = re.match(r"theorem (row_\w+)", l)
        if mm: bad.add(mm.group(1))
    return {n: t for n, t in stated.items() if n not in bad}

def splice(path, block, module):
    src = path.read_text(encoding="utf-8")
    closer = f"\nend FRC.{module}\n"
    if BEGIN in src:
        i, j = src.index(BEGIN), src.index(END) + len(END) + 1
        new = src[:i] + block + src[j:]
    else:
        k = src.rindex(closer)
        new = src[:k] + "\n" + block + src[k:]
    return src, new

def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--module", required=True); ap.add_argument("--json", required=True); ap.add_argument("--check", action="store_true"); ap.add_argument("--typed", action="store_true")
    a = ap.parse_args()
    data = json.loads(Path(a.json).read_text(encoding="utf-8")); pkg = Path(a.json).stem.replace("-ledger", "")
    paper_no = data["paper"].split("-")[0]
    preds = {r["label"]: r["predicate"] for b in data["blocks"] for r in b["rows"]}
    stale = []
    for lib in LIBS:
        path = ROOT / lib / f"{a.module}.lean"
        if not path.exists(): continue
        k = kinds(path); rows = []
        for label in [r["label"] for b in data["blocks"] for r in b["rows"]]:
            if label.startswith("V"): continue
            cites = [x["name"] for x in data["lean"].get(label, []) if x["module"] == f"{lib}/{a.module}"]
            if not cites: continue
            thms = [n for n in cites if k.get(n) in ("theorem", "lemma")]
            defs = [n for n in cites if k.get(n) not in ("theorem", "lemma")]
            if not thms: print(f"{lib}: {paper_no}:{label} cites only definitions ({', '.join(defs)}) — no row declaration"); continue
            rows.append((f"{paper_no}:{label}", preds[label], thms, defs))
        if not rows: continue
        stated = None
        if a.typed:
            names = ["row_" + r[0].split(":")[1] for r in rows]
            got = statements(lib, a.module, names); ok = compiles(lib, a.module, rows, got)
            rest = [n for n in names if n not in ok]
            if rest:
                got2 = statements(lib, a.module, rest, explicit=True); ok.update(compiles(lib, a.module, rows, got2))
            stated = ok; left = [n for n in names if n not in ok]
            print(f"{lib}/{a.module}.lean: {len(ok)} rows stated as theorems" + (f"; def form kept for {', '.join(left)}" if left else ""))
        block = section(rows, lib, a.module, pkg, stated)
        old, new = splice(path, block, a.module)
        if a.check:
            if old != new: stale.append(f"{lib}/{a.module}.lean")
        elif old != new:
            path.write_text(new, encoding="utf-8"); print(f"{lib}/{a.module}.lean: {len(rows)} row declarations written")
        else: print(f"{lib}/{a.module}.lean: {len(rows)} row declarations, current")
    if a.check and stale: sys.exit("ledger rows stale in: " + ", ".join(stale) + " — run make_rows.py")

if __name__ == "__main__":
    main()
