#!/usr/bin/env python3
"""make_predicates.py — one Lean declaration per ledger predicate (run from lean/, the lake package root).

For a paper's module the site's ledger JSON (docs/<pkg>/<pkg>-ledger.json, field "lean") binds each predicate to the
declarations that prove it. This writes, in each library that carries such declarations for the module, a section

    -- Ledger predicates of 10-dimensions (generated by make_predicates.py from docs/10-dimensions/10-dimensions-ledger.json; edit the ledger, not this section)
    /-- 10:C2 (p10012) — <the predicate's text> -/
    def p10012 := And.intro FRC.Dimensions.Dom.mul_inv …
    -- end ledger predicates

before the module's closing `end FRC.<Module>` — or, where the file's own namespaces do not close there, appended at its end
inside `namespace FRC.<Module> … end FRC.<Module>` — replacing an earlier section. In the core a predicate may cite declarations of
several modules (1-algebra cites Frame, Poly, Instances, Quaternion); the predicate is then hosted by the paper's module when every
cited module can be imported there without a cycle (the imports are added), else by the cited module that imports the
others (G5 of 1-algebra lives in Quaternion, which imports Algebra); the site links the declaration where it lives.
The declaration is named by the predicate's accession key (p10012; the label in its docstring). A predicate with one cited theorem is an alias;
with several, the conjunction (`And.intro`, nested); a cited definition is not a proof and is left out of the term and
named in the docstring. Written first as `def pNNNNN := term` (Lean infers the statement from the term); with `--typed`
the statement is then read back from the compiled module (`#check`, the numerals typed) and each predicate is rewritten as
`theorem pNNNNN : <statement> := term`, so the source states what it proves — a predicate whose printed statement does not
re-elaborate keeps the `def` form (the explicit form `pp.explicit` is tried in between). `#print axioms` reads the predicate's
axioms off either form. V rows are not predicates and get no declaration. The executable web copies (make_web.py, make_core_web.py) append `#print axioms` for every predicate declaration.

    python3 make_predicates.py --module Dimensions --json ../docs/10-dimensions/10-dimensions-ledger.json
    python3 make_predicates.py --module Dimensions --json … --typed      # then restate as theorems (needs the library built: lake build)
    python3 make_predicates.py --module Dimensions --json … --check      # exit 1 if a library's section is stale
"""
import argparse, json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
LIBS = ("FrcCore", "FrcLedger")
DECL = re.compile(r"^(?:@\[[^\]]*\]\s*)?(?:noncomputable\s+|protected\s+|private\s+)*(theorem|lemma|def|abbrev|instance|structure|inductive)\s+([A-Za-z_][A-Za-z0-9_'.]*)")
END = "-- end ledger predicates"                    # the section opens "-- Ledger predicates of <pkg> (generated …" and closes here

def imports_of(lib, mod):
    return re.findall(r"^import %s\.(\w+)" % lib, (ROOT / lib / f"{mod}.lean").read_text(encoding="utf-8"), re.M)

def closure(lib, mod, seen=None):
    seen = set() if seen is None else seen
    for d in imports_of(lib, mod):
        if d not in seen and (ROOT / lib / f"{d}.lean").exists(): seen.add(d); closure(lib, d, seen)
    return seen

def host_of(lib, module, cited_mods):
    """The module that hosts a predicate's declaration: the paper's module when no cited module reaches it by imports (the missing
    imports are added there), else the cited module whose closure contains every other cited module and the paper's."""
    if all(m == module or module not in closure(lib, m) for m in cited_mods): return module
    for m in cited_mods:
        if all(x == m or x in closure(lib, m) for x in cited_mods | {module}): return m
    return None

def add_imports(lib, host, needed):
    path = ROOT / lib / f"{host}.lean"; src = path.read_text(encoding="utf-8"); have = set(imports_of(lib, host)) | closure(lib, host)
    new = [m for m in sorted(needed) if m != host and m not in have]
    if not new: return []
    lines = src.split("\n"); k = max((i for i, l in enumerate(lines) if l.startswith("import ")), default=-1)
    for m in new: k += 1; lines.insert(k, f"import {lib}.{m}")
    path.write_text("\n".join(lines), encoding="utf-8"); return new

def kinds(path):
    """fully qualified name -> kind, namespace-aware (the site's reader, lean_module, uses the same walk)."""
    stack, out = [], {}
    for line in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^namespace\s+(\S+)", line)
        if m: stack.append(m.group(1)); continue
        m = re.match(r"^end\s+(\S+)", line)
        if m and stack and stack[-1] == m.group(1): stack.pop(); continue
        m = DECL.match(line)
        if m: out[".".join(stack + [m.group(2)])] = m.group(1)
    return out

def doc_text(pred):
    """The predicate's text for the docstring: one line, TeX kept, the comment closer made safe."""
    return " ".join(pred.split()).replace("-/", "- /")

def term_of(thms):
    ts = ["@" + t for t in thms]                          # the explicit form: no implicit or instance argument is elaborated
    return ts[0] if len(ts) == 1 else "".join(f"And.intro {t} (" for t in ts[:-1]) + ts[-1] + ")" * (len(ts) - 1)

def section(rows, lib, module, pkg, stated=None):
    """stated: declaration name -> statement text for the theorem form; predicates absent from it keep the def form."""
    lines = [f"-- Ledger predicates of {pkg} (generated by make_predicates.py from docs/{pkg}/{pkg}-ledger.json; edit the ledger, not this section)"]
    for label, pred, thms, defs, key in rows:
        note = f" Cited definitions (not proofs): {', '.join(defs)}." if defs else ""
        name = key; term = term_of(thms); doc = f"/-- {label} ({key}) — {doc_text(pred)}{note} -/"
        if stated and name in stated:
            lines.append(f"{doc}\ntheorem {name} : {stated[name]} :=\n  {term}")
        else:
            lines.append(f"set_option linter.defProp false in\n{doc}\ndef {name} := {term}")
    lines.append(END)
    return "\n".join(lines) + "\n"

def statements(lib, host, names, module, explicit=False):
    """The statements of the predicate declarations as Lean prints them (`#check`), one per predicate, numerals typed; `host` is the module
    that holds them, `module` the paper's (their namespace)."""
    import subprocess, tempfile
    opts = "set_option pp.proofs false\nset_option pp.numericTypes true\n" + ("set_option pp.explicit true\n" if explicit else "")
    src = f"import {lib}.{host}\n{opts}" + "".join(f"#check @FRC.{module}.{n}\n" for n in names)
    with tempfile.NamedTemporaryFile("w", suffix=".lean", dir=ROOT, delete=False) as f: f.write(src); path = Path(f.name)
    try: out = subprocess.run(["lake", "env", "lean", str(path)], cwd=ROOT, capture_output=True, text=True).stdout
    finally: path.unlink()
    got = {}
    for e in re.split(r"\n(?=@?FRC\.%s\.p\d{5})" % module, out.strip()):
        m = re.match(r"@?FRC\.%s\.(p\d{5}) : (.*)" % module, e, re.S)
        if m: got[m.group(1)] = re.sub(r"\[inst(?:_\d+)? : ", "[", " ".join(m.group(2).split()))
    return got

def compiles(lib, host, rows, stated, module):
    """Which predicates of `stated` re-elaborate as theorems: a scratch file in a side namespace, one theorem per predicate."""
    import subprocess, tempfile
    names = {r[4]: r for r in rows}
    src = f"import {lib}.{host}\nset_option linter.unusedVariables false\nnamespace FRC.{module}.PredicateCheck\n" + "".join(
        f"theorem {n} : {t} := {term_of(names[n][2])}\n" for n, t in stated.items()) + f"end FRC.{module}.PredicateCheck\n"
    with tempfile.NamedTemporaryFile("w", suffix=".lean", dir=ROOT, delete=False) as f: f.write(src); path = Path(f.name)
    try: res = subprocess.run(["lake", "env", "lean", str(path)], cwd=ROOT, capture_output=True, text=True)
    finally: path.unlink()
    lines = src.split("\n"); bad = set()
    for m in re.finditer(r":(\d+):\d+: error", res.stdout + res.stderr):
        l = lines[int(m.group(1)) - 1]; mm = re.match(r"theorem (p\d{5})", l)
        if mm: bad.add(mm.group(1))
    return {n: t for n, t in stated.items() if n not in bad}

def existing_statements(path, pkg):
    """The statements of the predicates already stated as theorems in the file's section of this paper (declaration name ->
    statement), so that a run without --typed does not demote them to the def form."""
    src = path.read_text(encoding="utf-8"); head = f"-- Ledger predicates of {pkg} ("
    i = src.find(head)
    if i < 0: return None
    sec = src[i:src.index(END, i)]
    got = dict(re.findall(r"^theorem (p\d{5}) : (.*?) :=\n", sec, re.M | re.S))
    return {k: " ".join(v.split()) for k, v in got.items()} or None

def splice(path, block, module, pkg):
    """The section replaces its earlier version (the one of this paper: `-- Ledger predicates of <pkg>`) or goes before
    `end FRC.<module>`; a file whose namespaces do not close there gets the block wrapped in `namespace FRC.<module> … end` at
    its end."""
    src = path.read_text(encoding="utf-8")
    closer = f"\nend FRC.{module}\n"
    head = f"-- Ledger predicates of {pkg} ("
    mine = [m.start() for m in re.finditer(re.escape(head), src)]
    if mine:
        i = mine[0]; j = src.index(END, i) + len(END) + 1
        wrapped = src[i - len(f"namespace FRC.{module}\n"):i] == f"namespace FRC.{module}\n" and src[j:].startswith(f"end FRC.{module}\n")
        if wrapped: i -= len(f"namespace FRC.{module}\n"); j += len(f"end FRC.{module}\n"); block = f"namespace FRC.{module}\n{block}end FRC.{module}\n"
        new = src[:i] + block + src[j:]
    elif closer in src:
        k = src.rindex(closer); new = src[:k] + "\n" + block + src[k:]
    else:
        new = src.rstrip("\n") + f"\n\nnamespace FRC.{module}\n{block}end FRC.{module}\n"
    return src, new

def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--module", required=True); ap.add_argument("--json", required=True); ap.add_argument("--check", action="store_true"); ap.add_argument("--typed", action="store_true")
    a = ap.parse_args()
    data = json.loads(Path(a.json).read_text(encoding="utf-8")); pkg = Path(a.json).stem.replace("-ledger", "")
    paper_no = data["paper"].split("-")[0]
    preds = {r["label"]: r["predicate"] for b in data["blocks"] for r in b["rows"]}; keys = {r["label"]: r["key"] for b in data["blocks"] for r in b["rows"]}
    stale = []; hosts = {}                                            # library -> predicate -> the module hosting its declaration
    for lib in LIBS:
        path = ROOT / lib / f"{a.module}.lean"
        if not path.exists(): continue
        by_host = {}                                                   # host module -> predicates (the paper's module, or a cited one that imports it)
        for label in [r["label"] for b in data["blocks"] for r in b["rows"]]:
            if label.startswith("V"): continue
            cites = [x for x in data["lean"].get(label, []) if x["module"].split("/")[0] == lib and (lib == "FrcCore" or x["module"] == f"{lib}/{a.module}")]
            if not cites: continue
            if not keys.get(label): print(f"{lib}: {paper_no}:{label} has no accession key — no declaration (site_build.py --assign-keys)"); continue
            mods = {x["module"].split("/")[1] for x in cites}
            kmap = {}
            for m in mods: kmap.update(kinds(ROOT / lib / f"{m}.lean"))
            thms = [x["name"] for x in cites if kmap.get(x["name"]) in ("theorem", "lemma")]
            defs = [x["name"] for x in cites if kmap.get(x["name"]) not in ("theorem", "lemma")]
            if not thms: print(f"{lib}: {paper_no}:{label} cites only definitions ({', '.join(defs)}) — no predicate declaration"); continue
            host = host_of(lib, a.module, mods)
            if host is None: print(f"{lib}: {paper_no}:{label} cites {', '.join(sorted(mods))}, no module can host the predicate — skipped"); continue
            by_host.setdefault(host, []).append((f"{paper_no}:{label}", preds[label], thms, defs, keys[label], mods))
        for host, rows in by_host.items():
            hpath = ROOT / lib / f"{host}.lean"
            needed = set().union(*(r[5] for r in rows))
            if not a.check:
                added = add_imports(lib, host, needed)
                if added: print(f"{lib}/{host}.lean: imports {', '.join(added)} added")
            rows = [r[:5] for r in rows]
            stated = existing_statements(hpath, pkg)                   # without --typed the theorem forms already in the file are kept
            if a.typed:
                names = [r[4] for r in rows]
                got = statements(lib, host, names, a.module); ok = compiles(lib, host, rows, got, a.module)
                rest = [n for n in names if n not in ok]
                if rest:
                    got2 = statements(lib, host, rest, a.module, explicit=True); ok.update(compiles(lib, host, rows, got2, a.module))
                stated = ok; left = [n for n in names if n not in ok]
                print(f"{lib}/{host}.lean: {len(ok)} predicates stated as theorems" + (f"; def form kept for {', '.join(left)}" if left else ""))
            hosts.setdefault(lib, {}).update({r[0]: host for r in rows})
            block = section(rows, lib, a.module, pkg, stated)
            old, new = splice(hpath, block, a.module, pkg)
            if a.check:
                if old != new: stale.append(f"{lib}/{host}.lean")
            elif old != new:
                hpath.write_text(new, encoding="utf-8"); print(f"{lib}/{host}.lean: {len(rows)} predicate declarations of {pkg} written")
            else: print(f"{lib}/{host}.lean: {len(rows)} predicate declarations of {pkg}, current")
    # lean/predicates.json: where each predicate's declaration lives, per library, by label (the paper's ledger tool reads it for \leanwitin)
    rj = ROOT / "predicates.json"; reg = json.loads(rj.read_text(encoding="utf-8")) if rj.exists() else {}
    entry = {"module": a.module, **{lib: {r: h for r, h in sorted(hs.items())} for lib, hs in hosts.items()}}
    if reg.get(pkg) != entry:
        if a.check: stale.append("predicates.json")
        else: reg[pkg] = entry; rj.write_text(json.dumps(reg, indent=1, ensure_ascii=False) + "\n", encoding="utf-8"); print(f"predicates.json: {pkg} written")
    if a.check and stale: sys.exit("ledger predicates stale in: " + ", ".join(stale) + " — run make_predicates.py")

if __name__ == "__main__":
    main()
