#!/usr/bin/env python3
"""make_web.py — self-contained copies of the ledger modules for the Lean web editor.

The web editor (live.lean-lang.org) takes one file importing only Mathlib.  For each module
FrcLedger/<M>.lean this writes web/<M>.lean: the module with every `import FrcLedger.X` replaced by the
body of X (recursively, each module once, in dependency order).  Module bodies are self-contained
(their own `namespace … end`), so concatenation is valid Lean; the header records the provenance.

    python3 make_web.py            # (re)write web/*.lean for every module
    python3 make_web.py --check    # exit 1 if any web/*.lean differs from what would be written (CI)
"""
import re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC, OUT = ROOT / "FrcLedger", ROOT / "web"
IMPORT = re.compile(r"^import FrcLedger\.(\w+)\s*$", re.M)

def module(name):
    return (SRC / f"{name}.lean").read_text(encoding="utf-8")

def body(name):
    """The module without its `import` lines."""
    return re.sub(r"^import .*\n", "", module(name), flags=re.M).strip("\n") + "\n"

def deps(name, seen=None, order=None):
    seen = set() if seen is None else seen; order = [] if order is None else order
    for d in IMPORT.findall(module(name)):
        if d not in seen:
            seen.add(d); deps(d, seen, order); order.append(d)
    return order

def web(name):
    inlined = deps(name)
    parts = ["import Mathlib\n",
             f"/-! Generated by `lean/make_web.py` from `FrcLedger/{name}.lean`"
             + (f" with `FrcLedger/{'`, `FrcLedger/'.join(inlined)}` inlined" if inlined else "")
             + " — one self-contained file for the Lean web editor. Edit the modules, not this file. -/\n"]
    for d in inlined:
        parts.append(f"\n/-! inlined: FrcLedger/{d}.lean (verbatim, minus its import lines) -/\n\n" + body(d))
    parts.append(f"\n/-! FrcLedger/{name}.lean -/\n\n" + body(name))
    rows = re.findall(r"^(?:theorem|def) (p\d{5})\b", module(name), re.M)     # the ledger predicates: their axioms computed in the editor
    if rows: parts.append("\n-- Ledger predicates: axioms (each predicate's, computed here)\n" + "".join(f"#print axioms FRC.{name}.{r}\n" for r in rows))
    return "".join(parts)

def main():
    check = "--check" in sys.argv
    OUT.mkdir(exist_ok=True); bad = []
    for f in sorted(SRC.glob("*.lean")):
        name = f.stem; text = web(name); target = OUT / f"{name}.lean"
        if check:
            if not target.exists() or target.read_text(encoding="utf-8") != text: bad.append(name)
        else:
            target.write_text(text, encoding="utf-8"); print(f"web/{name}.lean: {text.count(chr(10))} lines, inlined {deps(name) or 'nothing'}")
    if check:
        if bad: sys.exit(f"web/ is stale for: {', '.join(bad)} — run make_web.py and commit")
        print("web/ is current")

if __name__ == "__main__":
    main()
