"""frc.ledgers — the ledger files, one per paper and one per master block (ledger migration, task LM20).

A ledger file binds its ledger's predicates to the themes: the table of keys (generated by ci/make_ledgers.py),
the shells and the checks. Nothing imports a ledger file (gate G09); its notebook and its Lean certificates are
generated beside it by ci/make_ledgers.py.
"""
