"""p06_fourier — the ledger file of 6-fourier (ledger migration, task LM36, 7 October 2026).

"Scale-Shift and Fractional Fourier Transform as Rotations over Finite Holographic Substrate" (Akhtman, 2026; doi
10.20944/preprints202606.0127.v1). The paper's predicate ledger is docs/6-fourier/6-fourier-ledger.json. This file binds
its predicates to the framework: the table of keys (generated from the ledger by ci/make_ledgers.py), the shells of the
paper's Table tab:checks, and the thirty-nine checks of five blocks. Each check names the predicate(s) it witnesses
(LEDGER) under a `# 6:XN (<key>)` marker on the check that decides it (PREDICATES). The checks are those of the paper's
validation package (src/6-fourier/fourier.py of 25 September 2026) and compute what it computes, record for record. The
package stays the paper's published witness until its release pins the framework (tasks LM33, LM36).

The exact checks call the fourier theme (frc/fourier.py: the transform, the projectors, the family, the meridians, ranks
over F_p) and frc/arith.py; block E's readout on ℂ^n calls the chart file frc/chart_fourier.py, so this file stays exact
(gate G09). The Lean side is the certificates lean/FrcCore/Ledgers/P06Fourier.lean and
lean/FrcLedger/Ledgers/P06Fourier.lean, over the frame and fourier themes' keys.

    python3 -m frc.ledgers.p06_fourier        every block, the census; exit 1 if a check fails (≈ 1 min)
    python3 -m frc.ledgers.p06_fourier D      one block (A to E)
    from frc.ledgers.p06_fourier import R; R.predicate("6:C3")    one predicate: its blocks run once per session

Blocks:  A  the frame datum and the shell Fourier operator     EXACT            (6:B1–B3, B5–B7)
         B  the fractional family F^[s]                        EXACT            (6:C2–C11)
         C  representation domains and the coordinate zoom     EXACT            (6:D1, D2, D4, D5, D7)
         D  the Weil dictionary, the operator-level comparison EXACT            (6:E2, E3, E5–E10)
         E  the cyclotomic observer readout, the entropy cycle EXACT, APPROX    (6:F2–F8)

The notebook frc/ledgers/p06_fourier.ipynb runs one predicate per cell, the cell's id its key (gate G13).
"""
import random
import sys
from fractions import Fraction as Fr
from math import gcd, isqrt

from frc import arith
from frc import chart_fourier as CF
from frc.fourier import identity, is_monomial, matmul, matpow, rank_mod, shift_matrix
from frc.registry import Registry

# ---- generated by ci/make_ledgers.py from docs/6-fourier/6-fourier-ledger.json; edit the ledger, not this table ----
PAPER = "6-fourier"
KEYS = {"A1": "p06001", "A2": "p06002", "A3": "p06003", "A4": "p06004", "A5": "p06005", "A6": "p06006", "A7": "p06007", "A8": "p06055", "B1": "p06008", "B2": "p06009", "B3": "p06010", "B4": "p06011", "B5": "p06012", "B6": "p06013", "B7": "p06014", "C1": "p06015", "C2": "p06016", "C3": "p06017", "C4": "p06018", "C5": "p06019", "C6": "p06020", "C7": "p06021", "C8": "p06022", "C9": "p06023", "C10": "p06051", "C11": "p06052", "D1": "p06024", "D2": "p06025", "D3": "p06026", "D4": "p06027", "D5": "p06028", "D6": "p06029", "D7": "p06053", "E1": "p06030", "E2": "p06031", "E3": "p06032", "E4": "p06033", "E5": "p06034", "E6": "p06035", "E7": "p06036", "E8": "p06050", "E9": "p06054", "E10": "p06056", "F1": "p06037", "F2": "p06038", "F3": "p06039", "F4": "p06040", "F5": "p06041", "F6": "p06042", "F7": "p06043", "F8": "p06049"}       # every row of the ledger: its label and its accession key
LEAN = {"B2": "core", "B3": "core", "B5": "core, ml", "B6": "core", "B7": "core, ml", "C2": "core, ml", "C3": "core, ml", "C4": "core, ml", "C5": "core, ml", "C6": "core", "C7": "ml", "C8": "core, ml", "C9": "core, ml", "C11": "core", "D1": "core", "D2": "core, ml", "D4": "core", "D5": "core", "D7": "core", "E2": "ml", "E3": "ml", "E5": "ml", "E6": "ml", "E7": "ml"}       # the rows with a Lean declaration: the libraries whose key files prove them
# ---- end of the generated table ----

LEAN_ONLY = ()                  # the predicates with a Lean declaration and no python check (gate G12): none

# Table tab:checks: (p, κ, g, i), g the least primitive root, i = −g^κ.
TABLE = [(5, 1, 2, 3), (13, 3, 2, 5), (17, 4, 3, 4), (29, 7, 2, 17), (37, 9, 2, 6), (41, 10, 6, 9)]
SHELLS = [p for p, _, _, _ in TABLE]

# The paper's predicate ledger (Appendix A, predicates cited as 6:XN): the predicate(s) each check witnesses.
LEDGER = {
    "A1": "6:B1", "A2": "6:B2", "A3": "6:B3", "A4": "6:B5", "A5": "6:B6", "A6": "6:B7",
    "B1": "6:C2", "B2": "6:C3", "B3": "6:C3", "B4": "6:C4", "B5": "6:C5", "B6": "6:C6", "B7": "6:C7, 6:C10", "B8": "6:C7, 6:C10",
    "B9": "6:C8, 6:C11", "B10": "6:C9",
    "C1": "6:D1", "C2": "6:D2", "C3": "6:D2, 6:D7", "C4": "6:D4", "C5": "6:D4", "C6": "6:D5",
    "D1": "6:E2", "D2": "6:E2", "D3": "6:E3", "D4": "6:E5, 6:E9", "D5": "6:E6", "D6": "6:E7", "D7": "6:E7", "D8": "6:E8", "D9": "6:E10",
    "E1": "6:F2", "E2": "6:F3", "E3": "6:F3", "E4": "6:F4", "E5": "6:F5", "E6": "6:F6", "E7": "6:F7", "E8": "6:F8",
}

BLOCK = {"A": "the frame datum and the shell Fourier operator",          # check-id prefix -> the block (the function block_<letter> below)
         "B": "the fractional family F^[s]",
         "C": "representation domains and the coordinate zoom",
         "D": "the Weil dictionary and the operator-level comparison",
         "E": "the cyclotomic observer readout and the entropy cycle"}

# the deciding check of each witnessed predicate, as the package names it
PREDICATES = {
    "6:B1": "A1", "6:B2": "A2", "6:B3": "A3", "6:B5": "A4", "6:B6": "A5", "6:B7": "A6",
    "6:C2": "B1", "6:C3": "B2", "6:C4": "B4", "6:C5": "B5", "6:C6": "B6", "6:C7": "B7", "6:C8": "B9", "6:C9": "B10", "6:C10": "B7", "6:C11": "B9",
    "6:D1": "C1", "6:D2": "C2", "6:D4": "C4", "6:D5": "C6", "6:D7": "C3",
    "6:E2": "D2", "6:E3": "D3", "6:E5": "D4", "6:E6": "D5", "6:E7": "D6", "6:E8": "D8", "6:E9": "D4", "6:E10": "D9",
    "6:F2": "E1", "6:F3": "E2", "6:F4": "E4", "6:F5": "E5", "6:F6": "E6", "6:F7": "E7", "6:F8": "E8",
}

R = Registry("6", "fourier", LEDGER, PREDICATES, sources=[__file__])


def primitive_roots(p):
    return [g for g in range(2, p) if arith.order(g, p) == p - 1]


def mod(M, p):
    return [[x % p for x in row] for row in M]


def scal(c, M, p):
    return [[c * x % p for x in row] for row in M]


def add(A, B, p):
    return [[(x + y) % p for x, y in zip(a, b)] for a, b in zip(A, B)]


class Frame:
    """The framed shell F_p(t; 0, 1, g): p = 4κ+1, g primitive, i = −g^κ, π = 2κ, e = g^i, n = p − 1 = 4κ; the matrices
    over F_p as lists of rows, entries in [0, p)."""
    def __init__(self, p, g=None):
        self.p, self.n, self.kap = p, p - 1, (p - 1) // 4
        self.g = arith.primitive_root(p) if g is None else g
        assert arith.order(self.g, p) == p - 1
        self.i = (-pow(self.g, self.kap, p)) % p
        self.pi = 2 * self.kap
        self.e = pow(self.g, self.i, p)
        self.inv2, self.inv4 = pow(2, p - 2, p), pow(4, p - 2, p)
        self._W = self._F = self._Pi = None

    def conjugate(self):
        return Frame(self.p, pow(self.g, self.p - 2, self.p))

    def gpow(self, k):
        return pow(self.g, k % self.n, self.p)

    @property
    def W(self):
        if self._W is None: self._W = [[self.gpow(j * k) for j in range(self.n)] for k in range(self.n)]
        return self._W

    @property
    def F(self):
        if self._F is None: self._F = scal(self.i, self.W, self.p)
        return self._F

    @property
    def J(self):
        return [[1 if j == (-k) % self.n else 0 for j in range(self.n)] for k in range(self.n)]

    def I(self):
        return identity(self.n)

    @property
    def Pi(self):
        """Π_ℓ = ¼ Σ_r i^{−ℓr} F^r, the powers of F by multiplication."""
        if self._Pi is None:
            p, n = self.p, self.n
            Fs = [self.I()]
            for _ in range(3): Fs.append(matmul(Fs[-1], self.F, p))
            inv_i = pow(self.i, p - 2, p)
            self._Pi = []
            for ell in range(4):
                c = [pow(inv_i, ell * r, p) for r in range(4)]
                self._Pi.append([[self.inv4 * sum(c[r] * Fs[r][a][b] for r in range(4)) % p for b in range(n)] for a in range(n)])
            self._Fpows = Fs
        return self._Pi

    def Fpow(self, r):
        self.Pi
        return self._Fpows[r % 4]

    def frft(self, s):
        """F^[s] = Σ_ℓ g^{−ℓs} Π_ℓ."""
        p, n = self.p, self.n
        w = [self.gpow(-ell * s) for ell in range(4)]
        P = self.Pi
        return [[sum(w[l] * P[l][a][b] for l in range(4)) % p for b in range(n)] for a in range(n)]

    def mults(self):
        return tuple(rank_mod(P, self.p) for P in self.Pi)

    def gauss(self):
        return sum(self.gpow(k * k) for k in range(self.n)) % self.p

    def epsilon(self):
        G, onepi = self.gauss(), (1 + self.i) % self.p
        return 1 if G == onepi else (-1 if G == (-onepi) % self.p else None)

    def meridian(self, m):
        em = self.gpow(m)
        return tuple((a * em) % self.p for a in range(self.pi + 1))

    def S(self, r, x):
        return (self.gpow(r) * x) % self.p

    def z(self, s):
        return self.gpow(-s)

    def R(self, s):
        """R_s = [[c_s, −d_s], [d_s, c_s]], c_s = (z+z⁻¹)/2, d_s = (z−z⁻¹)/(2i)."""
        p, z = self.p, self.z(s)
        zi = pow(z, p - 2, p)
        c = ((z + zi) * self.inv2) % p
        d = ((z - zi) * self.inv2 * pow(self.i, p - 2, p)) % p
        return [[c, (-d) % p], [d, c]]


def trace(M, p):
    return sum(M[k][k] for k in range(len(M))) % p


def columns(M):
    return [tuple(c) for c in zip(*M)]


# ------------------------------------------------------------------------------------------------------------
# block A: the frame datum and the shell Fourier operator (6:B1–B3, B5–B7)
# The shell data of Table tab:checks; the Euler identity on the odd quarter-turn and its toggle under the conjugate
# reframing; the u-relabelling; W² = −J, (iW)² = J, (iW)⁴ = I; the unitary normalisation ±i read in the field; the
# symmetric–antisymmetric decomposition.
@R.block("A", BLOCK["A"])
def block_A():
    """Block A — the frame datum and the shell Fourier operator (EXACT): A1–A6."""
    frames = {p: Frame(p) for p in SHELLS}
    ok, rows = True, []
    for p, kap, g, i in TABLE:
        f = frames[p]
        ok &= (p == 4 * kap + 1 and f.kap == kap and f.g == g and f.i == i)
        ok &= (f.i == (-pow(g, kap, p)) % p == pow(g, p - 1 - kap, p) == pow(g, 3 * kap, p))
        ok &= (f.i * f.i % p == p - 1)
        ok &= (f.pi == 2 * kap and (2 * f.pi) % p == p - 1 and pow(g, f.pi, p) == p - 1)
        ok &= ((-f.pi) % p == f.inv2)
        ok &= (f.e == pow(g, i, p))
        rows.append(f"F_{p}(κ={kap}, g={g}, i={i}, e={f.e})")
    # 6:B1 (p06008)
    R.check("A1", "p = 4κ+1, g the smallest primitive root, i = −g^κ = g^{−κ}, i² ≡ −1, π = 2κ, 2π ≡ −1, g^π ≡ −1, −π ≡ 2⁻¹, e = g^i; Table tab:checks (κ, g, i)",
            ok, "; ".join(rows))
    ok, n_frames, n_carry = True, 0, 0
    for p in SHELLS:
        for g in primitive_roots(p):
            f = Frame(p, g)
            euler = pow(f.e, f.i * f.pi, p)
            ok &= (euler == pow(g, f.pi * (f.i % 2), p))
            ok &= ((euler == p - 1) == (f.i % 2 == 1))
            fc = f.conjugate()
            ok &= (fc.i == (-f.i) % p and fc.i % 2 != f.i % 2)
            carries_c = pow(fc.e, fc.i * fc.pi, p) == p - 1
            ok &= ((euler == p - 1) != carries_c)
            n_frames += 1; n_carry += (euler == p - 1)
    f13 = frames[13]
    ok &= (f13.i == 5 and f13.e == 6 and pow(6, 5 * 6, 13) == 12 and pow(6, 6, 13) == 12)
    # 6:B2 (p06009)
    R.check("A2", "e^{iπ} = g^{2κ(i mod 2)} ≡ −1 exactly on the odd quarter-turn; the conjugate reframing toggles it, one member of each pair carries it",
            ok, f"{n_frames} primitive frames of p ∈ {SHELLS}, {n_carry} carry e^{{iπ}} ≡ −1 (one per conjugate pair); F_13(t;0,1,2): i = 5, e = 6, 6^{{30}} = 6^{{6}} ≡ −1")
    ok = True
    for p in SHELLS:
        f = frames[p]
        for u in range(1, f.n):
            if gcd(u, f.n) != 1: continue
            fu = Frame(p, pow(f.g, u, p))
            ok &= (fu.i == f.i) if u % 4 == 1 else (fu.i == (-f.i) % p)
            if u % 4 == 1:
                ok &= (fu.e == pow(f.g, u * f.i, p))
                ok &= ((fu.e != f.e) == ((f.i * (u - 1)) % f.n != 0))
    f5 = Frame(13, pow(2, 5, 13))
    ok &= (f5.i == f13.i and f5.e == 2 and f13.e == 6 and pow(6, 5, 13) == 2)
    # 6:B3 (p06010)
    R.check("A3", "g' = g^u: the quarter-turn flips only on u ≡ 3 (mod 4); e' = g^{ui} ≠ e iff i(u−1) ≢ 0 (mod 4κ); at p = 13, u = 5: e' = 2 ≠ 6",
            ok, "every unit u of Z_{4κ} on the six shells; F_13, g' = 2^5 = 6: i' = 5, e' = 6^5 = 2")
    ok, det = True, []
    for p in SHELLS:
        f = frames[p]
        W2 = matmul(f.W, f.W, p); F2 = matmul(f.F, f.F, p); F4 = matmul(F2, F2, p)
        a, b, c = W2 == scal(-1, f.J, p), F2 == f.J, F4 == f.I()
        ok &= a and b and c
        det.append(f"p={p}: {a},{b},{c}")
    # 6:B5 (p06012)
    R.check("A4", "W² = −J, (iW)² = J, (iW)⁴ = I on the six shells of Table tab:checks", ok, "; ".join(det))
    ok = True
    for p in SHELLS:
        f = frames[p]
        roots = sorted(c for c in range(p) if c * c % p == p - 1)
        ok &= (roots == sorted([f.i, (-f.i) % p]))
        ok &= ((1 * pow(f.n, p - 2, p)) % p == p - 1)
        for c in range(1, p):
            cW = scal(c, f.W, p)
            ok &= ((matmul(cW, cW, p) == f.J) == (c in roots))
    # 6:B6 (p06013)
    R.check("A5", "the square roots of 1/n ≡ −1 in F_p are exactly ±i, the two unitary normalisations of W: (cW)² = J iff c = ±i", ok, f"every c ∈ F_p^× tested on p ∈ {SHELLS}")
    ok, det = True, []
    for p in SHELLS:
        f = frames[p]
        ok &= matmul(f.W, f.J, p) == matmul(f.J, f.W, p) and matmul(f.F, f.J, p) == matmul(f.J, f.F, p)
        dplus = f.n - rank_mod(add(f.J, scal(-1, f.I(), p), p), p); dminus = f.n - rank_mod(add(f.J, f.I(), p), p)
        ok &= (dplus == 2 * f.kap + 1 and dminus == 2 * f.kap - 1)
        det.append(f"p={p}: dim V⁺={dplus}, V⁻={dminus}")
    # 6:B7 (p06014)
    R.check("A6", "WJ = JW, FJ = JF; dim V⁺ = 2κ+1, dim V⁻ = 2κ−1", ok, "; ".join(det))


# ------------------------------------------------------------------------------------------------------------
# block B: the fractional family F^[s] = Σ_ℓ g^{−ℓs} Π_ℓ (6:C2–C11)
# The projectors; additivity on every pair; the cardinal values; faithfulness; the multiplicities as ranks and their
# dichotomy from the Gauss sign on every primitive frame; the proof's trace identities; the exponent lifts and the
# non-commuting charts; the conjugate reframing.
@R.block("B", BLOCK["B"])
def block_B():
    """Block B — the fractional family (EXACT): B1–B10."""
    frames = {p: Frame(p) for p in SHELLS}
    ok = True
    for p in SHELLS:
        f = frames[p]; Pi = f.Pi
        S = [[0] * f.n for _ in range(f.n)]
        for l in range(4):
            S = add(S, Pi[l], p)
            ok &= matmul(Pi[l], Pi[l], p) == Pi[l]
            ok &= matmul(f.F, Pi[l], p) == scal(pow(f.i, l, p), Pi[l], p)
            for m in range(4):
                if m != l: ok &= all(x == 0 for row in matmul(Pi[l], Pi[m], p) for x in row)
        ok &= S == f.I()
    # 6:C2 (p06016)
    R.check("B1", "Π_ℓ² = Π_ℓ, Π_ℓ Π_m = 0, Σ Π_ℓ = I, F Π_ℓ = i^ℓ Π_ℓ", ok, f"p ∈ {SHELLS}")
    ok, npairs = True, 0
    for p in SHELLS:
        f = frames[p]
        fam = [f.frft(s) for s in range(f.n)]
        for s in range(f.n):
            for r in range(f.n):
                ok &= matmul(fam[s], fam[r], p) == fam[(s + r) % f.n]; npairs += 1
        f._fam = fam
    # 6:C3 (p06017)
    R.check("B2", "F^[s+r] = F^[s] F^[r] on every pair (s, r) of Z_{4κ}", ok, f"{npairs} pairs over p ∈ {SHELLS}")
    ok = True
    for p in SHELLS:
        f = frames[p]; fam = f._fam; k = f.kap
        F3 = matpow(f.F, 3, p)
        ok &= fam[0] == f.I() and fam[k] == f.F and fam[2 * k] == f.J and fam[3 * k] == F3
        ok &= matmul(F3, f.F, p) == f.I()
        ok &= matpow(fam[1], k, p) == f.F
    R.check("B3", "F^[0] = I, F^[κ] = F, F^[2κ] = J, F^[3κ] = F⁻¹, F^[4κ] = I; (F^[1])^κ = F", ok, f"p ∈ {SHELLS}")
    ok = True
    for p in SHELLS:
        f = frames[p]; fam = f._fam
        ok &= all(fam[s] != f.I() for s in range(1, f.n))
        ok &= len({tuple(map(tuple, fam[s])) for s in range(f.n)}) == f.n
    # 6:C4 (p06018)
    R.check("B4", "s ↦ F^[s] is injective on Z_{4κ}: the 4κ members are pairwise distinct (p = 5 included)", ok, f"p ∈ {SHELLS}")
    ok, det = True, []
    for p in SHELLS:
        f = frames[p]; m = f.mults()
        for l in range(4):
            ok &= (m[l] == f.n - rank_mod(add(f.F, scal(-pow(f.i, l, p), f.I(), p), p), p))
        ok &= (m[0] + m[2] == 2 * f.kap + 1 and m[1] + m[3] == 2 * f.kap - 1 and m[0] >= 1 and m[2] >= 1)
        ok &= (m[1] >= 1 and m[3] >= 1) if f.kap >= 2 else ((m[1] == 0) != (m[3] == 0))
        det.append(f"p={p}: {m}")
    # 6:C5 (p06019)
    R.check("B5", "m_ℓ = rank Π_ℓ = dim ker(F − i^ℓ I); m_0+m_2 = 2κ+1, m_1+m_3 = 2κ−1; m_0, m_2 ≥ 1; m_1, m_3 ≥ 1 for κ ≥ 2; p = 5: one odd projector vanishes", ok, "; ".join(det))
    f2, f6 = Frame(13, 2), Frame(13, 6)
    ok = (f2.mults() == (3, 3, 4, 2) and f6.mults() == (4, 2, 3, 3))
    ok &= (trace(f2.F, 13) == 4 and trace(f6.F, 13) == 9)
    ok &= (pow(2, 5, 13) == 6)
    nconj = 0
    for p in SHELLS:
        f = frames[p]
        for u in range(1, f.n):
            if gcd(u, f.n) != 1: continue
            fu = Frame(p, pow(f.g, u * u, p))
            perm = [(u * k) % f.n for k in range(f.n)]
            ok &= fu.F == [[f.F[a][b] for b in perm] for a in perm]; nconj += 1
    # 6:C6 (p06020)
    R.check("B6", "p = 13: g = 2 gives (3,3,4,2), Tr F = 4; g = 6 gives (4,2,3,3), Tr F = 9; m ↦ um carries F(g) to F(g^{u²}) by a permutation", ok, f"{nconj} relabellings over p ∈ {SHELLS}")
    ok, det, n38 = True, [], 0
    for p in SHELLS:
        f0 = frames[p]; k = f0.kap
        prims = primitive_roots(p)
        eps = {}
        for g in prims:
            f = Frame(p, g); e = f.epsilon()
            ok &= (e is not None)
            eps[g] = e
            want = (k, k, k + 1, k - 1) if e == 1 else (k + 1, k - 1, k, k)
            ok &= (f.mults() == want)
        for g in prims:
            ok &= (eps[pow(g, p - 2, p)] == -eps[g])
            for u in range(1, f0.n):
                if gcd(u, f0.n) == 1 and u % 4 == 1:
                    ok &= (eps[pow(g, u, p)] == arith.jacobi(k, u) * eps[g])
        ok &= (2 * sum(1 for g in prims if eps[g] == 1) == len(prims))
        if k >= 2: ok &= (eps[f0.g] == 1)
        if p != 41: n38 += len(prims)
        det.append(f"p={p}: {len(prims)} frames, ε=+1 on {sum(1 for g in prims if eps[g] == 1)}")
    ok &= (n38 == 38)
    ok &= (Frame(5, 2).mults() == (2, 0, 1, 1) and Frame(5, 2).epsilon() == -1)
    ok &= (Frame(5, 3).mults() == (1, 1, 2, 0) and Frame(5, 3).epsilon() == 1)
    # 6:C7 (p06021), 6:C10 (p06051)
    R.check("B7", "G = ε(1+i), the two patterns, ε(g⁻¹) = −ε(g), ε(g^u) = (κ/u) ε(g), classes equally populated; 38 frames of p ∈ {5,…,37} and 16 of p = 41; p = 5: (2,0,1,1) at g = 2, (1,1,2,0) at g = 3",
            ok, "; ".join(det))
    ok = True
    for p in SHELLS:
        for g in primitive_roots(p):
            f = Frame(p, g)
            G = f.gauss(); Gs = sum(f.gpow(-k * k) for k in range(f.n)) % p
            ok &= (G * Gs % p == p - 2 and G * G % p == 2 * f.i % p)
            tr = [trace(f.Fpow(r), p) for r in range(4)]
            ok &= (tr[1] == f.i * G % p and tr[2] == 2 and tr[3] == f.i * Gs % p)
            m = f.mults()
            inv_i = pow(f.i, p - 2, p)
            for l in range(4):
                ok &= (m[l] % p == f.inv4 * sum(pow(inv_i, l * r, p) * tr[r] for r in range(4)) % p)
    R.check("B8", "G G* = −2, G² = 2i, Tr F = iG, Tr F² = 2, Tr F³ = iG*, m_ℓ ≡ ¼ Σ_r i^{−ℓr} Tr F^r (mod p)", ok, "every primitive frame of the six shells")
    f = frames[13]; ok = True
    for a in [(0, 1, 2, 3), (0, 5, 2, 3), (4, 1, 6, 7), (0, 1, 2, 11)]:
        U = []
        for s in range(12):
            w = [f.gpow(-a[l] * s) for l in range(4)]
            U.append([[sum(w[l] * f.Pi[l][x][y] for l in range(4)) % 13 for y in range(12)] for x in range(12)])
        ok &= all(matmul(U[s], U[r], 13) == U[(s + r) % 12] for s in range(12) for r in range(12))
        ok &= U[0] == f.I() and U[3] == f.F and U[6] == f.J and U[9] == matpow(f.F, 3, 13)
    f29 = frames[29]; f29u = Frame(29, pow(f29.g, 5, 29))
    ok &= (25 % 28 != 1)
    noncomm = matmul(f29u.frft(1), f29.F, 29) != matmul(f29.F, f29u.frft(1), 29)
    ok &= noncomm
    scan = []
    for p in SHELLS:
        f0 = frames[p]
        for u in range(1, f0.n):
            if gcd(u, f0.n) == 1 and (u * u) % f0.n != 1:
                fu = Frame(p, pow(f0.g, u, p)); F1 = fu.frft(1)
                scan.append((p, u, matmul(F1, f0.F, p) != matmul(f0.F, F1, p)))
    ok &= all(x[2] for x in scan)
    # 6:C8 (p06022), 6:C11 (p06052)
    R.check("B9", "exponent lifts a_ℓ ≡ ℓ (mod 4) are additive with the cardinal skeleton (p = 13); the chart g^5 at p = 29 (u² ≢ 1 mod 28) does not commute with F, nor does any chart with u² ≢ 1 (mod 4κ) on the six shells",
            ok, f"non-commuting at p = 29, u = 5: {noncomm}; all charts with u² ≢ 1 (mod 4κ) on the six shells non-commuting: {all(x[2] for x in scan)} ({len(scan)} charts)")
    ok, det = True, []
    for p in SHELLS:
        f = frames[p]; fc = f.conjugate(); k = f.kap
        ok &= (fc.i == (-f.i) % p)
        Finv = matpow(f.F, 3, p)
        ok &= fc.F == scal(-1, Finv, p)
        ok &= matmul(fc.F, fc.F, p) == f.J and matpow(fc.F, 4, p) == f.I()
        famc = [fc.frft(s) for s in range(f.n)]
        ok &= famc[0] == f.I() and famc[k] == fc.F and famc[2 * k] == f.J
        ok &= all(matmul(famc[s], famc[r], p) == famc[(s + r) % f.n] for s in range(f.n) for r in range(0, f.n, 3))
        ok &= len({tuple(map(tuple, M)) for M in famc}) == f.n
        ok &= all(fc.Pi[l] == f.Pi[(l + 2) % 4] for l in range(4))
        m, mc = f.mults(), fc.mults()
        ok &= (mc == (m[2], m[3], m[0], m[1]) and {m, mc} == {(k, k, k + 1, k - 1), (k + 1, k - 1, k, k)})
        det.append(f"p={p}: {m} ↦ {mc}")
    # 6:C9 (p06023)
    R.check("B10", "the conjugate frame (g⁻¹, −i) keeps the operator relations, cardinal values, additivity and faithfulness; its multiplicity tuple is the other pattern; F' = −F⁻¹, Π'_ℓ = Π_{ℓ+2}",
            ok, "; ".join(det))


# ------------------------------------------------------------------------------------------------------------
# block C: representation domains and the coordinate-side zoom (6:D1, D2, D4, D5, D7)
@R.block("C", BLOCK["C"])
def block_C():
    """Block C — representation domains and the coordinate-side zoom (EXACT): C1–C6."""
    frames = {p: Frame(p) for p in SHELLS}
    ok = True
    for p in SHELLS:
        f = frames[p]
        fam = [f.frft(s) for s in range(f.n)]; f._fam = fam
        ok &= all(rank_mod(M, p) == f.n for M in fam)
        ok &= all(f.gpow(-l * s) != 0 for s in range(f.n) for l in range(4))
    # 6:D1 (p06024)
    R.check("C1", "every F^[s] has full rank 4κ over F_p; the eigenvalues g^{−ℓs} are nonzero", ok, f"p ∈ {SHELLS}")
    ok = True
    for p in SHELLS:
        f = frames[p]
        ok &= len({tuple(columns(M)) for M in f._fam}) == f.n
    # 6:D2 (p06025)
    R.check("C2", "the 4κ framed bases B_s = F^[s] B_0 are pairwise distinct", ok, f"p ∈ {SHELLS}")
    ok, det = True, []
    for p in SHELLS:
        f = frames[p]; k = f.kap
        ok &= all(f._fam[(s + 2 * k) % f.n] == matmul(f._fam[s], f.J, p) for s in range(f.n))
        bases = [frozenset(columns(M)) for M in f._fam]
        unordered = set(bases)
        ok &= (len(unordered) == 2 * k)
        ok &= all((bases[s] == bases[t]) == ((s - t) % (2 * k) == 0) for s in range(f.n) for t in range(f.n))
        for t in range(f.n):
            if t in (0, 2 * k): continue
            val = f.i * f.inv2 * (1 - f.gpow(-2 * t)) % p
            ok &= val != 0 and all(f._fam[t][0][kk] == val for kk in range(1, f.n)) and sum(1 for x in f._fam[t][0] if x) >= 2
        det.append(f"p={p}: {f.n} framed, {len(unordered)} unordered")
    # 6:D7 (p06053)
    R.check("C3", "F^[s+2κ] = F^[s] J, so B_{s+2κ} = B_s as unordered bases, and B_{s+t} ≠ B_s for t ∉ {0,2κ}: every off-site entry of row 0 of F^[t] is (i/2)(1 − g^{−2t}) ≠ 0, F^[t] not monomial — 4κ framed domains, exactly 2κ measurement bases", ok, "; ".join(det))
    ok, npairs = True, 0
    for p in SHELLS:
        f = frames[p]
        for m in range(f.n):
            Mm = f.meridian(m)
            for r in range(f.n):
                ok &= (tuple(f.S(r, x) for x in Mm) == f.meridian(m + r)); npairs += 1
    # 6:D4 (p06027)
    R.check("C4", "S_r(M_m) = M_{m+r} on every (m, r), as ordered lists", ok, f"{npairs} pairs over p ∈ {SHELLS}")
    ok = True
    for p in SHELLS:
        f = frames[p]
        for m in range(f.n):
            Mm = f.meridian(m)
            ok &= all((Mm[a + 1] - Mm[a]) % p == f.gpow(m) for a in range(f.pi))
        ok &= all(f.S(r + p - 1, x) == f.S(r, x) for r in range(f.n) for x in range(p))
    R.check("C5", "consecutive entries of M_m differ by the effective step g^m; S_{r+(p−1)} = S_r", ok, f"p ∈ {SHELLS}")
    f = frames[13]
    ladder = {0: (0, 1, 2, 3, 4, 5, 6), 1: (0, 2, 4, 6, 8, 10, 12), 2: (0, 4, 8, 12, 3, 7, 11), 3: (0, 8, 3, 11, 6, 1, 9)}
    ok = (f.g == 2 and f.i == 5 and f.pi == 6 and all(f.meridian(m) == ladder[m] for m in ladder))
    ok &= all(f.gpow(m) == 2 ** m for m in range(4))
    w = f.pi
    unwrapped = [m for m in range(f.n) if w * 2 ** m < 13]
    wraps = [m for m in range(4) if any(a * 2 ** m >= 13 for a in range(w + 1))]
    ok &= (unwrapped == [0, 1] and wraps == [2, 3])
    # 6:D5 (p06028)
    R.check("C6", "p = 13, g = 2: M_0…M_3 = the printed ladder at steps 1, 2, 4, 8; the no-wrap window w·g^r < p with w = π = 6 holds for r ≤ 1 and the listing wraps from M_2", ok, f"unwrapped meridians {unwrapped}, wrapping {wraps}")


# ------------------------------------------------------------------------------------------------------------
# block D: the Weil dictionary and the operator-level comparison (6:E2, E3, E5–E10)
@R.block("D", BLOCK["D"])
def block_D():
    """Block D — the Weil dictionary and the operator-level comparison (EXACT): D1–D9."""
    frames = {p: Frame(p) for p in SHELLS}
    I2 = identity(2)
    ok = True
    for p in SHELLS:
        f = frames[p]
        for s in range(f.n):
            Rm = f.R(s); c, d = Rm[0][0], Rm[1][0]
            ok &= ((c * c + d * d) % p == 1 and (Rm[0][0] * Rm[1][1] - Rm[0][1] * Rm[1][0]) % p == 1)
            ok &= (Rm[0][1] == (-d) % p and Rm[1][1] == c)
    R.check("D1", "c_s² + d_s² = 1, det R_s = 1: R_s ∈ SO(2, F_p) for every s", ok, f"p ∈ {SHELLS}")
    ok, det = True, []
    for p in SHELLS:
        f = frames[p]
        Rs = [f.R(s) for s in range(f.n)]
        ok &= all(matmul(Rs[s], Rs[r], p) == Rs[(s + r) % f.n] for s in range(f.n) for r in range(f.n))
        ok &= (len({tuple(map(tuple, Rm)) for Rm in Rs}) == f.n)
        so2 = sum(1 for c in range(p) for d in range(p) if (c * c + d * d) % p == 1)
        ok &= (so2 == p - 1)
        det.append(f"p={p}: |SO(2)|={so2}")
    # 6:E2 (p06031)
    R.check("D2", "R_{s+r} = R_s R_r, s ↦ R_s injective, |SO(2, F_p)| = p−1 = 4κ: an isomorphism", ok, "; ".join(det))
    ok = True
    for p in SHELLS:
        f = frames[p]; k = f.kap
        w = [[0, p - 1], [1, 0]]
        ok &= (f.z(k) == f.i)
        ok &= f.R(0) == I2 and f.R(k) == w
        ok &= f.R(2 * k) == scal(-1, I2, p) and f.R(3 * k) == matpow(w, 3, p)
        ok &= matmul(f.R(3 * k), w, p) == I2
    # 6:E3 (p06032)
    R.check("D3", "R_0 = I, R_κ = [[0,−1],[1,0]] (Table tab:checks), R_{2κ} = −I, R_{3κ} = w⁻¹; z_κ = g^{−κ} = i", ok, f"p ∈ {SHELLS}")
    ok, det = True, []
    for p in SHELLS:
        f = frames[p]; n = f.n
        sig = shift_matrix(n)
        pw, sp = [identity(n)], identity(n)
        for _ in range(n): sp = matmul(sp, sig, p); pw.append(sp)
        ok &= pw[n] == f.I() and all(pw[r] != f.I() for r in range(1, n))
        ok &= all(rank_mod(add(sig, scal(-a, f.I(), p), p), p) == n - 1 for a in range(1, p))
        F1 = f.frft(1); eig = {f.gpow(-l) for l in range(4)}
        ranks = {a: rank_mod(add(F1, scal(-a, f.I(), p), p), p) for a in range(1, p)}
        ok &= all(ranks[a] == n for a in range(1, p) if a not in eig)
        neig = sum(1 for a in range(1, p) if ranks[a] < n)
        ok &= (neig <= 4) and (f.kap == 1 or neig < n)
        det.append(f"p={p}: σ has {n} simple eigenvalues, F^[1] has {neig}")
    # 6:E5 (p06034), 6:E9 (p06054)
    R.check("D4", "σ has the 4κ simple eigenvalues F_p^×; F^[1] has at most four; for κ ≥ 2 ⟨σ⟩ and ⟨F^[1]⟩ are not conjugate", ok, "; ".join(det))
    ok, det = True, []
    for p in SHELLS:
        f = frames[p]; n = f.n
        P1 = f.Pi[1]; m1 = rank_mod(P1, p)
        ok &= (m1 >= 1) if f.kap >= 2 else True
        if m1 == 0:
            det.append(f"p={p}: E_1 = 0 (κ = 1)"); continue
        cols = [[P1[a][j] for a in range(n)] for j in range(n) if any(P1[a][j] for a in range(n))]
        for s in range(n):
            Fs = f.frft(s)
            for v in cols[:3]:
                Fv = [sum(Fs[a][b] * v[b] for b in range(n)) % p for a in range(n)]
                ok &= Fv == [f.gpow(-s) * x % p for x in v]
                for x in range(p):
                    ok &= [y * x % p for y in Fv] == [f.S(-s, x) * y % p for y in v]       # F^[s] T_v(x) = T_v S_{−s}(x)
            vec = [1, (-f.i) % p]
            Rm = f.R(s)
            ok &= [(Rm[a][0] * vec[0] + Rm[a][1] * vec[1]) % p for a in range(2)] == [f.gpow(-s) * y % p for y in vec]
        det.append(f"p={p}: dim E_1 = {m1}")
    # 6:E6 (p06035)
    R.check("D5", "E_1 ≠ 0 for κ ≥ 2; F^[s] = g^{−s} on E_1; F^[s] T_v = T_v S_{−s} on every x and s; R_s (1,−i)ᵀ = g^{−s} (1,−i)ᵀ", ok, "; ".join(det))
    ok = True
    for p in SHELLS:
        f = frames[p]; n = f.n
        sig = shift_matrix(n)
        D1 = [[f.gpow(k) if k == j else 0 for j in range(n)] for k in range(n)]
        Dm = [[f.gpow(-k) if k == j else 0 for j in range(n)] for k in range(n)]
        Finv = matpow(f.F, 3, p); siginv = matpow(sig, n - 1, p)
        ok &= matmul(matmul(f.F, sig, p), Finv, p) == D1
        ok &= matmul(matmul(f.F, D1, p), Finv, p) == siginv
        sigs = [sig, D1, siginv, Dm]
        for r in range(4):
            ok &= matmul(f.Fpow(r), sig, p) == matmul(sigs[r], f.Fpow(r), p)
        for s in range(n):
            c = [f.inv4 * sum(pow(f.gpow(r * f.kap - s), l, p) for l in range(4)) % p for r in range(4)]
            M = [[sum(c[r] * f.Fpow(r)[a][b] for r in range(4)) % p for b in range(n)] for a in range(n)]
            ok &= M == f.frft(s)
    # 6:E7 (p06036)
    R.check("D6", "F σ F⁻¹ = D_1, F D_1 F⁻¹ = σ⁻¹; F^r σ = σ_r F^r with (σ, D_1, σ⁻¹, D_1⁻¹); F^[s] = Σ_r c_r(s) F^r, c_r(s) = ¼ Σ_ℓ (g^{rκ−s})^ℓ", ok, f"p ∈ {SHELLS}")
    ok, n_int, n_card, det = True, 0, 0, []
    for p in SHELLS:
        f = frames[p]; n = f.n; k = f.kap
        sig = shift_matrix(n)
        mono = [is_monomial(matmul(matmul(f.frft(s), sig, p), f.frft(-s), p)) for s in range(n)]
        card = {0, k, 2 * k, 3 * k}
        ok &= all(mono[s] for s in card) and all(not mono[s] for s in range(n) if s not in card)
        if p != 5: n_int += n - 4
        n_card += 4
        det.append(f"p={p}: monomial at {sorted(s for s in range(n) if mono[s])}")
    ok &= (n_int == 112)
    R.check("D7", "F^[s] σ F^[s]⁻¹ is monomial exactly at the four cardinal indices and non-monomial at every one of the 112 intermediate indices of p ∈ {13,17,29,37,41}", ok, "; ".join(det) + f"; {n_int} intermediate indices swept")
    ok, n_int8, worst, det = True, 0, None, []
    for p in [q for q in range(13, 200) if q % 4 == 1 and all(q % d for d in range(2, isqrt(q) + 1))]:
        f = frames.get(p) or Frame(p); n, k, inv2 = f.n, f.kap, pow(2, p - 2, p)
        c = lambda r, t: f.inv4 * sum(pow(f.gpow(r * k - t), l, p) for l in range(4)) % p
        # row 0 of F^[s] σ F^[s]⁻¹ = Σ_{ℓ,m} g^{−ℓs} g^{ms} (row 0 of Π_ℓ σ) Π_m: the product, expanded bilinearly
        P = f.Pi
        V = [[[sum(P[l][0][(a + 1) % n] * P[m][a][j] for a in range(n)) % p for j in range(n)] for m in range(4)] for l in range(4)]
        for s in range(n):
            if s % k == 0: continue
            cs, cps = [c(r, s) for r in range(4)], [c(r, -s) for r in range(4)]
            c02 = (cs[0] + cs[2]) % p
            ok &= all(x != 0 for x in cs + cps) and c02 == inv2 * (1 + f.gpow(-2 * s)) % p and c02 != 0
            lead, cst = f.i * c02 * cps[3] % p, f.i * c02 * cps[1] % p
            ok &= lead != 0 and cst != 0
            wl, wm = [f.gpow(-l * s) for l in range(4)], [f.gpow(m * s) for m in range(4)]
            row = [sum(wl[l] * wm[m] * V[l][m][j] for l in range(4) for m in range(4)) % p for j in range(n)]
            D0 = [f.i * (c02 * (cps[3] * f.gpow(j) + cps[1] * f.gpow(-j)) + (cs[1] + cs[3]) * (cps[0] + cps[2])) % p for j in range(n)]
            ok &= all(row[j] == D0[j] for j in range(n) if j not in {n - 1, 0, 1})
            nz = sum(1 for x in row if x); roots = sum(1 for j in range(n) if D0[j] == 0)
            ok &= roots <= 2 and nz >= n - 5
            worst = nz if worst is None else min(worst, nz)
            n_int8 += 1
        det.append(f"p={p}")
    ok &= len(det) == 20 and n_int8 == 1920
    # 6:E8 (p06050)
    R.check("D8", "cardinal exclusivity (thm:monomial): row 0 of F^[s] σ F^[s]⁻¹ is x⁻¹ times a quadratic in x = g^j off j ∈ {−1,0,1}, leading coefficient i(c₀+c₂)c₃(−s) ≠ 0, at least 4κ−5 nonzero entries for every non-cardinal s, every shell p ≡ 1 (mod 4) below 200", ok,
            f"{len(det)} shells, {n_int8} non-cardinal indices; fewest nonzero entries in row 0: {worst}")
    ok, det = True, []
    for p in SHELLS:
        f = frames[p]; n, i = f.n, f.i
        circle = {(c, d) for c in range(p) for d in range(p) if (c * c + d * d) % p == 1}
        Rs = {(f.R(s)[0][0], f.R(s)[1][0]) for s in range(n)}
        ok &= len(circle) == n and Rs == circle
        seen, orbits = set(), []
        for x in range(p):
            for y in range(p):
                if (x, y) in seen: continue
                orb = {((c * x - d * y) % p, (d * x + c * y) % p) for (c, d) in circle}
                seen |= orb; orbits.append((len(orb), (x * x + y * y) % p))
        sizes = sorted(o[0] for o in orbits)
        ok &= sizes == [1] + [n] * (n + 2) and p * p == 1 + (n + 2) * n
        ok &= len({q for (sz, q) in orbits if q != 0}) == n
        ok &= sum(1 for (sz, q) in orbits if q == 0 and sz == n) == 2
        null = {(x, y) for x in range(p) for y in range(p) if (x * x + y * y) % p == 0 and (x, y) != (0, 0)}
        ok &= null == {(x, (i * x) % p) for x in range(1, p)} | {(x, (-i * x) % p) for x in range(1, p)}
        for s in range(n):
            Rm, z = f.R(s), f.z(s); zi = pow(z, p - 2, p)
            for (x, y) in [(1, 0), (0, 1), (2, 3), (i, 1)]:
                x2, y2 = (Rm[0][0] * x + Rm[0][1] * y) % p, (Rm[1][0] * x + Rm[1][1] * y) % p
                u, v = (x + i * y) % p, (x - i * y) % p
                ok &= (x2 + i * y2) % p == z * u % p and (x2 - i * y2) % p == zi * v % p and (x * x + y * y) % p == u * v % p
        F1 = f.frft(1)
        ok &= (len(F1), len(F1[0])) == (n, n)
        det.append(f"p={p}: |SO(2)|={len(circle)}, orbits 1+{n + 2}×{n}")
    # 6:E10 (p06056)
    R.check("D9", "the plane as orbits of the cycle (cor:boundary): |SO(2,F_p)| = n = p−1 and it is {R_s}; F_p² = the origin + (n+2) free orbits (n circles of nonzero norm, two isotropic lines y = ±ix), p² = 1+(n+2)n; (u,v) ↦ (z_s u, z_s⁻¹ v); dim V = n",
            ok, "; ".join(det))


# ------------------------------------------------------------------------------------------------------------
# block E: the cyclotomic observer readout and the entropy on the meridian cycle (6:F2–F8)
# The readout realises the fractional family on ℂ^n through the observer's chart X ↦ ζ_n: E1 is exact (the Gauss
# polynomial modulo Φ_n in integers, G² = 2i in F_p) with one chart reading; E2–E8 are the chart's (frc/chart_fourier.py).
def cyclotomic(n):
    """Φ_n(X) as integer coefficients, low to high, by exact division of X^n − 1."""
    def div(a, b):
        a = list(a); q = [0] * (len(a) - len(b) + 1)
        for i in range(len(q) - 1, -1, -1):
            q[i] = a[i + len(b) - 1]
            for j in range(len(b)): a[i + j] -= q[i] * b[j]
        assert all(x == 0 for x in a[:len(b) - 1]), "inexact"
        return q
    poly = [-1] + [0] * (n - 1) + [1]
    for d in range(1, n):
        if n % d == 0: poly = div(poly, cyclotomic(d))
    return poly


def polyrem(a, b):
    a = list(a)
    while len(a) >= len(b):
        c = a[-1]
        if c:
            for j in range(len(b)): a[len(a) - len(b) + j] -= c * b[j]
        a.pop()
    return a


@R.block("E", BLOCK["E"])
def block_E():
    """Block E — the cyclotomic observer readout and the entropy cycle: E1 exact, E2–E8 the chart's."""
    frames = {p: Frame(p) for p in SHELLS}
    ok, det = True, []
    for p in SHELLS:
        f = frames[p]; n, k = f.n, f.kap
        G = [0] * n
        for kk in range(n): G[(kk * kk) % n] += 1
        G2 = [0] * n
        for a, x in enumerate(G):
            for b, y in enumerate(G):
                if x and y: G2[(a + b) % n] += x * y
        G2[k] -= 2 * n
        ok &= all(c == 0 for c in polyrem(G2, cyclotomic(n)))
        ok &= CF.gauss_square(n) < Fr(1, 10 ** 9)
        ok &= (f.gauss() ** 2 % p == 2 * f.i % p)
        det.append(f"n={n}: deg Φ_n = {len(cyclotomic(n)) - 1}")
    # 6:F2 (p06038)
    R.check("E1", "Ĝ² = 2n X^κ modulo Φ_n(X) (exact integer arithmetic); under σ_C: (Σ ζ^{k²})² = 2n i; under ρ: G² = 2i in F_p", ok, "; ".join(det))
    ok = all(CF.cardinal(p - 1) for p in SHELLS)
    # 6:F3 (p06039)
    R.check("E2", "H(0) = H(2κ) = 0, H(κ) = H(3κ) = log n for every δ_j", ok, f"n ∈ {[p - 1 for p in SHELLS]}", kind="[approx]")
    rng = random.Random(6)
    ok = all(CF.mub(p - 1, rng) for p in SHELLS)
    cok, h0, hk = CF.comb()
    R.check("E3", "B_0, B_κ mutually unbiased (overlaps 1/n); H_{B_0} + H_{B_κ} ≥ log n on random states, saturated by δ_j; the comb (δ_0+δ_6)/√2 at n = 12: log 2 + log 6 = log 12",
            ok and cok, f"comb: H_0 = {h0:.4f} = log 2, H_κ = {hk:.4f} = log 6; 200 random states per shell", kind="[approx]")
    ok, curves = True, {}
    for p in SHELLS:
        o, H = CF.closed_form(p - 1); ok &= o; curves[p] = H
    # 6:F4 (p06040)
    R.check("E4", "F^[s] δ_0 has the two-valued readout p_0 = 1 − (n−1)t_s/n, p_j = t_s/n, t_s = (2−ζ^{2s}−ζ^{−2s})/4 = sin²(πs/2κ); H(s) the closed form, strictly increasing on [0, κ], period 2κ, strictly intermediate off the cardinal indices",
            ok, f"n ∈ {[p - 1 for p in SHELLS]}", kind="[approx]")
    Hn = CF.normalised(curves[13], 12)
    table = [Fr(0), Fr(44, 100), Fr(91, 100), Fr(1), Fr(91, 100), Fr(44, 100)] * 2
    ok = all(CF.rounds_to(Hn[s], table[s]) for s in range(12))
    # 6:F5 (p06041)
    R.check("E5", "p = 13: H(s)/log n = 0, .44, .91, 1, .91, .44, 0, .44, .91, 1, .91, .44 (fig:entropy13)", ok,
            "H/log n = " + ", ".join(f"{x:.4f}" for x in Hn) + "; the figure is the package's", kind="[approx]")
    ok, H1 = CF.input_dependence(Hn, SHELLS)
    # 6:F6 (p06042)
    R.check("E6", "δ_1 at p = 13: H(1)/log n = 0.55 against 0.44 for δ_0; δ_j meets the odd projectors exactly when j ∉ {0, 2κ}; δ_{2κ} reproduces the δ_0 curve",
            ok, f"δ_1: H(1)/log n = {H1[1]:.4f}; δ_0: {Hn[1]:.4f}", kind="[approx]")
    ok, n_units, n_pairs, h5, h3 = CF.twist(curves, SHELLS, H1)
    ok &= n_pairs == 536
    # 6:F7 (p06043)
    R.check("E7", "X ↦ ζ^u leaves the cardinal values of every δ_j invariant and relabels the curve of δ_j by s ↦ us whenever ηuj ≡ j (mod n), ηu ≡ 1 (mod 4) — the Born vectors permuted by k ↦ ηuk: every cardinal site, every site for u = −1; n = 12, u = 5: δ_1 0.55 ↦ 0.44, from every relabelling; δ_3 unchanged at 0.42",
            ok, f"{n_units} twists over the six shells, {n_pairs} (u, j) pairs relabelled; n = 12, u = 5, s = 1: δ_1 {h5:.4f}, δ_3 {h3:.4f}", kind="[approx]")
    stated = [Fr(0), Fr(10, 100), Fr(41, 100), Fr(1), Fr(41, 100), Fr(10, 100)] * 2
    ok, bound = CF.uncertainty(SHELLS, random.Random(8), stated)
    # 6:F8 (p06049)
    R.check("E8", "c(s)² ≥ max{1/n, 1 − (n−1)t_s/n}; B_s mutually unbiased to B_0 exactly at s ∈ {κ, 3κ}; c(s) = 1 exactly at s ∈ {0, 2κ}; H_{B_0} + H_{B_s} ≥ −2 log c(s) on random states; p = 13: the bound 0, .10, .41, 1, .41, .10 per half-cycle",
            ok, "p = 13: −2 log c(s)/log n = " + ", ".join(f"{b + 0:.3f}" for b in bound) + "; 40 random states per (shell, s)", kind="[approx]")


if __name__ == "__main__":
    want = [a.upper() for a in sys.argv[1:]] or sorted(BLOCK)
    bad = [b for b in want if b not in BLOCK]
    if bad: sys.exit(f"no block {', '.join(bad)}: the blocks are {', '.join(sorted(BLOCK))}")
    for b in want: R.run_block(b)
    sys.exit(0 if R.summary(write=False, expect=list(LEDGER) if want == sorted(BLOCK) else None) else 1)
