"""p20_rh — the ledger file of 20-rh (ledger migration, task LM36, 7 October 2026).

"The Riemann Hypothesis over the Holographic Substrate: a Finite-Field Dictionary and the Screen Reading" (Akhtman and
Voether, 2026; doi 10.20944/preprints202606.0768.v1). The paper's predicate ledger is docs/20-rh/20-rh-ledger.json. This
file binds its predicates to the framework: the table of keys (generated from the ledger by ci/make_ledgers.py), the
shells, and the checks of three of the package's five blocks. Each check names the predicate(s) it witnesses (LEDGER)
under a `# 20:XN (<key>)` marker on the check that decides it (PREDICATES). The checks are those of the paper's
validation package (src/20-rh/rh.py of 24 September 2026) and compute what it computes, record for record. The package
stays the paper's published witness until its release pins the framework (tasks LM33, LM36).

The exact checks call the horizon, frame and extension themes (frc/horizon.py, frc/shell.py, frc/extension.py) and
frc/arith.py; the floating-point readings call the chart file frc/chart_rh.py and are compared here with rational
bounds, so this file stays exact (gate G09). The package's blocks C and D are not reproduced: they sum the von Mangoldt
comb to depths 10⁶–10⁸ over thousands of heights and evaluate ζ and L-functions with mpmath, which the package does
with numpy in eight minutes; the framework's chart tier is the standard library only. Their predicates keep the
package as their witness. The Lean side is the certificates lean/FrcCore/Ledgers/P20Rh.lean and
lean/FrcLedger/Ledgers/P20Rh.lean, over the horizon theme's keys and the chart theme's.

    python3 -m frc.ledgers.p20_rh         every block, the census; exit 1 if a check fails (≈ 30 s)
    python3 -m frc.ledgers.p20_rh E       one block (A, B or E)
    from frc.ledgers.p20_rh import R; R.predicate("20:B4")    one predicate: its blocks run once per session

Blocks:  A  the shell theorem and the exact shell arithmetic        EXACT, two APPROX   (20:B1–B10, E1, E12, E13)
         B  the de-framing dictionary                               CHART, APPROX       (20:D2–D4, B8)
         E  resonance, antipode, horizon, square-root cancellation  EXACT, APPROX       (20:B11, C2–C4, C6)

The notebook frc/ledgers/p20_rh.ipynb runs one predicate per cell, the cell's id its key (gate G13).
"""
import sys
from fractions import Fraction as Fr
from math import isqrt

from frc import arith
from frc import chart_rh as CR
from frc.extension import Ext
from frc.horizon import divisors, log_free_mangoldt, mobius_phi, prime_power_base, ramanujan_c, resonance, zeta
from frc.registry import Registry

# ---- generated by ci/make_ledgers.py from docs/20-rh/20-rh-ledger.json; edit the ledger, not this table ----
PAPER = "20-rh"
KEYS = {"A1": "p20001", "A2": "p20002", "A3": "p20003", "A4": "p20004", "A5": "p20078", "A6": "p20006", "A7": "p20007", "A8": "p20070", "A9": "p20071", "A10": "p20077", "B1": "p20008", "B2": "p20009", "B3": "p20010", "B4": "p20011", "B5": "p20012", "B6": "p20013", "B7": "p20014", "B8": "p20015", "B9": "p20016", "B10": "p20017", "B11": "p20018", "C1": "p20019", "C2": "p20020", "C3": "p20021", "C4": "p20022", "C5": "p20023", "C6": "p20024", "D1": "p20025", "D2": "p20026", "D3": "p20027", "D4": "p20028", "D5": "p20029", "D6": "p20030", "D7": "p20031", "E1": "p20032", "E2": "p20033", "E3": "p20034", "E4": "p20035", "E5": "p20036", "E6": "p20037", "E7": "p20038", "E8": "p20039", "E9": "p20040", "E10": "p20041", "E11": "p20042", "E12": "p20043", "E13": "p20044", "E14": "p20045", "E15": "p20046", "E16": "p20072", "F1": "p20047", "F2": "p20048", "F3": "p20049", "F4": "p20050", "F5": "p20051", "F6": "p20052", "F7": "p20053", "F8": "p20069", "Z1": "p20059", "Z2": "p20060", "Z5": "p20075"}       # every row of the ledger: its label and its accession key
LEAN = {"B1": "core, ml", "B2": "core, ml", "B4": "core, ml", "B5": "core, ml", "B6": "core, ml", "B7": "core, ml", "B8": "core, ml", "B9": "core, ml", "B10": "core, ml", "C2": "ml", "C5": "ml", "E1": "core, ml", "E12": "core, ml", "E13": "ml"}       # the rows with a Lean declaration: the libraries whose key files prove them
# ---- end of the generated table ----

LEAN_ONLY = ("C5",)             # 20:C5 (mean-square flatness) has a Lean declaration and no python check in the package

# The shells of block A: p = 13, 17, 29, 37, 41 in full; 173 for A1, A4 and A6.
SHELLS = [13, 17, 29, 37, 41]
BIG = 173

# The paper's predicate ledger (Appendix A, predicates cited as 20:XN): the predicate(s) each check witnesses; the
# package's checks of blocks A, B and E.
LEDGER = {
    "A1": "20:B4", "A2": "20:B5", "A3": "20:B6", "A4": "20:B8", "A5": "20:B9", "A6": "20:B10", "A6b": "20:B10", "A7": "20:E1, 20:E12, 20:E13",
    "A7b": "20:E1, 20:E12, 20:E13", "A8": "20:E9", "A9": "20:B7", "A10": "20:B1", "A11": "20:B2",
    "B1": "20:D2", "B2": "20:D3", "B3": "20:B8", "B4": "20:D4",
    "E1a": "20:C2", "E1b": "20:C2", "E1c": "20:C3", "E2a": "20:B11", "E2b": "20:B11", "E3": "20:C4", "E4": "20:C6",
}

BLOCK = {"A": "the shell theorem and the exact shell arithmetic",       # check-id prefix -> the block (the function block_<letter> below)
         "B": "the de-framing dictionary: zero density, the reconstruction residue, the horizon-length main sum",
         "E": "resonance, antipode, horizon-scale resolution, square-root cancellation"}

# the deciding check of each witnessed predicate, as the package names it; 20:E9 is decided by the package's C4 (block C,
# not reproduced), and A8 corroborates it
PREDICATES = {
    "20:B1": "A10", "20:B2": "A11", "20:B4": "A1", "20:B5": "A2", "20:B6": "A3", "20:B7": "A9", "20:B8": "A4", "20:B9": "A5",
    "20:B10": "A6", "20:B11": "E2a",
    "20:C2": "E1a", "20:C3": "E1c", "20:C4": "E3", "20:C6": "E4",
    "20:D2": "B1", "20:D3": "B2", "20:D4": "B4",
    "20:E1": "A7", "20:E12": "A7", "20:E13": "A7b",
}

R = Registry("20", "rh", LEDGER, PREDICATES, sources=[__file__])

for _p in SHELLS + [BIG]:
    assert arith.is_prime(_p) and _p % 4 == 1, _p


def next_prime(n):
    """The least prime above n."""
    n += 1
    while not arith.is_prime(n): n += 1
    return n


def carrier_of(p):
    """The Carrier chart of A11: the least prime ≡ 1 (mod 4) above p²."""
    om = next_prime(p * p)
    while om % 4 != 1: om = next_prime(om)
    return om


# ------------------------------------------------------------------------------------------------------------
# block A: the shell theorem and the exact shell arithmetic (20:B1–B10, E1, E12, E13)
# The zero-slot and slot complementarity; the Hermitian phase calculus on F_{p²} = F_p(η), η² = ν the least non-residue;
# the finite critical line Tr z = 1 ⟺ z = 2⁻¹ + bη, 2⁻¹ = 2κ + 1 = −π; the Klein four-group of Frobenius φ and the
# half-turn ρ : z ↦ 1 − z with its fixed loci; the Subject constants on the odd lift; the scale-shift on the power
# characters and its trace; the flat ground state c_p(n) = −1 in F_q; the shared core Q₄ of two shells; frame
# coincidence below the horizon. The generator g is the least primitive root, as in the package.
@R.block("A", BLOCK["A"])
def block_A():
    """Block A — the shell theorem and the exact shell arithmetic: 62 checks, 60 exact and 2 floating-point readings."""
    for p in SHELLS + [BIG]:
        g, nu = arith.primitive_root(p), arith.nonresidue(p)
        kappa = (p - 1) // 4
        # A1 zero-slot
        ok = all(zeta(p, k) == 0 for k in range(1, p - 1)) and zeta(p, p - 1) == p - 1
        # 20:B4 (p20011)
        R.check("A1", f"zero-slot on F_{p}", ok, f"Σx^k=0 for k=1..{p-2}; = -1 at k={p-1}")
        # A6 the Subject constants, capacity-first
        pi_ = 2 * kappa
        i_ = pow(g, p - 1 - kappa, p)                                       # g^{-κ}
        assert i_ == (-pow(g, kappa, p)) % p
        i_odd = i_ if i_ % 2 == 1 else i_ + p                               # the odd integer lift of i
        e_ = pow(g, i_odd, p)
        ok = ((2 * pi_) % p == p - 1 and (i_ * i_) % p == p - 1 and pow(g, pi_, p) == p - 1
              and pow(e_, i_odd * pi_, p) == p - 1 and (2 * (2 * kappa + 1)) % p == 1 and (2 * kappa + 1) % p == (-pi_) % p)
        # 20:B10 (p20017)
        R.check("A6", f"Subject constants on F_{p}: π=2κ, i=g^-κ, e=g^i (odd lift)", ok,
                f"g={g} κ={kappa} π={pi_} i={i_} e={e_}: 2π≡-1, i²≡-1, g^π≡-1, e^(iπ)≡-1, 2⁻¹=2κ+1=-π")
        # A4 the finite critical line
        K = Ext(p, nu)
        inv2 = (2 * kappa + 1) % p
        line = [(inv2, b) for b in range(p)]
        quarter = pow(4, p - 2, p)
        ok = all(2 * z[0] % p == 1 for z in line) and len(set(line)) == p \
            and all(K.norm(z) == (quarter - nu * z[1] * z[1]) % p for z in line)
        if p != BIG:                                                        # the converse on the full plane: Tr z = 1 only on the line
            ok = ok and all(((2 * a) % p == 1) == (a == inv2) for a in range(p))
        # 20:B8 (p20015)
        R.check("A4", f"finite critical line on F_{p}: Tr z = 1 ⟺ z = 2⁻¹ + bη, |L| = p, N = ¼ − νb²", ok, f"ν={nu}, 2⁻¹={inv2}")
        if p == BIG:
            continue
        # A2 slot complementarity
        image = {(-pow(g, k, p)) % p for k in range(1, p - 1)}
        # 20:B5 (p20012)
        R.check("A2", f"Φ(k) = −g^k bijects the nonterminal slots onto F_{p}^× \\ {{−1}}", image == set(range(1, p - 1)),
                f"|image| = {len(image)} = p−2")
        # A3 the Hermitian phase calculus: the circle U_{p+1}, Frobenius as inversion on it, i off the circle
        plane = K.elements()
        U = [z for z in plane if K.norm(z) == 1]
        inv_ok = all(K.conj(z) == K.pow(z, p) and K.mul(z, K.conj(z)) == (1, 0) for z in U)
        i2 = [(a, 0) for a in range(p) if (a * a) % p == p - 1]
        ok = len(U) == p + 1 and inv_ok and len(i2) == 2 and all(K.conj(z) == z and K.norm(z) == p - 1 for z in i2)
        # 20:B6 (p20013)
        R.check("A3", f"F_{p}²: |U_(p+1)| = p+1, Frobenius = inversion on it, i Frobenius-fixed with N(i) = −1", ok)
        # A5 the Klein four-group and its fixed loci
        rho = lambda z: ((1 - z[0]) % p, (-z[1]) % p)
        sig = lambda z: rho(K.conj(z))
        fix_phi = {z for z in plane if K.conj(z) == z}; fix_rho = {z for z in plane if rho(z) == z}
        fix_sig = {z for z in plane if sig(z) == z}
        ok = (all(K.conj(K.conj(z)) == z and rho(rho(z)) == z and K.conj(rho(z)) == rho(K.conj(z)) for z in plane)
              and fix_phi == {(a, 0) for a in range(p)} and fix_sig == set(line) and fix_rho == {(inv2, 0)}
              and fix_phi & fix_sig == {(inv2, 0)})
        # 20:B9 (p20016)
        R.check("A5", f"Klein four-group on F_{p}²: Fix φ = F_p, Fix σ = L_1/2, Fix ρ = {{2⁻¹}}, F_p ∩ L_1/2 = {{2⁻¹}}", ok)
        # A9 the flat ground state in exact arithmetic: ω of order p in F_q, q the least prime ≡ 1 (mod p)
        q = p + 1
        while not (q % p == 1 and arith.is_prime(q)): q += p
        om = pow(arith.primitive_root(q), (q - 1) // p, q)
        assert pow(om, p, q) == 1 and om != 1
        cp = [sum(pow(om, a * n, q) for a in range(1, p)) % q for n in range(1, p)]
        # 20:B7 (p20014)
        R.check("A9", f"c_{p}(n) ≡ −1 (mod {q}) for n ≠ 0: Σ_a ω^{{an}} in F_{q}, ω of order {p}", all(c == q - 1 for c in cp))
        # A7 the scale-shift on the power characters in F_p, and its trace
        ok_fp = all(pow((g * x) % p, k, p) == (pow(g, k, p) * pow(x, k, p)) % p for k in range(p - 1) for x in range(1, p))
        tr = [sum(1 for x in range(1, p) if (pow(g, r, p) * x) % p == x) for r in range(1, p)]
        ok_tr = all(tr[r - 1] == ((p - 1) if r % (p - 1) == 0 else 0) for r in range(1, p))
        # 20:E1 (p20032), 20:E12 (p20043)
        R.check("A7", f"F_{p}: S x^k = g^k x^k on the power characters (integer arithmetic); Tr S^r = (p−1)[(p−1)|r]", ok_fp and ok_tr)
        # A7b the complex reading on ℓ²(F_p^×): the chart's characters, tolerance 10⁻¹⁰
        ok_mean, ok_orth, ok_c, mean = CR.characters(p, g, prime_power_base)
        # 20:E13 (p20044)
        R.check("A7b", f"ℓ²(F_{p}^×): mean v̄ = ψ(p−1)/(p−1) on the trivial mode, v − v̄·1 on the nontrivial characters, χ_j/√(p−1) orthonormal; Sχ_j = ω^j χ_j",
                ok_mean and ok_orth and ok_c, f"v̄ = {mean:.6f} (= log 27720/12 at p = 13)" if p == 13 else "", kind="[approx]")
        # A10 the shared quarter-turn core; no cycle projection on the pair (13, 233)
        Om = 233
        q4 = {pow(i_, a, p) for a in range(4)}
        ok = q4 == {1, i_, p - 1, (-i_) % p} and (p - 1) % 4 == 0 and (Om - 1) % 4 == 0
        if p == 13:
            ok = ok and (Om - 1) % (p - 1) != 0
            # 20:B1 (p20008)
            R.check("A10", "Q₄ ⊂ both cycles; C_232 ↠ C_12 does not exist (12 ∤ 232) on the pair (13, 233)", ok, "the shells share the core, not a clock")
        else:
            R.check("A10", f"Q₄ = {{1, i, −1, −i}} ⊂ F_{p}^×, 4 | p−1", ok)
    # A11 frame coincidence below the horizon: the Carrier chart Ω the least prime ≡ 1 (mod 4) above p²
    for p in SHELLS + [1009, 10009]:
        Om = carrier_of(p)
        H = isqrt(p)
        same = all(n % p == n % Om == n for n in range(1, H + 1))
        prods = all((a * b) % p == (a * b) % Om == a * b for a in range(1, H + 1) for b in range(1, H + 1))
        irreducible = {n for n in range(2, H + 1) if all(n % d for d in range(2, isqrt(n) + 1))}   # trial division inside the window
        primes = {n for n in range(2, H + 1) if arith.is_prime(n)}
        # 20:B2 (p20009)
        R.check("A11", f"frame coincidence below √{p} = {H} on the pair ({p}, {Om}): residues, window products and primality agree",
                same and prods and irreducible == primes, f"Π_p = {sorted(primes)}")
    # A6b the odd-lift rule on every admissible frame below 3000, least primitive root
    frames = [q for q in range(5, 3000) if q % 4 == 1 and arith.is_prime(q)]
    bad = []
    for q in frames:
        gq = arith.primitive_root(q); kq = (q - 1) // 4; piq = 2 * kq
        r = pow(gq, q - 1 - kq, q)                                          # the least residue of i = g^{-κ}
        odd, even = (r, r + q) if r % 2 == 1 else (r + q, r)
        e_odd = pow(gq, odd, q)
        if not (pow(e_odd, odd * piq, q) == q - 1 and pow(e_odd, even * piq, q) == 1 and (r * r) % q == q - 1):
            bad.append(q)
    f17 = (pow(3, 16 - 4, 17), pow(3, 21, 17))                              # F_17, g = 3: i = 3^{-4} = 4 (even), lift 21, e = 3^21 = 5
    R.check("A6b", f"the odd-lift rule on all {len(frames)} frames p ≡ 1 (mod 4) below 3000: e^{{iπ}} ≡ −1 on the odd lift, ≡ +1 on the even member; F_17: g=3, i=4, lift 21, e=5",
            not bad and f17 == (4, 5), f"frames {len(frames)}, failures {bad}; F_17 (i, e) = {f17}")
    # A8 self-adjointness is free: the Lanczos matrix of ten heights (the chart, floating point)
    a, b, ev = CR.lanczos(CR.HEIGHTS[:10])
    dev = max(abs(x - y) for x, y in zip(ev, CR.HEIGHTS[:10]))
    R.check("A8", "any real multiset is the spectrum of a real-symmetric tridiagonal matrix (Lanczos on ten heights, floating point)",
            len(a) == 10 and len(b) == 9 and dev < Fr(1, 10 ** 11), f"max|eig(J) − height| = {dev:.1e}", kind="[approx]")


# ------------------------------------------------------------------------------------------------------------
# block B: the de-framing dictionary (20:D2–D4, B8)
# A shell of cardinality p reads ζ on the line to height T = 2πp with the Riemann–Siegel main sum of length √p. The
# zero density at T = 2πp is the shell scale-depth (1/2π) log p; the de-framing limit (2κ+1)/p → ½ from above (exact
# here, in rationals); the horizon-length main sum changes sign once per zero on [10, 55]; its residue against Hardy's Z
# falls as p^{−1/4}. The chart file computes θ by its asymptotic series and Z by Euler–Maclaurin, where the package
# called mpmath.
@R.block("B", BLOCK["B"])
def block_B():
    """Block B — the de-framing dictionary: 4 checks (2 CHART, 2 APPROX)."""
    stated = {50: Fr(6226, 10 ** 4), 500: Fr(9891, 10 ** 4), 5000: Fr(13556, 10 ** 4), 50000: Fr(17220, 10 ** 4)}
    T0 = [40, 80, 160, 320, 640, 1280, 2560, 5120]
    dens, sc, inwin, dev, err, slope = CR.deframe(list(stated), CR.linspace(10, 55, 700), T0)
    # 20:D2 (p20026)
    R.check("B1", "smooth zero density at T = 2πp is (1/2π) log p", all(abs(dens[p] - stated[p]) < Fr(6, 10 ** 5) for p in stated),
            "  ".join(f"p={p}: {dens[p]:.4f}" for p in stated), kind="[chart]")
    vals = [(p, Fr(2 * ((p - 1) // 4) + 1, p)) for p in [13, 53, 101, 409, 1009, 10009]]
    ok = all(v > Fr(1, 2) for _, v in vals) and all(vals[i][1] > vals[i + 1][1] for i in range(len(vals) - 1)) \
        and abs(vals[-1][1] - Fr(1, 2)) < Fr(1, 1000)
    R.check("B3", "de-framing limit (2κ+1)/p → ½ from above", ok, "  ".join(f"{p}: {CR.ratio(v, 1):.5f}" for p, v in vals), kind="[chart]")
    ok = len(sc) == len(inwin) and max(dev) < Fr(1, 2)
    # 20:D4 (p20028)
    R.check("B4", "the bare horizon-length main sum has one sign change per zero on [10,55], each within 0.5 of γ_n", ok,
            f"{len(sc)} sign changes for {len(inwin)} zeros; max deviation {max(dev):.2f} (1–2 terms only at these heights)", kind="[approx]")
    # 20:D3 (p20027)
    R.check("B2", "reconstruction residue ∝ p^{-1/4}: fitted log-log slope in [−0.40, −0.10]", Fr(-40, 100) < slope < Fr(-10, 100),
            f"slope = {slope:.3f}", kind="[approx]")


# ------------------------------------------------------------------------------------------------------------
# block E: resonance, antipode, horizon-scale resolution, square-root cancellation (20:B11, C2–C4, C6)
# The units-chart resonance R_L(n) = Σ_{q≤L} μ(q)/φ(q) c_q(n) with Kluyver's integer c_q(n), in rationals; Λ = μ ∗ log,
# exactly in its exponentiated form; Hardy's limit and the staircase against the logarithms (the chart); the per-mode
# energy μ²(q)/φ(q), its maximum at the antipode q = 2; the resolving threshold L*(H), exact; the band energies and the
# chart-mode correlations by Fourier transforms in the chart.
@R.block("E", BLOCK["E"])
def block_E():
    """Block E — the resonance and the von Mangoldt weight, the staircase, the antipode, the resolving band, the
    √p-flatness of the chart modes: 7 checks (2 EXACT, 5 APPROX)."""
    Qmax, Nmax = 320, 60
    mu, phi = mobius_phi(5000)
    cum = resonance(Qmax, Nmax, mu, phi)
    # E1a Λ = μ ∗ log: exactly for n ≤ 300 (Π_{d|n} d^{−μ(d)} = ℓ on ℓ^k, 1 elsewhere), in floating point for n ≤ 5000
    sym_ok = all(log_free_mangoldt(n, mu) == (prime_power_base(n) or 1) for n in range(2, 301))
    divs = [[] for _ in range(5001)]
    for d in range(1, 5001):
        for m in range(d, 5001, d): divs[m].append(d)
    flt = CR.mobius_log_deviation(5000, mu, lambda n: divs[n], prime_power_base)
    # 20:C2 (p20020)
    R.check("E1a", "Λ = μ ∗ log: −Σ_{d|n} μ(d) log d = Λ(n), symbolic for n ≤ 300, floating point for n ≤ 5000", sym_ok and flt < Fr(1, 10 ** 9),
            f"symbolic {'ok' if sym_ok else 'FAIL'}; max float deviation {flt:.1e}", kind="EXACT")
    # E1b Hardy's limit and the intertwiner: Cesàro means over L ≤ 4000 (the chart)
    Qhi = 4000
    pps = [2, 3, 4, 5, 7, 8, 9, 11, 13]; comp = [6, 10, 12, 14]
    Rm = CR.cesaro_means(Qhi, pps + comp, mu, phi, ramanujan_c)
    hardy, zero_ok, inter, Rf, lam = CR.hardy_limits(Rm, phi, prime_power_base, pps, comp)
    R.check("E1b", "Hardy: R_L(n) → (φ(n)/n) Λ(n) on prime powers, → 0 off them; intertwiner (n/φ(n)) R → Λ = log ℓ", hardy and zero_ok and inter,
            f"R(2) = {Rf[2]:.4f} vs ½ log 2 = {lam[2] / 2:.4f}; R(9) = {Rf[9]:.4f} vs ⅔ log 3 = {lam[9] * 2 / 3:.4f}; "
            f"(13/12) R(13) = {Rf[13] * 13 / 12:.4f} vs log 13 = {lam[13]:.4f}; max |R| off prime powers {max(abs(Rf[n]) for n in comp):.3f}", kind="[approx]")
    # E1c the staircase from the modes: Ψ_L(N) = Σ_{n≤N} (n/φ(n)) R_L(n) against ψ(N) on N ≤ 30
    def Psi(L):
        out, s = [], Fr(0)
        for n in range(2, 31):
            s += Fr(n, phi[n]) * cum[L][n]; out.append(s)
        return out
    devs = [CR.staircase_deviation(Psi(L), prime_power_base, 30) for L in (15, 60, 240)]
    # 20:C3 (p20021)
    R.check("E1c", "Ψ_L(N) → ψ(N) on N ≤ 30: maximal deviation falls monotonically over L = 15, 60, 240", devs[0] > devs[1] > devs[2],
            "max |Ψ_L − ψ| = " + ", ".join(f"{d:.3f}" for d in devs), kind="[approx]")
    # E2a the per-mode energy, exact
    E = {q: Fr(mu[q] ** 2, phi[q]) for q in range(2, 2001)}
    ok = (E[2], E[3], E[5], E[7]) == (Fr(1), Fr(1, 2), Fr(1, 4), Fr(1, 6)) and all(E[q] < 1 for q in E if q != 2)
    # 20:B11 (p20018)
    R.check("E2a", "per-mode energy μ²(q)/φ(q) = 1, ½, ¼, ⅙ at q = 2, 3, 5, 7; unique maximum among the nonconstant modes at the antipode q = 2 (2 ≤ q ≤ 2000)", ok,
            "energies " + ", ".join(f"q={q}: {E[q]}" for q in (2, 3, 5, 7, 11)), kind="EXACT")
    # E2b the additive-transform band energy of the prime indicator on Z/10007 (the chart's transform)
    p4 = 10007
    band = CR.band_energy([1 if arith.is_prime(n) else 0 for n in range(p4)], (2, 3, 5, 7))
    law = [band[q] * phi[q] / band[2] for q in (3, 5, 7)]
    stated = {2: 1153, 3: 592, 5: 301, 7: 205}
    ok = band[2] > band[3] > band[5] > band[7] and all(abs(band[q] - stated[q]) < 2 for q in stated) \
        and all(Fr(85, 100) < r < Fr(125, 100) for r in law)
    R.check("E2b", "additive-transform band energy of the prime indicator on Z/10007 (Parseval-normalised, bins within 3 of a/q): 1153 > 592 > 301 > 205, the law 1/φ(q)", ok,
            " > ".join(f"q={q}: {band[q]:.0f}" for q in (2, 3, 5, 7)) + "; φ(q)·E_q/E_2 = " + ", ".join(f"{r:.2f}" for r in law), kind="[approx]")
    # E3 the resolving threshold, in rationals
    Hs = list(range(6, 51, 2)); Ls = []
    for H in Hs:
        pp = [n for n in range(2, H + 1) if prime_power_base(n)]; npp = [n for n in range(2, H + 1) if not prime_power_base(n)]
        Ls.append(next((L for L in range(2, Qmax + 1) if min(cum[L][n] for n in pp) > max(abs(cum[L][n]) for n in npp)), None))
    ok = all(L is not None for L in Ls) and all(L < 6 * H for L, H in zip(Ls, Hs)) and all(L < H * H for L, H in zip(Ls, Hs) if H >= 8)
    ratio = [Fr(L, H) for L, H in zip(Ls, Hs)]
    # 20:C4 (p20022)
    R.check("E3", "resolving threshold L*(H) exists for H = 6..50 and tracks the horizon: L* < 6H ≪ H²", ok,
            f"L*/H in [{CR.ratio(min(ratio), 1):.2f}, {CR.ratio(max(ratio), 1):.2f}]; L*(12) = {Ls[Hs.index(12)]}, L*(20) = {Ls[Hs.index(20)]}, L*(50) = {Ls[-1]}", kind="[approx]")
    # E4 square-root cancellation of every chart mode (the chart's FFT over the discrete logarithm)
    def dlog(p):
        g, out, x = arith.primitive_root(p), {}, 1
        for k in range(p - 1): out[x] = k; x = x * g % p
        return out
    m1, f1, _ = CR.mode_correlations(1009, dlog(1009), arith.is_prime)
    p5 = next_prime(100_000)
    while p5 % 4 != 1: p5 = next_prime(p5)
    m5, f5, _ = CR.mode_correlations(p5, dlog(p5), arith.is_prime)
    cum200 = resonance(80, 200, mu, phi)
    rn = range(2, 201)
    res_corr = CR.pearson([1 if arith.is_prime(n) else 0 for n in rn], [cum200[80][n] for n in rn])
    ok = (abs(m1 - Fr(77, 1000)) < Fr(5, 1000) and abs(f1 - Fr(315, 10 ** 4)) < Fr(5, 10 ** 4) and abs(m1 / f1 - Fr(243, 100)) < Fr(3, 100)
          and abs(m5 - Fr(87, 10 ** 4)) < Fr(5, 10 ** 4) and abs(f5 - Fr(32, 10 ** 4)) < Fr(1, 10 ** 4) and abs(m5 / f5 - Fr(275, 100)) < Fr(3, 100)
          and res_corr > Fr(85, 100))
    # 20:C6 (p20024)
    R.check("E4", "max chart-mode correlation with the primes is a small multiple of the 1/√(p−2) floor: 0.077 vs 0.0315 (p = 1009, 2.4×), 0.0087 vs 0.0032 (p = 100049, 2.7×); resonance correlates 0.90", ok,
            f"p = 1009: max {m1:.4f}, floor {f1:.4f}, ratio {m1 / f1:.3f}; p = {p5}: max {m5:.4f} over {(p5 - 1) // 2} mode pairs, floor {f5:.4f}, ratio {m5 / f5:.3f}; corr(1_Π, R_80) on n ≤ 200 = {res_corr:.2f}", kind="[approx]")


if __name__ == "__main__":
    want = [a.upper() for a in sys.argv[1:]] or sorted(BLOCK)
    bad = [b for b in want if b not in BLOCK]
    if bad: sys.exit(f"no block {', '.join(bad)}: the blocks are {', '.join(sorted(BLOCK))}")
    for b in want: R.run_block(b)
    sys.exit(0 if R.summary(write=False, expect=list(LEDGER) if want == sorted(BLOCK) else None) else 1)
