import FrcCore.Keys.Carrier

/-!
# FrcCore.Ledgers.Master.Carrier — the certificate of the master's block B, core (ledger migration, task LM22)

Generated by `ci/make_ledgers.py` from the master's data (`docs/00-ledger.json`), the ledger file's `PROOFS` and the key files. One
`#print axioms` per key of the ledger that this library proves, guarded by the message it must print: the build
fails if a key's axioms change (no axioms). Nothing imports this file; `lake build FrcCore.Ledgers.Master.Carrier` checks it.
-/

-- 00:B5 (p00015)
/-- info: 'FRC.Ledger.p00015' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p00015

-- 00:B7 (p00165)
/-- info: 'FRC.Ledger.p00165' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p00165

-- 00:B8 (p00166)
/-- info: 'FRC.Ledger.p00166' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p00166

-- 00:B10 (p00168)
/-- info: 'FRC.Ledger.p00168' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p00168

-- 00:B14 (p00170)
/-- info: 'FRC.Ledger.p00170' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p00170
