import FrcCore.Keys.Foundation

/-!
# FrcCore.Ledgers.Master.Foundation — the certificate of the master's block A, core (ledger migration, task LM22)

Generated by `ci/make_ledgers.py` from the master's data (`docs/00-ledger.json`), the ledger file's `PROOFS` and the key files. One
`#print axioms` per key of the ledger that this library proves, guarded by the message it must print: the build
fails if a key's axioms change (no axioms). Nothing imports this file; `lake build FrcCore.Ledgers.Master.Foundation` checks it.
-/

-- 00:A5 (p00159)
/-- info: 'FRC.Ledger.p00159' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p00159

-- 00:A7 (p00160)
/-- info: 'FRC.Ledger.p00160' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p00160

-- 00:A12 (p00162)
/-- info: 'FRC.Ledger.p00162' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p00162

-- 00:A13 (p00163)
/-- info: 'FRC.Ledger.p00163' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p00163

-- 00:A14 (p00164)
/-- info: 'FRC.Ledger.p00164' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p00164
