import FrcCore.Keys.Fourier

/-!
# FrcCore.Ledgers.Master.Fourier — the certificate of the master's block C, core (ledger migration, task LM22)

Generated by `ci/make_ledgers.py` from the master's data (`docs/00-ledger.json`), the ledger file's `PROOFS` and the key files. One
`#print axioms` per key of the ledger that this library proves, guarded by the message it must print: the build
fails if a key's axioms change (no axioms). Nothing imports this file; `lake build FrcCore.Ledgers.Master.Fourier` checks it.
-/

-- 00:C2 (p00022)
/-- info: 'FRC.Ledger.p00022' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p00022

-- 00:C7 (p00172)
/-- info: 'FRC.Ledger.p00172' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p00172
