import FrcCore.Keys.Gravity

/-!
# FrcCore.Ledgers.Master.Gravity — the certificate of the master's block E, core (ledger migration, task LM22)

Generated by `ci/make_ledgers.py` from the master's data (`docs/00-ledger.json`), the ledger file's `PROOFS` and the key files. One
`#print axioms` per key of the ledger that this library proves, guarded by the message it must print: the build
fails if a key's axioms change (no axioms). Nothing imports this file; `lake build FrcCore.Ledgers.Master.Gravity` checks it.
-/

-- 00:E6 (p00176)
/-- info: 'FRC.Ledger.p00176' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p00176

-- 00:E7 (p00058)
/-- info: 'FRC.Ledger.p00058' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p00058
