import FrcCore.Keys.Quantum

/-!
# FrcCore.Ledgers.Master.Quantum — the certificate of the master's block F, core (ledger migration, task LM22)

Generated by `ci/make_ledgers.py` from the master's data (`docs/00-ledger.json`), the ledger file's `PROOFS` and the key files. One
`#print axioms` per key of the ledger that this library proves, guarded by the message it must print: the build
fails if a key's axioms change (no axioms). Nothing imports this file; `lake build FrcCore.Ledgers.Master.Quantum` checks it.
-/

-- 00:F2 (p00191)
/-- info: 'FRC.Ledger.p00191' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p00191

-- 00:F5 (p00194)
/-- info: 'FRC.Ledger.p00194' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p00194
