import FrcCore.Keys.Fourier
import FrcCore.Keys.Frame

/-!
# FrcCore.Ledgers.P06Fourier — the certificate of the ledger of 6-fourier, core (ledger migration, task LM20)

Generated by `ci/make_ledgers.py` from the ledger (`docs/6-fourier/6-fourier-ledger.json`) and the key files. One
`#print axioms` per key of the ledger that this library proves, guarded by the message it must print: the build
fails if a key's axioms change (no axioms). Nothing imports this file; `lake build FrcCore.Ledgers.P06Fourier` checks it.
-/

-- 6:B2 (p06009)
/-- info: 'FRC.Ledger.p06009' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p06009

-- 6:B3 (p06010)
/-- info: 'FRC.Ledger.p06010' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p06010

-- 6:B5 (p06012)
/-- info: 'FRC.Ledger.p06012' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p06012

-- 6:B6 (p06013)
/-- info: 'FRC.Ledger.p06013' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p06013

-- 6:B7 (p06014)
/-- info: 'FRC.Ledger.p06014' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p06014

-- 6:C2 (p06016)
/-- info: 'FRC.Ledger.p06016' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p06016

-- 6:C3 (p06017)
/-- info: 'FRC.Ledger.p06017' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p06017

-- 6:C4 (p06018)
/-- info: 'FRC.Ledger.p06018' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p06018

-- 6:C5 (p06019)
/-- info: 'FRC.Ledger.p06019' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p06019

-- 6:C7 (p06021)
/-- info: 'FRC.Ledger.p06021' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p06021

-- 6:C8 (p06022)
/-- info: 'FRC.Ledger.p06022' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p06022

-- 6:C9 (p06023)
/-- info: 'FRC.Ledger.p06023' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p06023

-- 6:D1 (p06024)
/-- info: 'FRC.Ledger.p06024' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p06024

-- 6:D2 (p06025)
/-- info: 'FRC.Ledger.p06025' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p06025

-- 6:D4 (p06027)
/-- info: 'FRC.Ledger.p06027' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p06027

-- 6:D5 (p06028)
/-- info: 'FRC.Ledger.p06028' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p06028

-- 6:D7 (p06053)
/-- info: 'FRC.Ledger.p06053' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p06053

-- 6:C6 (p06020)
/-- info: 'FRC.Ledger.p06020' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p06020

-- 6:C11 (p06052)
/-- info: 'FRC.Ledger.p06052' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p06052
