import FrcCore.Keys.Horizon

/-!
# FrcCore.Ledgers.P20Rh — the certificate of the ledger of 20-rh, core (ledger migration, task LM20)

Generated by `ci/make_ledgers.py` from the ledger (`docs/20-rh/20-rh-ledger.json`) and the key files. One
`#print axioms` per key of the ledger that this library proves, guarded by the message it must print: the build
fails if a key's axioms change (no axioms). Nothing imports this file; `lake build FrcCore.Ledgers.P20Rh` checks it.
-/

-- 20:B1 (p20008)
/-- info: 'FRC.Ledger.p20008' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p20008

-- 20:B2 (p20009)
/-- info: 'FRC.Ledger.p20009' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p20009

-- 20:B4 (p20011)
/-- info: 'FRC.Ledger.p20011' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p20011

-- 20:B5 (p20012)
/-- info: 'FRC.Ledger.p20012' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p20012

-- 20:B6 (p20013)
/-- info: 'FRC.Ledger.p20013' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p20013

-- 20:B7 (p20014)
/-- info: 'FRC.Ledger.p20014' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p20014

-- 20:B8 (p20015)
/-- info: 'FRC.Ledger.p20015' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p20015

-- 20:B9 (p20016)
/-- info: 'FRC.Ledger.p20016' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p20016

-- 20:B10 (p20017)
/-- info: 'FRC.Ledger.p20017' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p20017

-- 20:E1 (p20032)
/-- info: 'FRC.Ledger.p20032' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p20032

-- 20:E12 (p20043)
/-- info: 'FRC.Ledger.p20043' does not depend on any axioms -/
#guard_msgs in
#print axioms FRC.Ledger.p20043
